### ISSUE TITLE
Put request with multipartform/data content type sends an empty request

### ISSUE THREAD

**Issue by Khader-1** [cfug/dio#1081]
### New Issue Checklist

- I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter / web / android                          |      |
| Dio Version                    | 3.0.0                                  |      |
| Repro rate                     |  all the time (100%)    |      |

### Issue Description and Steps

when sending a put/patch request with data being a FormData object it just sends empty body, I have tried to set the "Content-Type" to "multipart/form-data" but nothing changed.

**Comment by fuadarradhi** [comment]
same here

**Comment by BigBrosh** [comment]
I've seen similar issue on 2018
https://github.com/flutterchina/dio/issues/88

Suggestion in this issue was to send map instead of form data
But I'd like my library to be able to send form data and attach multipart files as part of request
It's crucial
Please take a look

I can also see that there's actually logic both for form data and multipart files
![image](https://user-images.githubusercontent.com/30599468/116284812-2bff0b80-a796-11eb-8b9c-b79b5ad85e9e.png)

**Comment by Khader-1** [comment]
> 
> 
> I've seen similar issue on 2018
> #88
> 
> Suggestion in this issue was to send map instead of form data
> But I'd like my library to be able to send form data and attach multipart files as part of request
> It's crucial
> Please take a look
> 
> I can also see that there's actually logic both for form data and multipart files
> ![image](https://user-images.githubusercontent.com/30599468/116284812-2bff0b80-a796-11eb-8b9c-b79b5ad85e9e.png)

I've seen that one..
As you said I'd like to send multipart files, BTW I ended up switching all the PUT mapping endpoints in my server to POST mapping😞

**Comment by Manguelo** [comment]
Having the same issue.

**Comment by naaando** [comment]
Seems to happen to me, unfortunally it is very hard to understand at first

**Comment by MostafaSolimanMO** [comment]
I am having this issue with dio ^5.3.2
Why is this closed?

**Comment by augustineonu** [comment]
> I am having this issue with dio ^5.3.2 Why is this closed?

im having this issue too

  Future<void> update1() async {
    try {
      var formData = dio.FormData.fromMap({
        'fullName': fullNameController.text,
        'file': await dio.MultipartFile.fromFile(pickedImagePath.value,
            filename: pickedImagePath.value)
      });

      final response = await userService.updateProfile(payload: formData);
      if (response.status == 'success') {
        logger.log("Success:: ${response.message!}");
      } else {
        logger.log("Success:: ${response.message!}");
      }
    } catch (exception) {
      logger.log("failed:: ${exception.toString()}");
    }
  }
  
  this is a PUT reuqest. but now it send the finstance of the file and not the file path as supposed string.

**Comment by AlexV525** [comment]
Please submit new issues with minimal reproducible examples and updated info. We're generally not handling issues before Feb 13, 2023.
