### ISSUE TITLE
Connect + Receive timeout options are not working on downloads

### ISSUE THREAD

**Issue by mikezander** [cfug/dio#1163]

**Comment by ThiagoFontes** [comment]
I have tested on Flutter version 2.0.3, iOS 14 and bio 4.0.0, and timeout times weren't working.

**Comment by shijianit** [comment]
Very disappointed with the development team and turned a blind eye

**Comment by fernando-s97** [comment]
Timeout not working here also

**Comment by fernando-s97** [comment]
Problem still happening....

**Comment by fernando-s97** [comment]
Still

**Comment by SouthSnow** [comment]
Still GET

**Comment by mikezander** [comment]
even after upgrading to 5.0.1, receive timeout is not working. Even though I'm successfully downloading and receiving data, it throws a timeout error after the duration.
