### ISSUE TITLE
there are too many DioErrorType.connectTimeout reported in sentry

### ISSUE THREAD

**Issue by catmaomao** [cfug/dio#1230]
DioError [DioErrorType.connectTimeout]: Connecting timed out [50000ms]
#0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819)
#1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678)
<asynchronous suspension>
#2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:586)
<asynchronous suspension>

I have a timer task that requests the network every 30 seconds.
But I found a lot of network connection timeout problems in sentry background, I don't know why?

**Comment by macortesn** [comment]
I have the same issue, it's random. I try make any request the request fails and try again and the request works fine. I'm using the lastest version of Dio.
![image](https://user-images.githubusercontent.com/21014156/134278773-2ca943aa-47cb-42ed-8fdc-83984c7bf20c.png)

**Comment by lirantzairi** [comment]
I'm also getting this issue. I have a service running periodically every 3 minutes. Crashlytics shows that in production hundreds of users are getting connectTimeout from Dio. @wendux Any update please?

**Comment by kuhnroyal** [comment]
Is everyone here using the http2 adapter?

**Comment by namdp** [comment]
any update? getting too much errors

**Comment by kuhnroyal** [comment]
@namdp Can you answer my previous question?

**Comment by namdp** [comment]
> @namdp Can you answer my previous question?

@kuhnroyal. No, i'm not use  http2 adapter

**Comment by kuhnroyal** [comment]
Thanks, unfortunately I don't see what can be done here.
I also use Dio in production apps and there are many timeouts in Sentry, but usually they are just connection problems that you have to live with in mobile development.

**Comment by votruk** [comment]
The bug is happening in my project as well. Did anybody find a solution except retrying? I'm not using the http2 adapter btw.

**Comment by MohamedSonata** [comment]
If you are using a Localserver:  You Should every time when you restart your pc  changing the IP Address 

`BaseOptions(
          baseUrl:  /// here changing the ip address every time after restart the internet or the pc to your local ip address Example :http://192.168.1.4: server port,
 
          receiveDataWhenStatusError: true,
        ));`

and same solution for your Online domain be sure is the correct URL You're using

**Comment by OmarBakry-Globalits** [comment]
This problem still occurs till now I don't know why this issue marked as closed please open it again I'm using the latest version of Dio (dio: ^5.0.1) and still getting connection timeout every time although the code was working yesterday without any update !!!

I'm using this API
https://www.boredapi.com/api/activity/

**Comment by kuhnroyal** [comment]
It is very likely that there is nothing wrong in dio here, this ticket is not actionable. In mobile connectivity, timeouts are not unusual. If you have a specific use case were you think this occurs and you think it may be a problem with dio, please create a new issue following the template and include a reproducible sample.

Also check the configuration of your timeouts and try with the defaults instead, if you have custom timeouts set.

**Comment by daniel-py** [comment]
> It is very likely that there is nothing wrong in dio here, this ticket is not actionable. In mobile connectivity, timeouts are not unusual. If you have a specific use case were you think this occurs and you think it may be a problem with dio, please create a new issue following the template and include a reproducible sample.
> 
> Also check the configuration of your timeouts and try with the defaults instead, if you have custom timeouts set.

Hi there,
I have noticed this error shows up on IOS devices when the app is backgrounded. I am not the only one who has noticed this. There was an issue opened on this in 2019 that was never resolved but got closed by the bot.
ONCE THE APP GETS BACKGROUNDED ON IOS (not too sure about Android), dio throws this error: DioErrorType.CONNECT_TIMEOUT
