### ISSUE TITLE
Cyclic dependency with dio and interceptor

### ISSUE THREAD

**Issue by douglasiacovelli** [cfug/dio#1286]
### New Issue Checklist

- [X] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter                        |      |
| Platform Version               | e.g.  any                              |      |
| Dio Version                    | e.g.  4.0.0                                  |      |
| Android Studio / Xcode Version | e.g. any              |      |
| Repro rate                     | e.g. all the time  |      |
| Repro with our demo prj        | e.g. does it happen with our demo project?            |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
Use case: when a 401 occurs I must retry the failing request after refreshing the token. The issue is that the Dio instance depends on the interceptor and the interceptor depends this Dio instance in order to retry the request.

I feel like it would be a better design if we could avoid this cyclic dependency and I see two ways of exposing this API even though I haven't thought of how to execute this:

1. Having a handler like `RequestInterceptorHandler` on the `onError` callback. This way we could just update the set of request options and let it retry.
2. Receive the Dio instance that the interceptor is attached to via method params of the `onError` callback.

WDYT?

**Comment by wendux** [comment]
Using a **new** dio instance  in interceptor.

**Comment by realshovanshah** [comment]
@wendux Isn't there any other way to solve this except for creating a new instance?

**Comment by CyJaySong** [comment]
> @wendux除了创建新实例之外，没有其他方法可以解决此问题吗？

no

**Comment by realshovanshah** [comment]
@douglasiacovelli Have a look.
https://github.com/flutterchina/dio/issues/1088#issuecomment-814016908

Thanks to @mauriziopinotti I believe we finally have an answer.
