### ISSUE TITLE
CancelToken 取消请求后异常

### ISSUE THREAD

**Issue by xiejibiao** [cfug/dio#1287]
### 使用 CancelToken 取消请求，请求已被取消，但还会抛出 Receiving data timeout 异常

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name              | |ios 、android
| Platform Version           |  2.2.3
| Dio Version                    | 4.0.0

**Comment by wendux** [comment]
try with 4.0.5-betal1
