### ISSUE TITLE
Upload file from bytes on android

### ISSUE THREAD

**Issue by maikelohcfg** [cfug/dio#1302]
| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
Platform Name                  android
Platform Version               2.5.2
Dio Version                    4.0.0
Android Studio  2020.3
Repro rate                     all the time (100%) 

### Issue Description and Steps
Hello everyone i try to upload multiple images from bytes source on Android, on debug i can see the file on formdata but on server  i don't receive the file parameter and data, others fields submitted on the request reach the server properly but the file parameters is missing

`  formData.files.addAll([
      MapEntry(
      'evidences[]',
      MultipartFile.fromBytes(
      snapshot,
      filename: const Uuid().v4(),
      ),
      ),
      ]);`

**Comment by ccchp** [comment]
same issue,I use MultipartFile.fromBytes will cause DioError [DioErrorType.other]: HttpException: Read failed, uri=***
when I change to use fromFile ,It's ok , any dio vesion

**Comment by Hwan-seok** [comment]
Same as IOS

**Comment by suqinglin113x** [comment]
fromFile is work, but i can't compress image by this way.
