### ISSUE TITLE
Dio makes POST request fine in the debug version of the app but doesn't in release.

### ISSUE THREAD

**Issue by Vairochan** [cfug/dio#1320]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter / ios / android                          |      |
| Platform Version               | e.g.  1.5.0 / 12.0 / 9.0                              |      |
| Dio Version                    |4.0.3                                  |      |

### Issue Description and Steps

Please fill in the detailed description of the issue (full output of any stack trace, compiler error, ...) and the steps to reproduce the issue.

**Comment by jgoyvaerts** [comment]
This issue doesn't provide any useful information. Please update your issue with a minimal working code sample which reproduces your issue.

**Comment by TheHazeEffect** [comment]
Hey, So I just resolved an issue relating to this but with a GET request

I noticed if the leading "/' is missing it will be automatically added in debug mode but not in release

resulting in your API calls working on debug but not in release mode

Essentially...

@GET('/stores/{companyId}/inventory/wip?includeItems=true&limit={limit}&offset={offset}&order=ASC') 

results in "baseUrl/stores..."

VS

@GET('stores/{companyId}/inventory/wip?includeItems=true&limit={limit}&offset={offset}&order=ASC') (Fails)
resulting in "baseurlstore" which would give you a Host not found exception
