### ISSUE TITLE
Implement pause / resume feature

### ISSUE THREAD

**Issue by prateekmedia** [cfug/dio#1323]
### Feature request Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Feature request

There were many stale issues on dio's issue tracker like flutterchina/dio#1020 flutterchina/dio#399 flutterchina/dio#395. Pause and resume for downloads are always good for a better downloading experience.

This can be added by replacing CancelToken with more advanced DownloadToken or DioToken, which will contain all action like .cancel, .pause, .resume or isCancelled, isPaused, isResumed or something like that.

This can be inspired from an existing package called flowder.

**Comment by wendux** [comment]
... I think this feature would be better implemented in another new package for two reasons:
1. The `dio.download` API was originally designed for **simple** download scenarios; A powerful downloader is very complex.
2. To support it, the server needs to implement the HTTP Range protocol. Not all servers support HTTP Range.

**Comment by prateekmedia** [comment]
I would be happy to create it, but I don't have the knowledge of how the pause/resume/multi-threading functions will be implemented in it.
