### ISSUE TITLE
Freeze on large upload

### ISSUE THREAD

**Issue by gwen1230** [cfug/dio#1328]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Web                          |      |
| Platform Version               |                              |      |
| Dio Version                    | 4.0.4                                  |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2 / Xcode 10.2.1              |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        |             |      |
| Demo project link              |  |      |

### Issue Description and Steps

When i try to upload large file (e.g 10Mb) using this code,
```
await dio.post(
  URL,
  data: formData,
);
```
I have freeze UI about 10/20 seconds.

**Comment by jgoyvaerts** [comment]
Can reproduce.
Right now the flow for web upload is:
- post()
- request()
- fetch()
- _dispatchRequest
- _transformData
- httpClientAdapter.fetch

The transformData step transforms a Uint8list to an utf8 string, then chunks it up in groups of 1024 bytes, then converts it into a Stream.
The browser adapter then takes that Stream and puts it all together again. 

We should just send the uint8list straight away without the conversion to utf8 and without the splitting into groups (we can use browser xhr.onprogress event for supporting data sending progress), that should fix most performance issues.

@wendux this is quite a big change, do you want to take a look at this?

**Comment by wendux** [comment]
try with 4.0.5-beta1

**Comment by gwen1230** [comment]
This version doesn't seem compatible with dart 2.14.4. there is an error in browser_adapter.dart, we call unawaited with a potentialy null value, and this isn't possible since 2.14.0

**Comment by kuhnroyal** [comment]
The problem happened due to merge errors after removing the `pedantic` dependency with the old `unawaited`.
You can try using the latest develop as dependency and see if that works for you.

**Comment by gwen1230** [comment]
Hi ! I would like to test this version but i can't because i also depend on dio_cookie_manager and i have this error when i try to use latest develop as dependency : 
![image](https://user-images.githubusercontent.com/6987769/144029402-b0d53825-5eb7-46ee-ae9d-2a02dfc7a48d.png)

Is it possible to create a tag and publish it ?

**Comment by kuhnroyal** [comment]
You can add it like this for testing:

```
dependency_overrides:
	dio:
		git: ...
```

**Comment by gwen1230** [comment]
That sounds good to me ! There is no more freeze !
When will the release be available?

**Comment by kuhnroyal** [comment]
That's good to hear.
Not sure yet.

**Comment by YaWaiAung** [comment]
Hi
I have same issue.
I'm using 4.0.3 and freeze unit done when downloading large file with dio.download();

`     await _dio.download(model.url, savePath,
          onReceiveProgress: (received, total) {
        if (total != -1) {
          model.progress =
              int.parse((received / total * 100).toStringAsFixed(0));
          // downloadCallback(model.id, model.status, model.progress);
          _showNotification(model);
        }
      })`

**Comment by YaWaiAung** [comment]
Hi @kuhnroyal 
 I tried with 4.0.5-beta1. But I still have this issue.
#1328 this issue is about freeze on large file upload.
My issue #1356  is about freeze on downloading large file.
Please check again.
Thank for your time.
