### ISSUE TITLE
Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by hc79879** [cfug/dio#1350]
Flutter Web  request failed，Unsupported operation: Platform._operatingSystem
Flutter：2.5.3
dio：4.0.4

**Comment by kuhnroyal** [comment]
Can you add a full stacktrace please

**Comment by cirelir** [comment]
我也有同样的问题
dio：4.0.4
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/15341952/146889188-3fff5899-88c2-4e1c-89b4-dd6b4c7f6b8c.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/15341952/146889692-5d265b50-677b-47a2-8df8-8c2e56ac6250.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/15341952/146888711-4a92255b-ecaf-4f7d-a78e-2308fea86c65.png">

**Comment by kuhnroyal** [comment]
I need the full stacktrace , not screen shots.
We don't use any `Platform.*` in the library, so it is likely cause by your code.

**Comment by json1994** [comment]
I have the same problem, how to fix? 
dio: ^4.0.6

**Comment by DirtyNative** [comment]
Same here, I just use dio in combination with retrofit

**Comment by kuhnroyal** [comment]
Create a repro and open a new issue.
