### ISSUE TITLE
when upload a big file use multipart form, the memory grow fast and OOM

### ISSUE THREAD

**Issue by baneyue** [cfug/dio#1359]
is there any solutions???

**Comment by kuhnroyal** [comment]
Please provide more information and possibly a sample.

**Comment by BodenTide** [comment]
I also encountered！

**Comment by BodenTide** [comment]
I also encountered！The following is my code snippet. When I use the original dio adapter, the OOM problem will not be reported.
`Dio uploadDio = Dio()..httpClientAdapter = NativeAdapter();
        FormData fileData = FormData.fromMap({
          "file": MultipartFile.fromStream(() => file.openRead(start, end), len, filename: "ac.abc"),
        });
        await uploadDio.post(
          'xxxxxxx',
          data: fileData,
          options: Options(
            headers: {
              Headers.contentLengthHeader: len,
            },
          ),
          onSendProgress: (c, t) {
            var current = x + c; // x是已经上传成功的长度 c是当前请求已经上传的长度。
            var total = fileLength;
            print("cccc >>> $c || t >>> $t || current >>> $current || total >> $total");
          },
        )`

**Comment by Thioby** [comment]
Agree, problem still exsits. Just try to send huge  file:

```
 final fileData = MultipartFile.fromStream(
      () => file.openRead(),
      fileLength,
      filename: 'nah.dio'
    );

    final FormData formData = FormData.fromMap({
      'memoryleak': fileData,
    });

    final Response<dynamic> rawResponse = await dio.post<dynamic>(
      'http://multipart.does.leak.memory/somehow`,
      data: formData,
      onSendProgress: (sent, total) {
        progressCallback.call(sent, total);
      },
    );
```

**Comment by kuhnroyal** [comment]
We need a full sample and environment information, file size, sample file etc. Anything else does not help.

**Comment by dannnoon** [comment]
You can simply take any file and look at the memory pressure during its upload. It will always be dependent on target device if it crashes or not. For me uploading 1.76GB file on iPhone 12 is causing crash.
I think at fault is `FormData.finalize` method, I was able to get rid of the issue by reimplementing the FormData class and changing `finalize` implementation to this
``` 
@override
  Stream<List<int>> finalize() {
    if (isFinalized) {
      throw StateError(
        'The FormData has already been finalized. '
        'This typically means you are using '
        'the same FormData in repeated requests.',
      );
    }
    _isFinalized = true;

    return Rx.concat(
      [
        for (final entry in fields) ...[
          Stream.fromIterable([
            utf8.encode('--$boundary\r\n'),
            utf8.encode(_headerForField(entry.key, entry.value)),
            utf8.encode(entry.value),
            utf8.encode('\r\n'),
          ]),
        ],
        for (final file in files) ...[
          Stream.fromIterable([
            utf8.encode('--$boundary\r\n'),
            utf8.encode(_headerForFile(file)),
          ]),
          file.value.finalize(),
          Stream.fromIterable([
            utf8.encode('\r\n'),
          ]),
        ],
        Stream.fromIterable([
          utf8.encode('--$boundary--\r\n'),
        ]),
      ],
    );
  }
```

**Comment by Thioby** [comment]
What is unclear here?
Grab any file which is large enough. Like 4k 60fps 3:00 min long video.  (around 2.65GB) and try to send this file as MultipartFile to any backend.

**Comment by AlexV525** [comment]
> What is unclear here?

Details. All the above comments are regardless of platforms and versions. Others like `NativeAdapter` and `Rx.concat` are also uncleared with their identity.

Please submit new issues with reproducible examples so we can take further action. We generally don't handle issues submitted before 2023-02-13.
