### ISSUE TITLE
parameter savePath in method download can receive Future<String> savePath(Headers value)

### ISSUE THREAD

**Issue by zae1403** [cfug/dio#1360]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Description and Steps

parameter savePath can receive Future<\String> savePath(Headers value)

**Comment by kuhnroyal** [comment]
Please provide more information

**Comment by AlexV525** [comment]
Hi @zae140. We've made our hardfork repo public and published a new version of `dio`, named `diox`.
The new package contains the PR of the fix.
Please refer to https://pub.dev/packages/diox/versions/5.0.0-dev.1 to use the fork.
You can also see why we're working for a hardfork at https://github.com/cfug/diox/issues/29 and https://github.com/flutterchina/dio/issues/1607.
