### ISSUE TITLE
when response is a json array, the quotation lost, and the jsondecode get error.

### ISSUE THREAD

**Issue by heliping** [cfug/dio#1363]
when response json is ok.
` 
 收到了数据: {"A":"bbbb","B":"11817"}`
but when the respones is json array, the response delete the quotation.
`
收到了数据: [{A: bbbb, B: 11817}, {A: bbbb, B: 11817}]`
so the json decode return the error.
`
 FormatException: Unexpected character (at character 3)
[{A: bbbb, B: 11817}, {A: bbbb, B: 11817}]
  ^`

my code：
`
response = await dio.post(url, data: queryP);`

**Comment by kuhnroyal** [comment]
Can you provide a reproducible sample?

**Comment by heliping** [comment]
just set a server, with response a list json struct. 
I changed to flutter http pub package, the error disappeared.
