### ISSUE TITLE
await dio.post error

### ISSUE THREAD

**Issue by mhmmdaminn** [cfug/dio#1364]
i have an error about login service for flutter web

with the same code login service it works on flutter mobile

i think the error on dio.post
i get an information from log error.StatusCode

Future loginService(LoginParameterPost value) async {
    print("running service login");
    var deviceId = await SharedPreferencesHelper.getDeviceId();
    var deviceName = await SharedPreferencesHelper.getBrandDevice();
    var deviceMode = await SharedPreferencesHelper.getModelDevice();
    var ssn = await SharedPreferencesHelper.getSsn();

    print("Device ID : ${deviceId} "
        "Device Name : ${deviceName}"
        "Device Mode : ${deviceMode}");

    var connectivityResult = await (Connectivity().checkConnectivity());

    String ipAddress;
    if (connectivityResult == ConnectivityResult.mobile) {
      ipAddress = await Ipify.ipv4();
    } else if (connectivityResult == ConnectivityResult.wifi) {
      ipAddress = await Ipify.ipv4();
    }
    print("RESULT CEK KONEKTIFITAS : $connectivityResult");

    var body = {
      "username": value.username,
      "password": value.password,
      "browser_agent": "$deviceId $deviceName $deviceMode",
      "ip_address": ipAddress,
      "id_api": "web",
      "ip_server": "68",
      "req_id": DateTime.now().millisecondsSinceEpoch.toString(),
      "ssn": ssn
      //"deviceIdbaf57f8802d1181c" // untuk debug komen ini
   };
    print("body : ${body}");
    print("UriApi: ${UriApi.loginUrl}");
    print("baseUriApi : ${dio.options.baseUrl}");

    try {
      log.info("AMIN");
      log.info ("data : ${value.password}"
          "deviceID : ${deviceId}"
          "ipAddress :${ipAddress}"
          "deviceMode :${deviceMode}");
      final response = await dio.post(
        UriApi.loginUrl,
        options: Options(
          headers: {
            'Content-Type': 'application/json',
          },
        ),
        data: body
      );

      log.info("\n\n> RESPONSE SERVICE LOGIN = ${response.statusCode}");
      log.info("SERVICE LOGIN HEADER : ${response.headers}");
      log.info("SERVICE LOGIN BODY REQ : ${response.requestOptions.data}");
      log.info("> DATA LOGIN : ${response.data}\n\n");

      if (response.statusCode == 200) {
        if (response.data["code"] == "1") {
          return compute(autentikasiModelFromJson, json.encode(response.data));
        } else {
          throw (response.data["reason"]);
        }
      } else {
        log.warning("FAILED RETERIVED DATA LOGIN");
      }
    } on DioError catch (e) {
      log.warning("ERROR SERVICE LOGIN = ${e.response.statusCode}");
    }
  }

does anyone know how to fix it? or theres something i missed.
need ur help for my project.

thanks

**Comment by Ruslanbek0809** [comment]
I see your `body` map is not array. Instead of `data: body`, use `formData.fromMap()` property like this `data: formData.fromMap(body)`

**Comment by mhmmdaminn** [comment]
> As long as your `body` map doesn't contain an array, you can use `FormData.fromMap()` property like this in your `data` property: `data: FormData.fromMap(body)` instead of your `data: body`.

it still doesn't work :( still error StatusCode.

i've been debug this code login for mobile and web.
for mobile its quite well but with web i found an error body null. with the same code for mobile it works

![Screenshot 2022-01-05 135018](https://user-images.githubusercontent.com/97008895/148173071-63b75636-3e9d-460c-9af4-6f02efd3b49d.png)

**Comment by Ruslanbek0809** [comment]
Bro It should work. It is something about your code. Also I don't have much experience with flutter web. Sorry:(
