### ISSUE TITLE
How do I add a type to multipart request field?

### ISSUE THREAD

**Issue by szymonmazanik** [cfug/dio#1370]
I have a backend endpoint that requires having `;type=application/json` at the end of the field's content. Otherwise, it throws 415 error. 
Here is working curl: 
`curl --location --request POST 'https://example.com' --form 'account="{\"student\":null,}";type=application/json'`

From what I discovered we can only pass the form data as a Map, without any additional arguments.
Is it possible to achieve the same thing as in curl example with this package?

**Comment by kuhnroyal** [comment]
Not that I know of.
