### ISSUE TITLE
Rate limit for requests using QueuedInterceptorsWrapper

### ISSUE THREAD

**Issue by WieFel** [cfug/dio#1418]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter                         |      |
| Platform Version               | 2.8.1                              |      |
| Dio Version                    | 4.0.4                                 |      |
| Android Studio / Xcode Version | Android Studio Bumblebee 2021.1.1             |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | -            |      |
| Demo project link              | - |      |

### Issue Description and Steps

I am trying to implement request rate limits globally for my app within dio.
As far as I understood, `QueuedInterceptor` queues requests automatically and lets only one request at a time go through.

What I want to additionally achieve is to send max 10 requests/second to the server. But I can't find a way to do that properly.
My (simplified) code looks like this:
```dart
class API {
  late Dio _dio;

  /// Stores the currently active requests that have not been responded yet.
  int _activeRequestCount = 0;

  /// Limit of requests that can be sent per
  static const int _requestLimit = 10;

  API(String baseUrl) {
    _dio = Dio(BaseOptions(baseUrl: baseUrl));

  Timer.periodic(const Duration(seconds: 1), (timer) {
      // reset request counter every second
      _activeRequestCount = 0;
      print("RESET 0");
    });

  // interceptor for rate limiting
  _dio.interceptors.add(QueuedInterceptorsWrapper(
    onRequest: (options, handler) async {
      // before request is sent
      await Future.doWhile(() => _activeRequestCount >= _requestLimit);  // THIS LINE BLOCKS APP COMPLETELY
      _activeRequestCount++;
      print("request $_activeRequestCount");

      return handler.next(options);
    },
    onResponse: (response, handler) {
      // when response is received
      _activeRequestCount--;
      print("response $_activeRequestCount");

      return handler.next(response);
    },
  ));
  }

  // get(), post() and other functions provided by API using _dio instance
}
```

As `QueuedInterceptor` only lets go through one request/response (I suppose) at a time, actively waiting in onRequest using `await Future.doWhile(() => _activeRequestCount >= _requestLimit);` (or `while(...);`) blocks the whole interceptor and therefore the app.

Is there any better way to limit requests to a certain value per second using dio?

**Comment by spauldhaliwal** [comment]
@WieFel  @AlexV525 Was this solved? It was marked as completed last month, yet there's no discussion and I can't tell if this was added a feature or not.

**Comment by WieFel** [comment]
@spauldhaliwal I found my own way to solve it. I can share the approach here if you want.

**Comment by spauldhaliwal** [comment]
@WieFel any update on this?

**Comment by WieFel** [comment]
So my approach was like this:
```dart
/// Interceptor for limiting requests sent at once to at most the given number.
/// If the limit is reached, requests are queued until some responses get in
/// and slots are available.
class RequestLimitInterceptor extends Interceptor {
  /// Limit of requests that can be sent per second
  static const int _requestLimit = 10;

  Queue _requestQueue = Queue<_QueuedRequest>();
  int _requestCount = 0;

  bool get _limitReached => _requestCount >= _requestLimit;

  RequestLimitInterceptor() {
    Timer.periodic(const Duration(seconds: 1), (timer) => _processQueue());
  }

  @override
  void onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {
    if (!_limitReached) {
      _requestCount++;

      // send request normally
      super.onRequest(options, handler);
    } else {
      // add to queue to be processed on next free slot
      _requestQueue.add(_QueuedRequest(options, handler));
    }
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    _requestCount--;
    super.onResponse(response, handler);
  }

  @override
  void onError(DioError err, ErrorInterceptorHandler handler) {
    _requestCount--;
    super.onError(err, handler);
  }

  void _processQueue() {
    var elementsToProcess =
        min(_requestQueue.length, _requestLimit - _requestCount);

    for (int i = 0; i < elementsToProcess; i++) {
      _processNextRequestInQueue();
    }
  }

  void _processNextRequestInQueue() {
    if (_requestQueue.isNotEmpty) {
      final next = _requestQueue.removeFirst();
      onRequest(next.data, next.handler);
    }
  }
}

class _QueuedRequest {
  _QueuedRequest(this.data, this.handler);

  RequestOptions data;
  RequestInterceptorHandler handler;
}
```

and then I add the interceptor `dio.interceptors.add(RequestLimitInterceptor())`

It might not be perfect, but it solved my problem.

**Comment by AlexV525** [comment]
You'll need a mutex rather than the queued interceptor. Searching for how to implement a mutex might be helpful.
