### ISSUE TITLE
No host specified in URI

### ISSUE THREAD

**Issue by jjsebastianfuertes** [cfug/dio#1428]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | android                      |      |
| Platform Version               | 11.0                            |      |
| Dio Version                    | 4.0.4                                  |      |
| Android Studio  | Android Studio 11.0.11+0-b60-7590822 x86_64             |      |
| Repro rate                     |  2% |      |
| Repro with our demo prj        |  no            |      |

### Issue Description and Steps

I get this error [DioErrorType.other]: Invalid argument(s): No host specified in URI sometimes on random occasions. can't replicate but once it happens I have to completely delete the application and re-install it to make it work again.

While throw this error none request type works;

**Comment by jgoyvaerts** [comment]
Without seeing any code how you're using dio there isn't much we can do about this.

Is there a minimal repro case you can build or can you show how you are setting up and using dio in your application?

**Comment by y0unghe** [comment]
It happened to me today. I am using the IP address as the host. It worked at the beginning, but suddenly it won't work and report the error: `Unhandled Exception: DioError [DioErrorType.other]: Invalid argument(s): No host specified in URI http:/192.168.1.3:3000/api/v1/users/`

Delete the app and run it again on the device, it still won't work.
