### ISSUE TITLE
How to get DNS&ssl time

### ISSUE THREAD

**Issue by 390057892** [cfug/dio#1433]
How to get DNS&ssl time

**Comment by leeyisoft** [comment]
如是实现“让调用者接收到网络请求事件，比如，开始解析 DNS 事件，解析 DNS 结束的事件等等”

**Comment by MarsLeo** [comment]
> 如何实现“让调用者接收到网络请求事件，比如，开始解析 DNS 事件，解析 DNS 结束的事件等等”
> 
> How to implement "let the caller receive the network request event, e.g., the DNS resolution event starts, the DNS resolution event ends, etc."

同求方法
