### ISSUE TITLE
Duplicate requests / Question

### ISSUE THREAD

**Issue by YDA93** [cfug/dio#1442]
Since I migrated from http to Dio, I noticed receiving duplicate requests.

The question:

Does Dio hold the request in queue even when it fails?

Let's say I did http request and there was a socket exception does Dio automatically retry the request or will remove it from queue?

Please for your kind reply,

**Comment by luishwu** [comment]
Hello, 

Any news on this. I am having same problem, some request are duplicated several times. See below image from Devtools:

![image](https://user-images.githubusercontent.com/2806677/175073777-3f6d8b8b-31dd-4d57-ac73-678cf0662f66.png)

You can check that request are in the same exact time.

**Comment by Fethi-Hamdani** [comment]
@AlexV525  any updates on this?
