### ISSUE TITLE
[Exceptions] Invalid media type: expected no more input: charset=gbk,utf8

### ISSUE THREAD

**Issue by zhangzy7** [cfug/dio#1443]
### New Issue Checklist

- [√ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |windows                          |      |
| Platform Version               | win10                               |      |
| Dio Version                    | 4.0.4                                 |      |
| VSCode | VSCode  1.65.1              |      |
| Repro rate                     |  100%   |      |
| Repro with our demo prj        |  yes           |      |
| Demo project link              |  |      |
----
### Issue Description and Steps

我使用 nginx-1.20.2 搭了一个简易web服务器，在向其发送请求时，报告了异常

DioError (DioError [DioErrorType.other]: Error on line 1, column 23: Invalid media type: expected no more input.
   ╷
1 │ text/html; charset=gbk,utf8
   |.....................................................^
   ╵

在nginx的配置文件中配置gbk是为了处理多编码路径的情况，dio是否支持这项功能？或者说有没有什么办法处理这种问题？

----

Dio thorw exception when I request to a nginx-1.20.2 server. It set charset=gbk,utf8 to resolve some problem in multi-charset.
 
DioError (DioError [DioErrorType.other]: Error on line 1, column 23: Invalid media type: expected no more input.
   ╷
1 │ text/html; charset=gbk,utf8
   |....................................................^
   ╵

May Dio support this feature, or something else I can resolve it ?

**Comment by amondnet** [comment]
@zhangzy7 

This seems to be caused by an invalid media type declaration: `text/html; charset=gbk,utf8`

According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.1) the grammar for media types the type/subtype pair followed by zero or more "; parameter=value" pairs.

This is where the error occurred.
https://github.com/flutterchina/dio/blob/6d04ec95d951bdecd19a2939d94de217d2d1ff7d/dio/lib/src/transformer.dart#L172

https://pub.dev/documentation/http_parser/latest/http_parser/MediaType/MediaType.parse.html

> Parses a media type.
> 
> This will throw a FormatError if the media type is invalid. 



```dart
MediaType.parse('text/html; charset=gbk,utf8');
```


```
Error on line 1, column 23: Invalid media type: expected no more input.
  ╷
1 │ text/html; charset=gbk,utf8
  │                       ^
  ╵
```

```dart
import 'package:http_parser/http_parser.dart';
import 'package:test/test.dart';

void main() {
  group('A group of tests', () {
    test('charset=gbk,utf8', () {
      final type = MediaType.parse('text/html; charset=gbk,utf8');
      expect(type.parameters['charset'], 'utf8');
    });

    test('charset=utf8', () {
      final type = MediaType.parse('text/html; charset=utf8');
      expect(type.parameters['charset'], 'utf8');
    });

    test('charset=gbk', () {
      final type = MediaType.parse('text/html; charset=gbk');
      expect(type.parameters['charset'], 'gbk');
    });
    test('two parameters', () {
      final type = MediaType.parse('text/html; charset=gbk;foo=bar');
      expect(type.parameters['charset'], 'gbk');
      expect(type.parameters['foo'], 'bar');
    });
  });
}
```
