### ISSUE TITLE
Multipart: can't upload JSON with image

### ISSUE THREAD

**Issue by cdprete** [cfug/dio#1444]
Hi.
I'm trying to execute a POST and a PUT request where I do upload a JSON with, as well, an image file.

Version of the library: 4.0.4
App built for: Windows
Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale it-CH)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

Code
```dart
final String urlSuffix, httpMethod;
      if (id == null) {
        urlSuffix = contactsUrl;
        httpMethod = 'POST';
      } else {
        urlSuffix = singleContactUrl.replaceFirst(':id', id);
        httpMethod = 'PUT';
      }
      final data = FormData.fromMap({
        'data': MultipartFile.fromString(
          await compute(jsonEncode, contact),
          contentType: Headers.jsonMimeType,
        )
      })
      if (contact.image != null) {
        data.files.add(MapEntry(
          'image',
          MultipartFile.fromBytes(contact.image!.toList()),
        ));
      }

      final response = await client.request(
        '$baseUrl/$urlSuffix',
        data: data,
        options: Options(method: httpMethod),
      );
```

The image payload is simply ignored while, if I pass the JSON as field (instead of file), I get the same as in https://stackoverflow.com/questions/68799973/cannot-send-dio-post-request-with-multiple-form-data-body-json-and-image-with-fl 
(which is expected given the API).

**Comment by SimonWang9610** [comment]
Try to pass the `filename` parameter when creating a `MultiartFile`., the `filename` should indicate the file extension, e.g., `filename.png`. By indicating the file extension, the server should be able to decode data correctly.

If not provided `filename`, the payload of files in a form data would be:
`content-disposition: form-data; name="field"<...>`
By giving a `filename.ext`, it would be:
`content-disposition: form-data; name="field"; filename:"filename.ext" <...>`

**Comment by cdprete** [comment]
Hi.
After almost a year, it's hard to me to provide any feedback on this, but passing the an extension looks wrong to me.
In the end, even if the bytes are representing an image, what I wanted to upload there was a byte array (application/octet-stream).
Moreover, uploading the image alone works even without the extension (that's how I "solved" it at the end), which would make all this inconsistent.

**Comment by SimonWang9610** [comment]
> Hi. After almost a year, it's hard to me to provide any feedback on this, but passing the an extension looks wrong to me. In the end, even if the bytes are representing an image, what I wanted to upload there was a byte array (application/octet-stream). Moreover, uploading the image alone works even without the extension (that's how I "solved" it at the end), which would make all this inconsistent.

That is so weird.
Could you provide the payload (captured from the browser network console/dart network tool) of the request when sending JSON fields and image files together? 
The payload format of form data should be like as:
```
----dio-boundary-1865654818
content-disposition: form-data; name="test"

dio
----dio-boundary-1865654818
content-disposition: form-data; name="single"; filename="demo.jpeg"
content-type: image/jpeg

(file data)
----dio-boundary-1865654818--
```

Personally, it may be because the server side just ignores the binary data since it has no idea how to decode the binary data into the original file. Therefore, by investigating what payload is sent may help us solve this problem.

**Comment by cdprete** [comment]
Hi.
I don't have such a method anymore in the codebase. As I said, I then opted for the solution of splitting the JSON payload from the image itself, so I cannot reproduce this anymore.
If you want, you can find the full project at https://github.com/cdprete/phone-book and the Docker images are already available at https://hub.docker.com/u/cdprete (so that maybe you can spin up just the UI).

**Comment by cdprete** [comment]
By the way, now that I'm thinking back at this, I've just remember the initial idea was to be able to upload the image as octet-stream together with the JSON.
Basically, to reproduce the same as described in the first example in https://swagger.io/docs/specification/describing-request-body/multipart-requests/

I also remember trying with a fixed filename with a fixed extension (PNG to be precise), but keeping the application/octet-stream as content type, with no luck.
