### ISSUE TITLE
'DioError [DioErrorType.connectTimeout]: Connecting timed out [20000ms]'

### ISSUE THREAD

**Issue by OHeroJ** [cfug/dio#1447]
报错量非常多，咋整？

CONNECT_TIMEOUT too many times。

used package Dio 4.0.4, but still the same.

**Comment by OHeroJ** [comment]
CONNECT_TIMEOUT too many times

**Comment by OHeroJ** [comment]
https://github.com/flutterchina/dio/issues/975

**Comment by OHeroJ** [comment]
如果一开始请求未成功，那么后面及时你网再好，也会报超时

**Comment by balaji101010** [comment]
any updates?

**Comment by heinzan** [comment]
Same here sometime this timeout error appear internet is good why?

**Comment by toppert** [comment]
Same here sometime this timeout error appear internet is good too pls help

**Comment by balaji101010** [comment]
I temporarily used this library to fix my api issues https://pub.dev/packages/retry

**Comment by a83988029** [comment]
一直有这个问题
