### ISSUE TITLE
flutter web console show Bad state: Future already completed

### ISSUE THREAD

**Issue by alreadytaken1990** [cfug/dio#1454]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | web                         |      |
| Platform Version               | -                             |      |
| Dio Version                    | 4.0.5                                |      |
| Android Studio / Xcode Version | - (vscode&pkged)             |      |
| Repro rate                     | all the time (100%)   |      |
| Repro with our demo prj        | -           |      |
| Demo project link              | - |      |

### Issue Description and Steps

show error in broswer console:  Bad state: Future already completed
4.0.4 doesnt have this error

**Comment by FrankNanninga** [comment]
I can confirm - I am facing the same issue in my Interceptor. Removing the timeout options resolves the issue, though this is not a permanent fix ...

**Comment by figbin** [comment]
Same issue found~

**Comment by viralkachhadiya** [comment]
I am also getting same issue 

Error: Bad state: Future already completed
    at Object.throw_ [as throw] (http://localhost:57202/dart_sdk.js:5067:11)
    at _AsyncCompleter.new.completeError (http://localhost:57202/dart_sdk.js:35195:51)
    at http://localhost:57202/packages/dio/src/interceptors/log.dart.lib.js:651:25
    at _RootZone.runUnary (http://localhost:57202/dart_sdk.js:40441:59)
    at _FutureListener.then.handleValue (http://localhost:57202/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:57202/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:57202/dart_sdk.js:35969:17)
    at _Future.new.[_complete] (http://localhost:57202/dart_sdk.js:35809:25)
    at http://localhost:57202/dart_sdk.js:34915:30
    at internalCallback (http://localhost:57202/dart_sdk.js:26619:11)

**Comment by RootSoft** [comment]
Can confirm as well.
Downgrading to 4.0.4 or removing the timeout options resolves the issue.

**Comment by augb** [comment]
Could it be that this is the culprit:
```dart
... elided ...
request = await reqFuture;
if (options.connectTimeout > 0) {
  request = await reqFuture
      .timeout(Duration(milliseconds: options.connectTimeout));
} else {
  request = await reqFuture;
... elided ...
```
?

(See [line 47](https://github.com/flutterchina/dio/blob/ac78e6151e1736f945cb9b215bbcfac230e19cf1/dio/lib/src/adapters/io_adapter.dart#L47)).

It appears the call on line 47 is not needed since both conditions of the if do the call. Perhaps this is a duplicate?

**Comment by guillaume-camanes-wiztivi** [comment]
Same issue in my project.
As mentioned by @RootSoft, downgrading to 4.0.4 fixed it.

**Comment by llfbandit** [comment]
#1470 fixes this issue

**Comment by SystemTce** [comment]
昨晚发版，这个问题我一直没关注到是BrowserHttpClientAdapter的错误，排查了很久，五一第一天emo了，啊哈哈

**Comment by andrew2558** [comment]
I have the same problem
dio: ^4.0.6

**Comment by typenoob** [comment]
> I can confirm - I am facing the same issue in my Interceptor. Removing the timeout options resolves the issue, though this is not a permanent fix ...

same

**Comment by lukey78** [comment]
Can confirm, too. Is in there since 4.0.5, 4.0.4 seems to be ok.
