### ISSUE TITLE
Hi， guys! i am facing the same problem. what should i do ?

### ISSUE THREAD

**Issue by boziyoung** [cfug/dio#1461]
Hi， guys! i am facing the same problem. what should i do ?

my back : django , i have set up "django-cors-headers";
i have set up chrome "--disable-web-security" and started it;
but i print it , it  still ddin't have "set-cookie".
it is 
`allow: POST
allow:  OPTIONS
content-length: 50
content-type: application/json
date: Mon
date:  11 Apr 2022 09:00:05 GMT
referrer-policy: same-origin
server: WSGIServer/0.2 CPython/3.10.0
vary: Accept
vary:  Cookie
vary:  Origin
x-content-type-options: nosniff
x-frame-options: DENY`

but  i can see "set-cookie" in the chrome dev tab.
![image](https://user-images.githubusercontent.com/50167927/162718248-18f80909-adf8-473c-8c3b-61ed48cea97a.png)

_Originally posted by @boziyoung in https://github.com/flutterchina/dio/issues/1027#issuecomment-1094803474_

**Comment by charcoast** [comment]
Read my [comment](https://github.com/flutterchina/dio/issues/1027#issuecomment-1104611957) on #1027, it might help.

**Comment by makoru-hikage** [comment]
@boziyoung , please check your browser settings, here's a guide: https://www.cookieyes.com/blog/how-to-check-cookies-on-your-website-manually

Chrome DevTools acts like a Javascript frontend app, it cannot read httpOnly Cookies; so expect nothing in its cookie viewer in the "Application Tab".
