### ISSUE TITLE
flutter web，请求头设置了Date，Chrome中发送时捉包发现没有Date，为什么？

### ISSUE THREAD

**Issue by wadychou** [cfug/dio#1462]
### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter web， chrome                          |      |
| Platform Version               | Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm                             |      |
| Dio Version                    | dio: ^4.0.6                               |      |
| Android Studio / Xcode Version |               |      |
| Repro rate                     |     |      |
| Repro with our demo prj        |            |      |
| Demo project link              |   |      |

### Issue Description and Steps

    var options = BaseOptions(
      baseUrl: 'http://$bucketName.$endPoint',
      connectTimeout: 5000,
      receiveTimeout: 100000,
      headers: {
        HttpHeaders.hostHeader : '$bucketName.$endPoint', 
        HttpHeaders.dateHeader : gmtDate, // 请求头设置了Date，Chrome中发送时捉包发现没有Date，为什么？
        HttpHeaders.contentTypeHeader : 'application/json',,
      },
    );
    var dio = Dio(options);
    var response = await dio.delete('/$objectName');
    

// 请求头设置了Date，Chrome中发送时捉包发现没有Date，为什么？
捉包请求体如下：

DELETE /test/1234/test.png HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Host: xxx.xxxxxxxxx.aliyuncs.com
Origin: http://localhost:54376
Referer: http://localhost:54376/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
content-type: application/json

**Comment by keluokeda** [comment]
有同样的问题

**Comment by laxian** [comment]
dio: ^4.0.6
同样的问题，在web上出现，其他平台没有。
这么久了，都没人回复，有点儿不敢用了。

**Comment by laxian** [comment]
我换成了 http 库，也有同样的问题，所以，应该是flutter或者chrome的问题。

**Comment by laxian** [comment]
我把框架换成了http，问题依然存在。
经过分析，这个问题是因为浏览器限制。浏览器禁止手动设置一些敏感header，包括'Date'、'Connection'
