### ISSUE TITLE
WIFI switch, No address associated with hostname

### ISSUE THREAD

**Issue by MrLaibin** [cfug/dio#1465]
### New Issue Checklist

- [ YES ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter  / android                          |      |
| Platform Version               |   2.10.4 / 11.0                              |      |
| Dio Version                    |  4.0.6 / 1.0.17                                  |      |
| Android Studio / Xcode Version |  Android Studio 3.3.2            |      |
| Repro rate                     |  all the time (100%)  |      |
| Repro with our demo prj        |  ``` Dio _dio = new Dio();    _dio.fetch(RequestOptions(path: "http://baidu.com/")); ```           |      |
### Issue Description and Steps
WIFI A: the network is normal
WIFI B: LAN only
If I switch from A to B, then switch from B back to A. request will receive an error.
```
Unhandled Exception: DioError [DioErrorType.other]: SocketException: Failed host lookup: 'baidu.com' (OS Error: No address associated with hostname, errno = 7)
```
Browser The network is normal, kill the process and restart the App The network is normal

**Comment by AliYar-Khan** [comment]
Same happening with me .... I am running app in debug mode and it is giving me error
