### ISSUE TITLE
how to POST json data and Image file at the same time fromdata 

### ISSUE THREAD

**Issue by sumersm7** [cfug/dio#1468]
### New Issue Checklist

- [ yes] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  |  flutter                        |      |
| Platform Version               |                             |      |
| Dio Version                    |  4.0.6                                  |      |
| Repro rate                     | all the time (100%) |      |

### Issue Description and Steps

i want to POST json data and Image file at the same time. but iam receiving data in falt way.

```
@JsonSerializable()
class SomeClassA{
  String title,value;
  SomeClass({this.title,this.value});

  factory SomeClassA.fromJson(Map<String, dynamic> json) => _$SomeClassAFromJson(json);
  Map<String, dynamic> toJson() => _$SomeClassAToJson(this);
}


@JsonSerializable()
class SomeClassB{
  List<SomeClassA>? categoryLS;
  SomeClassB({this.categoryLS});

  factory SomeClassB.fromJson(Map<String, dynamic> json) => _$SomeClassBFromJson(json);
  Map<String, dynamic> toJson() => _$SSomeClassBToJson(this);
}
```

```
//after SomeClassBObj.toJson();
{
  categoryLS:
    [
      {
        title: Food,
        value: Food,
      },     
    ],
}
```
```
     //create formdata
      var formData =  FormData.fromMap(SomeClassBObj.toJson());
      formData.files.addAll([
        MapEntry('files', MultipartFile.fromFileSync('./example/upload.txt', filename: 'upload.txt'),),
        MapEntry('files', MultipartFile.fromFileSync('./example/upload.txt', filename: 'upload.txt'),),
      ]);
   //post form data
    await dio.post(reqUrl, data: formData, options: Options(headers: headers));
```

//output on server , req.body (what i get)

![image](https://user-images.githubusercontent.com/82924076/164695252-db89ebbe-9d41-4c02-bff0-7194743f5c19.png)

on server req.body(what i want)
![image](https://user-images.githubusercontent.com/82924076/164699891-30e2c48c-6aea-4f3c-9029-ac9932dc8681.png)

**Comment by ankitparmar007** [comment]
**Here is how I am sending image and json data**
```
 FormData formData = FormData.fromMap(
      {
        "email": "abc@gmail.com,
        "folderName": "name",
        "imageFile": await MultipartFile.fromFile(imagePath),
        "imageName": "imageName",
      },
    );
    try {
      var response = await dio.post(
        url + "/createImage/",
        data: formData,
      );
      return response.data;
    } on DioError catch (e) {
      return await handleErrors(e);
    }
```
