### ISSUE TITLE
Future already completed

### ISSUE THREAD

**Issue by jargalbat** [cfug/dio#1480]
When calling requests, the error has been thrown randomly.

Error: Bad state: Future already completed
    at Object.throw_ [as throw] (http://localhost:1234/dart_sdk.js:5067:11)
    at _AsyncCompleter.new.completeError (http://localhost:1234/dart_sdk.js:35195:51)
    at http://localhost:1234/packages/dio/src/interceptors/log.dart.lib.js:651:25
    at _RootZone.runUnary (http://localhost:1234/dart_sdk.js:40441:59)
    at _FutureListener.then.handleValue (http://localhost:1234/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:1234/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:1234/dart_sdk.js:35969:17)
    at _Future.new.[_complete] (http://localhost:1234/dart_sdk.js:35809:25)
    at http://localhost:1234/dart_sdk.js:34915:30
    at internalCallback (http://localhost:1234/dart_sdk.js:26619:11)

```
_dio.interceptors.add(CustomInterceptors());

// ...

class CustomInterceptors extends Interceptor {
  @override
  void onError(DioError err, ErrorInterceptorHandler handler) async {
    if (err.response != null) {
      if (err.response!.statusCode == 401) {
        // ...
        handler.resolve(response);
      } else {
        handler.next(err);
      }
    }

    return super.onError(err, handler);
  }
}
```

### Issue Info

| Info                           | Value                                                 |  
| ------------------------------ | ----------------------------------------------------- | 
| Platform Name                  | Chrome                          |  
| Dio Version                    | 4.0.6                                   |  
| Android Studio Version | 2021.1.1 Patch 2             | 

### Issue Description and Steps

Tried using flutter config --no-analytics. It didn't work.

**Comment by YouchanChung** [comment]
same issue..

**Comment by Dkrinker** [comment]
Same issue

**Comment by ZhZhZhen** [comment]
我在web项目中，也会输出这个错误

**Comment by marcelomdea** [comment]
Same issue...

**Comment by mdeandrea-mrmilu** [comment]
Related to #1497 and PR #1496

**Comment by loidy** [comment]
Still happening in 4.0.6

**Comment by angelomedeiros** [comment]
Same issue.

**Comment by Amr-SymTerra** [comment]
Same issue

**Comment by vrsct** [comment]
Same issue

**Comment by klepon** [comment]
same issue

**Comment by TryImpossible** [comment]
same issue

**Comment by hamzakhurshid12** [comment]
Same issue

**Comment by kenNg1** [comment]
Same issue

**Comment by tranducthang1505** [comment]
Same issue

**Comment by nicolaspernoud** [comment]
Same issue

**Comment by SumanPoudel0699** [comment]
https://stackoverflow.com/a/73824643/19475845

I have written one solution in StackOverflow this helps me to get read of ` Error: Bad state: Future already completed` error may help you also

**Comment by ikallali** [comment]
+1

**Comment by CrazyboyQCD** [comment]
+1

**Comment by davidmigloz** [comment]
Similar issues:
- https://github.com/flutterchina/dio/issues/1454
- https://github.com/flutterchina/dio/issues/1497
- https://github.com/flutterchina/dio/issues/1536

Open PRs:
- https://github.com/flutterchina/dio/pull/1470
- https://github.com/flutterchina/dio/pull/1496
- https://github.com/flutterchina/dio/pull/1513
- https://github.com/flutterchina/dio/pull/1550
- https://github.com/flutterchina/dio/pull/1565

**Comment by Wbqqqq** [comment]
+1

**Comment by HasanAlqaisi** [comment]
+1

**Comment by ajikmat** [comment]
+1

**Comment by metafounder** [comment]
+1

**Comment by adbelemvy** [comment]
same issue here

**Comment by botaditya** [comment]
Same issue being faced by me

**Comment by marjandn** [comment]
I have this issue as well

**Comment by mdeandrea-mrmilu** [comment]
@AlexV525 why this issue is closed? Someone fix this bug?

**Comment by AlexV525** [comment]
Yes, in #1550.

**Comment by MajedDH** [comment]
I had the same issue.

I really spent hours to figure out that the `handler` should be called once. my code was wrongly calling `handler.resolve` and then `handler.next`. 

I corrected the code to call only one of them (`if else`) ,  it worked like a charm.

**Comment by phamquoctrongnta** [comment]
For anyone come late
I just removed `super.onError(err, handler);` on `onError` method.

**Comment by kuhnroyal** [comment]
https://github.com/cfug/dio/pull/2130 improves the error message for this case.
