### ISSUE TITLE
io_adapter close() method logic error?

### ISSUE THREAD

**Issue by tobeen** [cfug/dio#1492]
dio 4.0.6
in class io_adapter.dart
@override
  void close({bool force = false}) {
    _closed = _closed;
    _defaultHttpClient?.close(force: force);
  }

is that _closed = _closed error?
should be:
@override
  void close({bool force = false}) {
    _closed = true;
    _defaultHttpClient?.close(force: force);
  }
??
please check.

**Comment by AlexV525** [comment]
Hi @tobeen. We've made our hardfork repo public and published a new version of `dio`, named `diox`.
The new package contains the PR of the fix.
Please refer to https://pub.dev/packages/diox/versions/5.0.0-dev.1 to use the fork.
You can also see why we're working for a hardfork at https://github.com/cfug/diox/issues/29 and https://github.com/flutterchina/dio/issues/1607.
