### ISSUE TITLE
DioError [DioErrorType.other]: HttpException: Connection closed while receiving data

### ISSUE THREAD

**Issue by Shimingli** [cfug/dio#1498]
DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
DioMixin.post (package:dio/src/dio_mixin.dart:97:12)
 DioNetWorkSingleton.post (package:common_net/base/dio_network_singleton.dart:58:17)

![image](https://user-images.githubusercontent.com/20720544/173309718-3963b048-a7d1-4327-b7a3-e2177c2a1439.png)

**Comment by taobingzhi** [comment]
解决了吗？我也碰到了这个问题，设置了keep-alive 也没用
