### ISSUE TITLE
http headers on requests forced to lower case

### ISSUE THREAD

**Issue by Toavina23** [cfug/dio#1506]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter                        |      |
| Platform Version               | e.g.  3.0.21                               |      |
| Dio Version                    | e.g.  4.0.6                                 |      |

### Issue Description and Steps

I have to send request to a server where the headers are case sensitive. I am using dio and remarked that all my headers are turned to lower case when I am sending the request to the server. As a result I am always getting the 400 status code. Any solution for this please ?

**Comment by shkvoretz** [comment]
@Toavina23 header field names are case-insensitive and should be treated as such by the server [https://www.rfc-editor.org/rfc/rfc9110.html#name-header-fields](https://www.rfc-editor.org/rfc/rfc9110.html#name-header-fields)
