### ISSUE TITLE
用原生请求好使,用dios请求就会被登录拦截

### ISSUE THREAD

**Issue by ZJGoal** [cfug/dio#1507]
![image](https://user-images.githubusercontent.com/23555850/174578767-13ab79ca-f333-4431-997b-647b34b2e000.png)
这个请求是好使的 但是我用dios就报错
![image](https://user-images.githubusercontent.com/23555850/174579020-91598152-a881-4b45-afd8-134fae2f1c05.png)
是什么问题呢？

**Comment by ZhZhZhen** [comment]
好像都是和跨域，设置cookie相关的问题，到现在也没有人解决。有人尝试这样设置。
```
dio = Dio(options);
    BrowserHttpClientAdapter adapter = BrowserHttpClientAdapter();
    adapter.withCredentials = true;
    dio.httpClientAdapter = adapter;
```
但我没成功
