### ISSUE TITLE
Interceptor doesn't work for DioError.type = cancel

### ISSUE THREAD

**Issue by sysint64** [cfug/dio#1512]
Interceptor have no effect on dio error when you cancel request.

**version**: 4.0.6

**Example**

```
class ErrorInterceptor extends Interceptor {
  @override
  void onError(DioError err, ErrorInterceptorHandler handler) {
    if (err.type == DioErrorType.cancel) {
      handler.next(CancelledException());
    } else {
      handler.next(err);
    }
  }
}
```

When register interceptor and try to catch an error it always has a type = `DioError` instead of `CancelledException` whenever request is cancelled.

**Comment by AlexV525** [comment]
cc @ueman @kuhnroyal Got any opinion about handling cancellation in interceptors? I do a test with the snippet and it's indeed not handled the cancellation.

![image](https://user-images.githubusercontent.com/15884415/207885602-a207d65c-35b5-4586-9569-fd3897ed7d5e.png)

**Comment by josh-burton** [comment]
Can this be re-opened? It seems it's still an issue.

I'm unable to catch a DioError of type cancel in an interceptor.
