### ISSUE TITLE
can't request download with DioMixin,Isn't it right to use a posture?

### ISSUE THREAD

**Issue by noProblemPromise** [cfug/dio#1514]
can't download with DioMixin, is this api unusable?

![1656557817694](https://user-images.githubusercontent.com/44568922/176583222-e172240e-e541-441c-a869-0ceeb31267cf.jpg)
![WX20220630-105550](https://user-images.githubusercontent.com/44568922/176583462-3a6c0a3c-2086-4ac8-b1ef-8c3794583214.png)
![WX20220630-105612](https://user-images.githubusercontent.com/44568922/176583470-525bc91b-956e-4edf-858f-44aa35c0488d.png)

**Comment by Nekketsu-GIT** [comment]
Have this same error on web. It seems to work on mobile but throw an FileSystemException as it can't create file...

**Comment by AlexV525** [comment]
`download` is only available in `DioForNative`.
