### ISSUE TITLE
HttpException: Connection reset by peer

### ISSUE THREAD

**Issue by iOS-Kel** [cfug/dio#1515]
dio send post error, how to resolve this problem

**Comment by Geeph** [comment]
I have the same issue

**Comment by Geeph** [comment]
> dio send post error, how to resolve this problem

hi bro, would you let me know if you fix it? thx.

**Comment by nguyenthanhphap1413** [comment]
i have same problem

**Comment by ali-taha-albaap** [comment]
I have the same issue

**Comment by ddswez** [comment]
> 

hi ali-taha-albaap, would you let me know if you fix it? thx.

**Comment by ddswez** [comment]
> @ali-taha-albaap  hi would you let me know if you fix it?

**Comment by ddswez** [comment]
> i have same problem

@nguyenthanhphap1413 hello, would you let me know if you fix it? thx.

**Comment by ddswez** [comment]
@Geeph 找到原因了吗，我同样的host在原生是可以了，用dio在flutter请求报错 SocketException: Connection reset by peer, errno 104

**Comment by tao111222333444** [comment]
@AlexV525 @ddswez  Has the problem been fixed? how to fix this problem

**Comment by li-xiaojun** [comment]
相同的问题，同一个接口用原生APP请求就没问题，用postman也没问题，但是Flutter就报错HttpException: Connection reset by peer，无论是跑在模拟器还是真机都报错

**Comment by jiang-jt** [comment]
> 相同的问题，同一个接口用原生APP请求就没问题，用postman也没问题，但是Flutter就报错HttpException: Connection reset by peer，无论是跑在模拟器还是真机都报错
@li-xiaojun 一样的问题，解决了吗

**Comment by yoni1988** [comment]
@junixapp 请问这个怎么解决？
