### ISSUE TITLE
Dio doesn't send request body when using GET method

### ISSUE THREAD

**Issue by xmine64** [cfug/dio#1529]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

I know it's not standard to send body when using GET method, but still it's possible to do that, but it's not working when using Dio. 

I used a simple http server that prints request body, to confirm that it works with dart:io:

<details>
   <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/21140798/180962738-6a905fab-d43a-450a-99ab-dc8442d592a0.png)

</details>

**Comment by bit-void** [comment]
I'd like this feature as well, for example elasticsearch prefers a body in their GET requests: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-request-body

**Comment by AlexV525** [comment]
Hi everyone! We've made our hardfork repo public and published a new version of `dio`, named `diox`.
The new package contains the PR of the fix.
Please refer to https://pub.dev/packages/diox/versions/5.0.0-dev.1 to use the fork.
You can also see why we're working for a hardfork at https://github.com/cfug/diox/issues/29 and https://github.com/flutterchina/dio/issues/1607.
