### ISSUE TITLE
Mismatching `Content-Type` header value with Dio options' `ResponseType`.

### ISSUE THREAD

**Issue by bambinoua** [cfug/dio#1533]
It seems there is a bug in `transformResponse` method of class `DefaultTransformer` (or somewhere deeper).

I use external API which returns token as **JSON String**, i.e. the result is:
```dart
""ZXlKaGJHY2lPa...""
```
And because `dio` consider this response as `ResponseType.plain` instead of `ResponseType.json` (but it is a JSON) it does not decode those `JSON String` to regular `String`.

![dio_bug](https://user-images.githubusercontent.com/45417992/182114247-f3087433-32fa-4ed2-8bb9-c263312f0fbc.png)

As you may notice on image the `Content-Type` of HTTP response is `application/json` but internal `options.responseType` is not `ResponseType.json` which is requried for calling `json.decode` method.

Dio version 4.0.6
Flutter version: 3.0.5

**Comment by jhionan** [comment]
And please stop forcing the lower case on headers!
