### ISSUE TITLE
Random error while uploading videos

### ISSUE THREAD

**Issue by Manasmd** [cfug/dio#1535]
### New Issue Checklist

- [✓] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

[✓] Flutter (Channel unknown, 2.10.5, on Ubuntu 20.04.2 LTS 5.4.0-122-generic, locale en_GB.UTF-8)
    • Flutter version 2.10.5 at /home/donatien/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (4 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/donatien/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/donatien/Android/Sdk
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio
    • Android Studio at /home/donatien/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.68.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.46.0

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.46.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Issue Description and Steps

I am trying to upload video files to Vimeo, it works fine. But sometimes it doesn't send the Multipart file properly. The DIOERROR only happens 1/10 tries. Please see the attached screenshot:
![Screenshot from 2022-08-03 18-48-14](https://user-images.githubusercontent.com/25542876/182756302-418d5186-e468-4bcb-9d0d-cf575a31705d.png)

**Comment by adelarsq** [comment]
I am experiencing a similar problem. Still no idea how to solve.
