### ISSUE TITLE
Dio is making multiple calls to URL when using breakpoints in Flutter (Android Studio) - Interceptor verified.

### ISSUE THREAD

**Issue by ExpertKiD** [cfug/dio#1546]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                       |      |
| Platform Version               | 3.0.5-stable                            |      |
| Dio Version                    | 4.0.4                               |      |
| Android Studio / Xcode Version | Android Studio latest - Xcode latest         |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        | yes        |      |
| Demo project link              | - |      |

### Issue Description and Steps

When we use breakpoints in flutter for API request step through, the API gets called multiple times. Otherwise without using breakpoints, the API works properly.

To reproduce the issue, add a breakpoint to API call in Flutter. Then, step by step check the response,its request await and so on.

Don't let the breakpoint go away. Keep it and go step by step with step through one step at a time. Within a minute there will be 5-6 consecutive request already made by Dio. I had 35 request made in just under 2 minute.

**Comment by huangjiaxiang** [comment]
me too!!!

**Comment by venbrinoDev** [comment]
i am also experience this 

how to reproduce 
you can add prettydiointerceptor to monitor the api calls
it calls like 5 times at a time
