### ISSUE TITLE
QueuedInterceptorsWrapper - no errors when dio.fetch with bad token

### ISSUE THREAD

**Issue by maciogg** [cfug/dio#1557]
### New Issue Checklist

- [x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | Flutter                        |      |
| Platform Version               | 3.05                                |      |
| Dio Version                    | 4.0.6                                 |      |

### Issue Description and Steps

Have QueuedInterceptorsWrapper to catch error with authorization token. When repeating call with new good token, everything is OK but when new token is still bad I got no error. I need catch this error for redirect to login screen.

    dio.interceptors.add(QueuedInterceptorsWrapper(onRequest: (options, handler) {
      return handler.next(options);
    }, onResponse: (response, handler) {
      return handler.next(response); 
    }, onError: (error, handler) async {
      if (error.response?.statusCode == 401) {
        var newToken = await ApiBaseHelper.refreshToken(ref);
        var options = error.response!.requestOptions;
        options.headers["Authorization"] = 'Basic ${base64.encode(utf8.encode('$newToken:'))}';
        //repeat
        dio.fetch(options).then(
          (r) => handler.resolve(r),
          onError: (e) {.  // NO ERROR HERE
            ApiBaseHelper.returnToLogin(ref);
          },
        );
        return;
      } else {
        return handler.next(error);
      }
    }));

LogInterceptor for repeat call (with 401 error :) )

flutter: connectTimeout: 5000
flutter: sendTimeout: 0
flutter: receiveTimeout: 5000
flutter: receiveDataWhenStatusError: true
flutter: extra: {}
flutter: headers:
flutter:  Authorization: Basic cmVzdWx0LnRva2VuOg==
flutter:
flutter: *** DioError ***:
flutter: uri: https://......../api/4.0/SraOrders/?page=1&items_per_page=10
flutter: DioError [DioErrorType.response]: Http status error [401]
flutter: uri: https://......../api/4.0/SraOrders/?page=1&items_per_page=10
flutter: statusCode: 401
flutter: headers:
flutter:  connection: keep-alive
flutter:  cache-control: s-maxage=10
flutter:  date: Sat, 03 Sep 2022 18:42:18 GMT
flutter:  content-length: 39
flutter:  age: 0
flutter:  x-frame-options: SAMEORIGIN
flutter:  content-type: application/json
flutter:  v-url: /api.php?_d=4.0/SraOrders/&ajax_custom=1&page=1&items_per_page=10&page=1&items_per_page=10
flutter:  x-content-type-options: nosniff
flutter:  www-authenticate: Basic realm="User email/API key"
flutter:  server: nginx/1.12.2

**Comment by zhanght2008** [comment]
I have the same problem!

**Comment by lilaw** [comment]
same here

**Comment by maciogg** [comment]
I've implemented custom interceptor and it's work.

https://github.com/maciogg/Dio-CustomInterceptor/blob/main/custom_interceptor.dart

using:

      Dio dio = Dio();
      dio.interceptors.add(CustomInterceptor(ref: ref, isAuth: true));

**Comment by lilaw** [comment]
I got it from this issue https://github.com/flutterchina/dio/issues/1339. you need a new doi instence for dio.fetch. I create three dio instances.

`
  Dio dio = Dio(options); // for regular api
  Dio tokenDio = Dio(options); // for token
  Dio fetchDio = Dio(options) // for dio.fetch

  fetchDio.fetch(options).then() //  call fetchDio.fetch()
`

**Comment by supermebing** [comment]
> I have the same problem!

解决了吗
