### ISSUE TITLE
Improper Neutralization of CRLF Sequences in dio

### ISSUE THREAD

**Issue by diegolechado** [cfug/dio#1572]
- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

4 days ago I received a [security alert](https://github.com/advisories/GHSA-jwpw-q68h-r678) in my repository. 
I would like to know if this vulnerability still occurring.

Has anyone else received this alert?

**Comment by phamnhuvu-dev** [comment]
I don't see 
`Dependabot alerts • Enabled`
in the security tab in this [project](https://github.com/flutterchina/dio/issues)
