### ISSUE TITLE
下载文件时，如何获取文件名字和文件后缀？

### ISSUE THREAD

**Issue by BYDU** [cfug/dio#1573]
在我查看api中看到如下介绍，请问具体如何获取文件名字和文件后缀呢？

await dio.download(
url,

  (HttpHeaders headers){

    // parse `content-disposition ` here
    return "$filename"
  },
);

**Comment by yhsj0919** [comment]
一般下载请求，在响应头会有文件名，关注一下headers有没有Content-Disposition属性，解析之后返回即可
