### ISSUE TITLE
Dark mode readability issue for Dio Api reference.

### ISSUE THREAD

**Issue by akashgk** [cfug/dio#1575]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

<img width="1440" alt="Screenshot 2022-10-13 at 6 01 43 PM" src="https://user-images.githubusercontent.com/78728996/195597266-cfc97fef-9786-431c-939b-d81ec77a0b60.png">

<img width="1440" alt="Screenshot 2022-10-13 at 6 01 51 PM" src="https://user-images.githubusercontent.com/78728996/195597243-72c14fa5-4dc2-4d8a-bab1-0c0d8acdf076.png">

**Comment by AlexV525** [comment]
This is related to pub.dev rather than the package.
