### ISSUE TITLE
How to add Host header ?

### ISSUE THREAD

**Issue by rubyon** [cfug/dio#1577]
I have small legacy webserver.

it need "Host" header for connection...

when I use post man...

add key "Host" value "*"

works fine...

but in dio... "Host" header not working...

  var dio = Dio();
  dio.options.headers.addAll({'Host': '*'});
  final response = await dio.get('http://192.168.4.1/dir');
  print(response.data);

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: DioError [DioErrorType.response]: Http status error [400]

in Ruby

#####
require 'net/http'
uri = URI('http://192.168.4.1/dir')
puts Net::HTTP.get(uri) # => String
#####

it works...

**Comment by fotohidevina** [comment]
In the dio, the host will be automatically resolved to "192.168.4.1“，This is a standard HTTP protocol. You cannot set it to ”*“
