### ISSUE TITLE
Whole number doubles are converted to integer during json parsing

### ISSUE THREAD

**Issue by josephcrowell** [cfug/dio#1593]
### New Issue Checklist

#691 reports the same error but was ignored and closed as stale.

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                | flutter
| Platform Version              | 3.3.6
| Dio Version                    | 4.0.6                                  |      |
| Android Studio / Xcode Version | All current versions of Xcode and Android Studio               |      |
| Repro rate                     | all the time (100%)   |      |
| Demo project link              | #691 |      |

### Issue Description and Steps

I just changed my code based on the http library to dio. Under http/ json.decode, doubles with a precision of 0 like 153.000000 were correctly created as a double type per the dart standard, but in dio, any whole number double is instead converted to an integer. This violates the way doubles are supposed to work in Flutter/Dart and your json parser needs to be fixed to handle whole number doubles correctly.

The steps in #691 reproduce the issue.

**Comment by AlexV525** [comment]
Hi @josephcrowell, is the issue still reproducible? If so, could you provide mockable steps to reproduce instead of the code in the previous issue?

**Comment by AlexV525** [comment]
The test passed without failure.

![image](https://user-images.githubusercontent.com/15884415/207858993-6c9cd380-4a04-4dc5-8b88-2f685f2651b9.png)
