### ISSUE TITLE
Simple request passing with `http` package but not with dio

### ISSUE THREAD

**Issue by cedvdb** [cfug/dio#1601]
dio web has headers in its request which are not allowed for "Simple request", which means some request which shouldn't trigger preflight will trigger it. EG CORS errors.

There is a strict policy on how to be elligible for what's called "simple request":

Simple request
A simple cross-site request is one that meets all the following conditions:

The only allowed methods are:

GET
HEAD
POST
Apart from the headers set automatically by the user agent (e.g. Connection, User-Agent, etc.), the only headers which are allowed to be manually set are:

Accept
Accept-Language
Content-Language
Content-Type
The only allowed values for the Content-Type header are:

application/x-www-form-urlencoded
multipart/form-data
text/plain
A simple request will not cause a pre-flight OPTIONS request

--------------------------------------------

Here is an example URL which does not pass with dio `https://homologation-webpayment.payline.com/webpayment/getToken`  but will pass with the `http` package, content type should be `x-www-form-urlencoded`, just make a POST request with whatever data, DIO will trigger a preflight and a CORS issue

**Comment by alvarobcprado** [comment]
Same problem
