### ISSUE TITLE
Add SecurityContext to BrowserHttpClientAdapter

### ISSUE THREAD

**Issue by bvoq** [cfug/dio#1602]
### Issue Info

| Info                           | Value                                                 |
| ------------------------------ | ----------------------------------------------------- |
| Platform Name                  | web / flutter                         | 
| Dio Version                    | 4.0.6                                  |

### Issue Description and Steps

For mTLS certification I added a SecurityContext to the adapter in the following way for Android/iOS, creating the private keys and certificatechainbytes locally.
It seems that BrowserHttpClientAdapter does not have a .onHttpClientCreate and I'm not sure how I can add a security context to dio for the browser. Is this a missing feature?

Code example:
```
  Dio dio = Dio(options);
  if (!kIsWeb) { // works
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        ((client) {
      final SecurityContext sc = SecurityContext(withTrustedRoots: true);

      sc.useCertificateChainBytes(certificateChainBytes);
      sc.usePrivateKeyBytes(privateKeyBytes);

      HttpClient httpClient = HttpClient(context: sc);
      httpClient.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        return true;
      };
      return httpClient;
    });
  } else { // ???
    (dio.httpClientAdapter as BrowserHttpClientAdapter).withCredentials = true;
  }
```

**Comment by AlexV525** [comment]
`SecurityContext` is under `dart:io`, so it's not available for Web platforms.

**Comment by bvoq** [comment]
Maybe extend dio to work with: https://pub.dev/packages/universal_io

**Comment by AlexV525** [comment]
It just escapes visiting `dart:io` APIs in Web environment, doesn't do anything about `SecurityContext`.
