### ISSUE TITLE
Improve drop-in replacement experience between Dio and package `http`

### ISSUE THREAD

**Issue by navaronbracke** [cfug/dio#1604]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

Platform: Flutter, all platforms
Dio version: 4.0.6

### Issue Description and Steps

Context: I needed cancellation support for a specific request. Since package `http` does not support it (yet), I went with Dio.
However, Dio is not a drop-in replacement for `http` for a number of reasons:

1. The URI paths for get, put, post, etc. all require a `String` instead on an `Uri`. Thus I can't just paste in the existing call to `Uri.parse()` but I have to add a `.toString()` at the end.
2. The `data` parameter for those request methods is `dynamic` instead of `Object?`, which prevents type checks & type promotion by the Dart Analyzer, because dynamic skips all that.
3. Dio by default treats status codes in the `4xx - 5xx` range as errors, while `http` does not. Having to explicitly specify `validateStatus: (status) => true` is rather strange.
4. This last one is more of a question: Do we need to specify the request & response type in the `Options()` object? Or are those  inferred from the headers that you set for the request? Having to only specify headers makes it a little easier. Perhaps using an enhanced enum on `ResponseType` that specifies the header name could help too?

**Comment by AlexV525** [comment]
> 1. The URI paths for get, put, post, etc. all require a `String` instead on an `Uri`. Thus I can't just paste in the existing call to `Uri.parse()` but I have to add a `.toString()` at the end.

`DioMixin` has methods like `getUri` and `postUri` to use `Uri`s directly.

> 2. The `data` parameter for those request methods is `dynamic` instead of `Object?`, which prevents type checks & type promotion by the Dart Analyzer, because dynamic skips all that.

This is indeed a required improvement. We've implemented it in the other fork which will be published soon.

> 3. Dio by default treats status codes in the `4xx - 5xx` range as errors, while `http` does not. Having to explicitly specify `validateStatus: (status) => true` is rather strange.

How does `http` handle them then? Could you provide some samples?

> 4. This last one is more of a question: Do we need to specify the request & response type in the `Options()` object? Or are those inferred from the headers that you set for the request? Having to only specify headers makes it a little easier. Perhaps using an enhanced enum on `ResponseType` that specifies the header name could help too?

Types are usually implied automatically, so unless you have some other type of request, they should not be set manually too often.

**Comment by navaronbracke** [comment]
Well, with `http` it is expected that you do two things:
- handle `SocketException` / `ClientException` for network errors
- handle the result of `Response.statusCode` yourself, in other words HTTP is unopinionated on this.
  The example in the docs is like this: 
  
  ```
import 'package:http/http.dart' as http;

final url = Uri.https('example.com', 'whatsit/create');
final response = await http.post(url, body: {'name': 'doodle', 'color': 'blue'});
print('Response status: ${response.statusCode}');
print('Response body: ${response.body}');
  ```
  
 A real world example would then look like:
 
 ```
 import 'package:http/http.dart';
 
 try {
   final url = Uri.https('example.com', 'whatsit/create');
   final response = await http.post(url, body: {'name': 'doodle', 'color': 'blue'});
   final int statusCode = response.statusCode;
   
   
   if() {
   
   }
 } on ClientException catch (error) {
   print('Network error: $error');
 }
 ```
