### ISSUE TITLE
[Proposal] Deprecate/Archive this package

### ISSUE THREAD

**Issue by josh-burton** [cfug/dio#1608]
Dio has been stagnant for a while, despite being one of the most widely used packages in Flutter.

Now that [DioX](https://github.com/cfug/diox) has been forked, the maintainers of Dio need to make a call.

If this package will realistically not be actively maintained, it should be deprecated and archived.

**Comment by ImClieo** [comment]
Is there no response from @wendux ?
Please take some stance on this issue - currently this is the 2nd biggest http package in flutter and it's not maintained.
New flutter developers will just add this without thinking twice about the last commit date.

**Comment by hurelhuyag** [comment]
Dio's maintainer is tired, and Diox's maintainers forked from the Dio. Why not just merge Diox into Dio.

**Comment by ImClieo** [comment]
> Dio's maintainer is tired, and Diox's maintainers forked from the Dio. Why not just merge Diox into Dio.

Why would you merge Diox into Dio? Diox is a HARD fork from Dio.
I understand the maintainer being tired, but then take a stance and archive this repo, paving the way for Diox or other Http packages. Right now Dio is living on, without dependency bumps, security fixes and what not.
