### ISSUE TITLE
dio is slow

### ISSUE THREAD

**Issue by mehdidavar** [cfug/dio#1609]
dio in simple api get method take 3 seconds but I take response in postman 300 milliseconds

**Comment by loveoverflowdev** [comment]
How about this comparing: Your simulator is slow while postman is fast ?

**Comment by muhammedrashidm** [comment]
> How about this comparing: Your simulator is slow while postman is fast ?

Yes, I have the same issue, while testing with a 3g/2g network on an emulator, but in chrome, even with network throttling, I am able to fetch data. server is aws
