### ISSUE TITLE
Flutter Converting object to an encodable object failed: Instance of 'FormData'

### ISSUE THREAD

**Issue by LambGe** [cfug/dio#1610]
this is my code:
final FormData formData = FormData.fromMap(<String, dynamic>{
        'file': await MultipartFile.fromFile(path, filename: name),
        'type': "image/png",
      });

dio.post(apiUrl,
        data: formData,
        options: Options(contentType: 'multipart/form-data'));

when I try to upload image to server, some problems like this:
Flutter Converting object to an encodable object failed: Instance of 'FormData'

**Comment by febryardiansyah** [comment]
hi, i have same problem with you then i found the solution that you can handle it by set the contentType to **MediaType("image","png")**, but you need this package to use Mediatype https://pub.dev/packages/http_parser

example:
```dart
FormData.fromMap({
        "profile_pic": await MultipartFile.fromFile(
          imagePath,
          filename: imagePath.split('/').last,
          contentType: MediaType("image", "jpeg"),
        ),
      })
```
it works so well for me!

**Comment by kouseina** [comment]
@febryardiansyah yeah me too

**Comment by febryardiansyah** [comment]
@kouseina good to hear that!

**Comment by NicolasKim** [comment]
Check your interceptor. When you trying to `jsonEncode(request data(which is include FormData))`, it will throw this exception. Hope this help
