### ISSUE TITLE
Dio freeze on widget test

### ISSUE THREAD

**Issue by EmadBeltaje** [cfug/dio#1613]
i use Dio in my [skeleton](https://github.com/EmadBeltaje/flutter_getx_template) and iam trying to write **widget test** for my [function](https://github.com/EmadBeltaje/flutter_getx_template/blob/master/lib/app/services/base_client.dart) which use dio for api call and show toast if there was error while making api request **the problem is widget test code freeze when i start making api request using dio **, i made a simple code just to view the problem
```dart
main() {
  // mock dio
  var dio = Dio();
  final dioAdapter = DioAdapter(dio: dio);

  testWidgets('test 500 error',(tester) async {
    // *) pump dummy widget
    await tester.pumpWidget(const Center(child: Text('haha'),));

    // *) dummy route
    String route = 'https://www.facebook/emadbeltaje.com';

    // *) simulate server 500 internal error
    dioAdapter.onGet(route, (server) {
      server.reply(500, null);
    });

    // *) perform api request on our dummy url
    try {
      // !) "" -> CODE FREEZE HERE <- ""
      Response response = await dio.get(route);
    }catch(error) {
      expect((error as DioError).response?.statusCode,500);
    }
  });
}
```

**Comment by ahmednfwela** [comment]
@AlexV525 why was this closed? I can still reproduce this on latest version

**Comment by ahmednfwela** [comment]
you switched from testWidget to just test,
but I solved it by wrapping the contents of my test with `tester.runAsync` and changing `HttpOverrides.global` to allow http requests

**Comment by EmadBeltaje** [comment]
@ahmednfwela 
iam sorry i ment this class [here](https://github.com/EmadBeltaje/flutter_getx_template/blob/master/integration_test/baseclient_test.dart)

**Comment by Yongle-Fu** [comment]
`
void main() async {
  // work fine
  test('dio get test', () async {
    await dioGetTest();
  });
  // work bad, always get 400 status code
  test('dio get test', () async {
    TestWidgetsFlutterBinding.ensureInitialized();
    await dioGetTest();
  });
  // work fine
  test('dio get test', () async {
    IntegrationTestWidgetsFlutterBinding.ensureInitialized();
    await dioGetTest();
  });
}

Future dioGetTest() async {
  final dio = Dio();
  final res = await dio.get('https://xxx');
  print(res);
}
`
What could be the reason behind this error?

**Comment by kuhnroyal** [comment]
This is normal behavior for Flutter widget tests. There are tons of related issues in the Flutter repository or on Stackoverflow.
