### ISSUE TITLE
Dio is not able to process the requests with new QueuedInterceptorsWrapper on resuming the app again after putting it in background for 20-30 min

### ISSUE THREAD

**Issue by suryamolly** [cfug/dio#1630]
### New Issue Checklist

- [ ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |    
| ------------------------------ | ----------------------------------------------------- | 
| Platform Name                  |flutter                          |      
| Platform Version               | 3.3.6                              |      
| Dio Version                    | 4.0.6                                 |      
| VS code Version | version 1.75.0              |      
| Repro rate                     | All the time (100%)   |      
| Repro with our demo prj        | Unknown            |      
| Demo project link              | NA |      

### Issue Description and Steps

I have encountered a strange behaviour with the version (4.0.6) while using the **QueuedInterceptorsWrapper** class , After the app is switched to foreground after keeping the app in background for 20-30 minutes. Dio library is not able to process the requests.

### Step to reproduce

1. Launch the app
2. Minimise the app in the background/app switcher menu (not to kill app.) keep app in background for 20-30 min.
3. Move app to foreground from background via app switcher menu.
4. Observe the behaviour.

### Expected behaviour

Dio should be able to take the requests and process it accordingly.

### Actual Behaviour

Dio is not able to process the requests , No logs are produced, looks like Dio is not responding.

**Comment by lsuhov** [comment]
Hello @AlexV525 ,
Can you tell us why this issue has been closed?
Thank you

**Comment by AlexV525** [comment]
See #1607

**Comment by vimaxwell** [comment]
@lsuhov do u have same issue with dio 5.0.0?
