### ISSUE TITLE
Transfer Dio Ownership

### ISSUE THREAD

**Issue by feinstein** [cfug/dio#1631]
@wendux since you are no longer maintaining the library, I would suggest you transfer its owenship to the Flutter community repo, or maybe even the Dart team.

Would you be open to this kind of chance? Dio is very widely used and not being maintained can be a huge impact in the Flutter ecosystem.

**Comment by thisisyusub** [comment]
I am absolutely agree with it. I have many projects depend on dio. It is awesome http client. We can maintain it by community.

**Comment by jacobaraujo7** [comment]
@wendux if you prefer, Flutterando can take care of the Package for you.

**Comment by josh-burton** [comment]
A community group has already stepped forward to maintain and develop dio as diox. 
If ownership is going to be transferred, it should be transferred to them.

**Comment by toshiossada** [comment]
> @wendux if you prefer, Flutterando can take care of the Package for you.

flutterando it's the biggest brazil community, if you want it will pleasure continue dio

**Comment by DiegoEmanuel** [comment]
Flutterando <3

**Comment by felipecastrosales** [comment]
@josh-burton are you referring to this? 
- https://github.com/cfug/diox

**Comment by felipecastrosales** [comment]
> A community group has already stepped forward to maintain and develop dio as diox. If ownership is going to be transferred, it should be transferred to them.

are you referring to this, right?
- https://github.com/cfug/diox
- https://pub.dev/packages/diox

**Comment by josh-burton** [comment]
> 

Yes. It's a fork by community members who have already been in active in the maintenance of Dio for a few years.

**Comment by felipecastrosales** [comment]
@josh-burton, interesting, I didn't know her. Thanks for sharing this information, very relevant to this discussion.

**Comment by wendux** [comment]
OK, I will transfer ownership to flutter.cn org

**Comment by AlexV525** [comment]
The transfer has been done. Thanks @wendux!

**Comment by AlexV525** [comment]
We'll continue to announce our process with this package in #1607.
