### ISSUE TITLE
v5.0.0 manually setting the content-type

### ISSUE THREAD

**Issue by hasanmhallak** [cfug/dio#1646]
### Request Statement

I was just wondering why did you remove the default content-type?

I think this would be a problem for people like me who had a huge set of apis that bunch of them is sending a multi-part form data.

the problem is I was only specifying the content type when I'm about to send a multi-part form. Now to migrate all the project I have to edit every endpoint that doesn't send a multi part form. And I think this would be tedious.

And thanks for keeping this Great library up-to-date!

### Solution Brainstorm

The first thing that comes to mind is set up an interceptor and check for the data type if it is a `FormData` or not. I don't know yet if this is a valid solution or not. But why all the hustle?

**Comment by AlexV525** [comment]
> I was just wondering why did you remove the default content-type?

We've voted for this before the release. See the explanation in the discussion: https://github.com/cfug/diox/discussions/52.

> The first thing that comes to mind is set up an interceptor and check for the data type if it is a `FormData` or not. I don't know yet if this is a valid solution or not.

Yes, using interceptors or helper methods are recommended in this case.

> But why all the hustle?

It's actually a while in the diox, still it seems a little bit hustle for dio, but it's under a major version release, I'd say let's take our time. :)

**Comment by AlexV525** [comment]
Closing as it's intended, and you can still reply if you have more concerns or questions.
