### ISSUE TITLE
v5 and mass closed tickets?

### ISSUE THREAD

**Issue by hampsterx** [cfug/dio#1652]
hi there,

I was tracking a bunch of issues:

#1392
#1407
#1433
#1230
#1261

These are many many more have all been "closed" without explanation.

What is the rational for doing this? Is it that v5 is considerably different that these issues are no longer relevant or what??

much appreciated~

**Comment by hampsterx** [comment]
Ahh i see #1644

Time to a fresh leaf~

**Comment by AlexV525** [comment]
Please submit issues if they're still valid and folliwing the new template, thanks.
