### ISSUE TITLE
[Notice] Set a proper `content-type` for requests when using Dio 5.0

### ISSUE THREAD

**Issue by AlexV525** [cfug/dio#1653]
The issue intends to tell users that don't follow our migration guide well, then come to search for relevant issues. This issue will be opened and pinned until we release 5.1.x or 6.0.x.

## Context

We've discussed why we have removed the default `content-type` in https://github.com/cfug/diox/discussions/52. The implied `content-type` makes the maintainers hard to determine instantly if issues are related. So we decide to do less: remove all implied `content-type`.

## Summary

Since the 5.0 release, all options and transformers will no longer imply the default `content-type` according to your payload type. This means if you don't explicitly set the `content-type`, requests might resulting failure, and this widely affects most of your requests. In order to use 5.0.x, you'll need to configure the `content-type` properly.

Requests with the `FormData` payload requires no further migrations.

## How?

Reading the migration guide with the *"Set content-type manually"* section should be the first step. https://github.com/cfug/dio/blob/main/dio/migration_guide.md#set-content-type-manually

- Use `Headers.formUrlEncodedContentType` if your payloads are typically a `Map`.
- Use `Headers.jsonContentType` if your payloads are typically an encoded JSON string.
- Use `Headers.textPlainContentType` if your payloads are typically string without any structures.

### Quick handling

- Add the most used `content-type` to your `BaseOptions`. For example:
  ```dart
  dio.options.contentType = Headers.jsonContentType;
  ```
- Add `Options.contentType` for each requests with a payload. For example:
  ```dart
  dio.post(
    'your_url',
    data: jsonEncodedString,
    options: Options(contentType: Headers.jsonContentType),
  )
  ```

#### Using `Interceptor`

```dart
InterceptorsWrapper(
  onRequest: (
    RequestOptions options,
    RequestInterceptorHandler handler,
  ) {
    if (options.contentType == null) {
      final dynamic data = options.data;
      final String? contentType;
      if (data is FormData) {
        contentType = Headers.multipartFormDataContentType;
      } else if (data is Map) {
        contentType = Headers.formUrlEncodedContentType;
      } else if (data is String) {
        contentType = Headers.jsonContentType;
      } else if (data != null) {
        contentType = Headers.textPlainContentType; // Can be removed if unnecessary.
      } else {
        contentType = null;
      }
      options.contentType = contentType;
    }
    handler.next(options);
  },
)
```

**Comment by HelenaSewell** [comment]
"The issue intends to tell users that don't follow our migration guide well, then come to search for relevant issues."
This linked part of the migration guide doesn't seem to exist. Am I missing something or is there no mention of this huge breaking change in the migration guide, and none in the changelog either?

**Comment by AlexV525** [comment]
> Am I missing something or is there no mention of this huge breaking change in the migration guide, and none in the changelog either?

It's been reverted by the new implementation in #1671. So as the migration guide.

**Comment by HelenaSewell** [comment]
I see, thanks. It doesn't seem to be working for me atm. I'll investigate more and see if I need to report an issue or not.

**Comment by HelenaSewell** [comment]
Update: my particular issue is caused by Freezed, not this library. Thanks for your help 👍

**Comment by riteshakya037** [comment]
For people facing this issue when using Retrofit and Freezed and build_runner ^2.4.4, here's the reference ticket in [Retrofit](https://github.com/trevorwang/retrofit.dart/issues/570) and the solution is to add this to build.yaml

```
global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
```

Reference: https://github.com/dart-lang/build/issues/3509
