### ISSUE TITLE
Using Options BaseUrl assertion fails

### ISSUE THREAD

**Issue by AbanoubNassem** [cfug/dio#1655]
### Package

dio

### Version

5.0.0

### Steps to Reproduce

for example make a `Dio` client like this:

```
 static const String _baseURL = "https://example.com"

 final _http = Dio(
    BaseOptions(
      baseUrl: _baseURL,
      headers: {
        "accept": "application/json",
        "x-requested-With": "XMLHttpRequest",
        'content-type': 'application/json',
      },
    ),
  );
```

### Expected Result

the client should send the request and it works normally.

### Actual Result

```
Assertion failed:
options.dart:103
baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty
is not true
```

**Comment by AlexV525** [comment]
@dafinoer Can you identify if this is valid and not being covered in the previous tests?

**Comment by AbanoubNassem** [comment]
> @dafinoer Can you identify if this is valid and not being covered in the previous tests?

well I didn't check the testing, however by changing the assertion from :

` assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`

to : 

`assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isEmpty)`

it works, fine , tested on web and mobile platforms , I have made a pull-request as well.

**Comment by AlexV525** [comment]
Sure, just called who authored this and see if additional information can be provided.

**Comment by dafinoer** [comment]
> > @dafinoer Can you identify if this is valid and not being covered in the previous tests?
> 
> well I didn't check the testing, however by changing the assertion from :
> 
> ` assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`
> 
> to :
> 
> `assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isEmpty)`
> 
> it works, fine , tested on web and mobile platforms , I have made a pull-request as well.

if you add `isEmpty`, then you set the URL like `hallo world` the result `true` we know the `hallo world` is an incorrect URL.

please check this unit test: [link](https://github.com/cfug/dio/blob/main/dio/test/options_test.dart#L380)

**Comment by AbanoubNassem** [comment]
> > > @dafinoer Can you identify if this is valid and not being covered in the previous tests?
> > 
> > 
> > well I didn't check the testing, however by changing the assertion from :
> > ` assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`
> > to :
> > `assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isEmpty)`
> > it works, fine , tested on web and mobile platforms , I have made a pull-request as well.
> 
> When you add `isEmpty`, then you set the URL like `hallo world` the result `true` we know the `hallo world` is an incorrect URL.
> 
> please check this unit test: [link](https://github.com/cfug/dio/blob/main/dio/test/options_test.dart#L380)

@dafinoer  I'm not really getting what you are saying:

here : https://github.com/cfug/dio/blob/ac252d876be138169d30731dae40ad1b2716d270/dio/test/options_test.dart#L391 

the test is validating that the host empty, which is correct.

but in the implementation : 

`assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`

we should fail if the host `isEmpty` , not if the host `isNotEmpty`?

or I'm missing something here?

**Comment by AbanoubNassem** [comment]
> > > @dafinoer Can you identify if this is valid and not being covered in the previous tests?
> > 
> > 
> > well I didn't check the testing, however by changing the assertion from :
> > ` assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`
> > to :
> > `assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isEmpty)`
> > it works, fine , tested on web and mobile platforms , I have made a pull-request as well.
> 
> When you add `isEmpty`, then you set the URL like `hallo world` the result `true` we know the `hallo world` is an incorrect URL.
> 
> please check this unit test: [link](https://github.com/cfug/dio/blob/main/dio/test/options_test.dart#L380)

in the testing here: https://github.com/cfug/dio/blob/ac252d876be138169d30731dae40ad1b2716d270/dio/test/options_test.dart#L391

the host will be empty , hence this is correct:

`expect(Uri.parse(opt6).host.isNotEmpty, false);`

but it's confusing it should be `expect(Uri.parse(opt6).host.isEmpty, true);`
so now in the test we fail if the host is empty.

but in the implementation:

`assert(baseUrl.isEmpty || Uri.parse(baseUrl).host.isNotEmpty)`

we asserting/failing if the host is not empty , which is wrong , we should fail if it's empty, which mean we have no host!

or am I missing something here?

**Comment by AbanoubNassem** [comment]
after deep investigations , the error was due to bad configurations on my end , it used to work with older version tho.

sorry for the inconvenience .

**Comment by AlexV525** [comment]
@dafinoer Could you help us to document this better to avoid such issues again?

**Comment by Chappie74** [comment]
@AbanoubNassem  What exactly was the bad configs, as I am having the same issue that worked before?
