### ISSUE TITLE
[Web] Cookies are not automatically set after updating to 5.0.0

### ISSUE THREAD

**Issue by sun-jiao** [cfug/dio#1663]
### Package

dio

### Version

5.0.0

### Output of `flutter doctor -v`

```shell
C:\flutter\bin\flutter.bat doctor --verbose
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[!] Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.22621.1265], locale zh-CN)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    ! The flutter binary is not on your path. Consider adding C:\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (8 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\{username}\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Connected device (4 available)
    • PHM110 (mobile)   • 50b75a5b • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [版本 10.0.22621.1265]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 110.0.5481.96
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 110.0.1587.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 5 categories.
Process finished with exit code 0
```

### Dart Version

2.19.2

### Steps to Reproduce

Here is my code:

```
static const String url = 'http://127.0.0.1:5000/';
static BaseOptions options = BaseOptions(
  baseUrl: url,
  headers: {
    "Accept": "application/json",
  },
);
static Dio dio = Dio(options);
var adapter = BrowserHttpClientAdapter();
adapter.withCredentials = true;
dio.httpClientAdapter = adapter;

await dio.get('/url', queryParameters: {'param': 'value'});
```

There are `set-cookies` in the response headers, but they are not automatically set.

As far as I know, dart codes are converted to js codes in flutter web projects, where cookies should be automatically managed by the browser (for me, it's chrome), and we could not set them manually. 

Previously, dio 4.0.6 was used in my project, and the above codes worked fine. But after updating to 5.0.0, the cookies in `set-cookies` are not automatically set. 

Is it possible to let me know the correct practice in the new version?

### Expected Result

4.0.6:

![image](https://user-images.githubusercontent.com/14086980/219568463-ecfc1d19-aed0-4f08-86d6-64837b2c3b13.png)

cookies in `set-cookies` are automatically set in the next request:

![image](https://user-images.githubusercontent.com/14086980/219568568-393ba603-fa54-4f62-8e36-99ddfce38626.png)

### Actual Result

after updating to 5.0.0:

![image](https://user-images.githubusercontent.com/14086980/219566585-608d6cda-c597-4f41-9b96-ecef8633c727.png)

cookies in `set-cookies` are not automatically set in the next request:

![image](https://user-images.githubusercontent.com/14086980/219566861-f682010a-b196-4ff4-83b8-82eed9b71bed.png)

**Comment by AlexV525** [comment]
Perhaps it's caused by a merging issue with your header values. Can you change `headers: {"Accept": "application/json"}` to `contentType: "application/json"` to see if it works?

**Comment by sun-jiao** [comment]
@AlexV525 Thanks but it doesn't work.

**Comment by sun-jiao** [comment]
@AlexV525 

I think I've found the problem:

In [this file](https://github.com/cfug/dio/blob/main/dio/lib/src/adapters/browser_adapter.dart), a function variable shadowed a class variable with the same name (`withCredentials`), make the class variable invalid. 

I have downloaded the repository and will try to see if I can fix it.

**Comment by sun-jiao** [comment]
No other bugs were found to causing this problem.
