### ISSUE TITLE
Dio Equivalent of httpClient.postAsJsonAsync() method

### ISSUE THREAD

**Issue by bishal-rumba007** [cfug/dio#1666]
### Request Statement

I want to know if there is dio equivalent of httpClient.postAsJsonAsync() method.
I want to know because i want to be able to send request along with a model encoded as json.
this particular method is from the C# .net core.
its further explanation as provided by microsoft is 
`
public static Task<HttpResponseMessage> PostAsJsonAsync<T>(
    this HttpClient client,
    string requestUri,
    T value
)
`
Parameters
client
Type: [System.Net.Http.HttpClient](https://msdn.microsoft.com/en-us/library/hh193681(v=vs.118))
requestUri
Type: [System.String](https://msdn.microsoft.com/en-us/library/s1wwdcbf(v=vs.118))
value
Type: T

for further info please refer to this.
[https://learn.microsoft.com/en-us/previous-versions/aspnet/hh944682(v=vs.118)](url)

**Comment by ueman** [comment]
Hey, you can take a look at the examples: https://github.com/cfug/dio/tree/main/dio#examples

Especially this one:
```dart
response = await dio.post('/test', data: {'id': 12, 'name': 'dio'});
```

That should get you started.
