### ISSUE TITLE
Memory usage keeps increase when doing repeatedly requests on Windows

### ISSUE THREAD

**Issue by zhhding** [cfug/dio#1668]
### Package

dio

### Version

5.0.0

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.22621.1265], locale zh-CN)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\zhhding\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\zhhding\AppData\Local\Android\Sdk
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\zhhding\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.1265]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.46

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Dart Version

2.19.2

### Steps to Reproduce

dio请求很多次以后,内存飙升,并且不会下降

### Expected Result

![6f1716abd4205d1c2d7142d077841ba](https://user-images.githubusercontent.com/7225351/219703361-36f49782-94ea-4c2c-8de1-b9060081c5b9.png)

### Actual Result

![eebe878811f9c69b8a2c5349e4abba7](https://user-images.githubusercontent.com/7225351/219703395-bb3ef8e3-2be4-4af1-bc56-31266408a7a3.png)

**Comment by zhhding** [comment]
memeory usage get veryhigh after hundreds request in windows ,and memory usage will not go down

**Comment by AlexV525** [comment]
Please provide your minimum testing code.

**Comment by zhhding** [comment]
// testdio
 testdio() async {
    try {
      for (var i = 0; i < 100; i++) {
        await RoomAPI.getTestRoomList();
        Future.delayed(Duration(seconds: 5));
        print("dio测试$i");
      }
    } catch (e) {}
  }

//testapi

  static Future getTestRoomList() async {
    await HttpUtilt().get('bankroom.getlist', model: Model.SAAS);
  }

// httputilt


class HttpUtilt {
  static HttpUtilt _instance = HttpUtilt._internal();
  factory HttpUtilt() => _instance;

  static late Dio dio;
  CancelToken cancelToken = new CancelToken();
  // Cookie管理
  static late BaseOptions options;

  HttpUtilt._internal() {
    // BaseOptions、Options、RequestOptions 都可以配置参数，优先级别依次递增，且可以根据优先级别覆盖参数
    options = new BaseOptions(
      // 请求基地址,可以包含子路径
      baseUrl: Global.verReleaseServer ? SERVER_API_URL : SERVER_API_URL_DEBUG,
      //连接服务器超时时间，单位是毫秒.
      connectTimeout: Duration(seconds: 30),

      // 响应流上前后两次接受到数据的间隔，单位为毫秒。
      receiveTimeout: Duration(seconds: 30),

      // Http请求头.
      headers: {"X-Requested-With": "XMLHttpRequest"},

      /// 请求的Content-Type，默认值是"application/json; charset=utf-8".
      /// 如果您想以"application/x-www-form-urlencoded"格式编码请求数据,
      /// 可以设置此选项为 `Headers.formUrlEncodedContentType`,  这样[Dio]
      /// 就会自动编码请求体.
      contentType: 'application/json; charset=utf-8',

      /// [responseType] 表示期望以那种格式(方式)接受响应数据。
      /// 目前 [ResponseType] 接受三种类型 `JSON`, `STREAM`, `PLAIN`.
      ///
      /// 默认值是 `JSON`, 当响应头中content-type为"application/json"时，dio 会自动将响应内容转化为json对象。
      /// 如果想以二进制方式接受响应数据，如下载一个二进制文件，那么可以使用 `STREAM`.
      ///
      /// 如果想以文本(字符串)格式接收响应数据，请使用 `PLAIN`.
      responseType: ResponseType.json,
    );

    dio = new Dio(options);

    // dio.interceptors.add(CookieManager(cookieJar));

    // 添加拦截器
    dio.interceptors.add(InterceptorsWrapper(
      onRequest: (options, handler) {
        // Do something before request is sent
        return handler.next(options); //continue
        // 如果你想完成请求并返回一些自定义数据，你可以resolve一个Response对象 `handler.resolve(response)`。
        // 这样请求将会被终止，上层then会被调用，then中返回的数据将是你的自定义response.
        //
        // 如果你想终止请求并触发一个错误,你可以返回一个`DioError`对象,如`handler.reject(error)`，
        // 这样请求将被中止并触发异常，上层catchError会被调用。
      },
      onResponse: (response, handler) {
        // Do something with response data
        return handler.next(response); // continue
        // 如果你想终止请求并触发一个错误,你可以 reject 一个`DioError`对象,如`handler.reject(error)`，
        // 这样请求将被中止并触发异常，上层catchError会被调用。
      },
      onError: (DioError e, handler) {
        ErrorEntity eInfo = createErrorEntity(e);
        switch (eInfo.code) {
          case 50015: // 没有权限 重新登录
            // goLoginPage();
            break;
          default:
        }
        Logger.writeFile("请求出错:${e.requestOptions.path}", folderName: 'httplogs');
        Response response = Response(requestOptions: RequestOptions(path: ''), data: eInfo.toMap(), statusCode: -1);

        return handler.resolve(response);
      },
    ));
  }

  /// restful get 操作
  /// refresh 是否下拉刷新 默认 false
  /// noCache 是否不缓存 默认 true
  /// list 是否列表 默认 false
  /// cacheKey 缓存key
  /// cacheDisk 是否磁盘缓存
  Future get(String path,
      {Map<String, dynamic>? queryParameters,
      Options? options2,
      bool refresh = false,
      bool noCache = !CACHE_ENABLE,
      bool list = false,
      String cacheKey = '',
      bool cacheDisk = false,
      String logFolder = "",
      required Model model,
      HeadModel? headModel = HeadModel.APP}) async {
    Options requestOptions = options2 ?? Options();
    if (requestOptions.extra == null) {
      requestOptions.extra = Map();
    }
    requestOptions.extra!.addAll({
      "refresh": true,
      "noCache": noCache,
      "list": list,
      "cacheKey": cacheKey,
      "cacheDisk": cacheDisk,
    });
    if (requestOptions.headers == null) {
      requestOptions.headers = Map<String, dynamic>();
    }
    if (Global.userInfo.value.token.isNotEmpty) {
      requestOptions.headers!.addAll({"token": Global.userInfo.value.token});
    }
    if (Global.deviceSN != "") {
      requestOptions.headers!.addAll({"serial": Global.deviceSN});
    }
    //实例化Random类并赋值给变量rng；
    var rng = new Random();
    requestOptions.headers!.addAll({"number": rng.nextInt(10000)});

    var addPath = "";
    if (model == Model.FILE) {
      addPath = sprintf(ModelUrls[model].toString(), [HeadModelUrls[headModel].toString(), path]);
    } else if (model == Model.BASE) {
      addPath = sprintf(ModelUrls[model].toString(), [HeadModelUrls[headModel].toString(), path]);
    } else if (model == Model.COMMON) {
      addPath = sprintf(ModelUrls[model].toString(), [HeadModelUrls[headModel].toString(), path]);
    } else {
      addPath = sprintf(ModelUrls[model].toString(), [HeadModelUrls[headModel].toString(), Global.deviceInfo.uniacid, path]);
    }

    try {
      Dio dio2 = new Dio(options);
      Response response = await dio2.get(
        addPath,
        queryParameters: queryParameters,
        options: requestOptions,
        cancelToken: cancelToken,
      );
      var data = response.data;
      dio2.close();

      return data;
    } catch (e) {
      toastInfo(msg: "Dio请求出错$addPath!");
      Logger.e("Dio请求出错Get");
    }
  }
}

**Comment by zhhding** [comment]
bankroom.getlist ,this api response about 100k data per time

**Comment by zhhding** [comment]
this is memery usage when application start
![1676726876422](https://user-images.githubusercontent.com/7225351/219868407-167607b3-8491-4bfc-8dcd-8f0fa2fbe241.png)
this is memery usage when 100 request  called
![1676727276920](https://user-images.githubusercontent.com/7225351/219868655-79979f74-e503-4fb5-9c01-e6be58926baa.png)

**Comment by AlexV525** [comment]
> bankroom.getlist ,this api response about 100k data per time

Providing codes from your project doesn't help in this case, consider creating a demo with the minimum integration of dio to test if the behavior still exists.

**Comment by cal-g** [comment]
This could be related to https://github.com/dart-lang/sdk/issues/49506 which happens during profiling.

**Comment by AlexV525** [comment]
Closing as above ref.
