### ISSUE TITLE
Dio return wrong response with Postman

### ISSUE THREAD

**Issue by thinhhja2001** [cfug/dio#1670]
### Package

dio

### Version

^5.0.0

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (4 weeks ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\thinh\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\thinh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 109.0.1518.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Dart Version

2.19.0

### Steps to Reproduce

I'm using Dio to get response from an API. But it couldn't get the same response with what has been tested using Postman.

I tried using the case-sensitive in the header but if couldn't solve the problem. Using the http from the Flutter team package couldn't solve this problem too.

But while I'm using axios package on https://www.npmjs.com/package/axios, it will get me the same response with Postman

Header using Dio
![image](https://user-images.githubusercontent.com/81420944/219846154-a74b8f78-c439-46d3-a595-e0bfd954bc99.png)

Response using Postman
![image](https://user-images.githubusercontent.com/81420944/219846135-32881c00-b7bb-4051-87a7-9c2d6f25610a.png)

The response using Dio is the response I will get if I set the header  with a wrong value.

### Expected Result

![image](https://user-images.githubusercontent.com/81420944/219845924-6667f595-d4d2-4358-8611-85d0b4f95cc8.png)

### Actual Result

![image](https://user-images.githubusercontent.com/81420944/219845965-0ff3c358-f837-4218-be5a-73d24a479a66.png)

**Comment by ueman** [comment]
Have you tried setting the same headers with dio as with Postman? As your screenshot shows, there's a difference in the headers

**Comment by thinhhja2001** [comment]
Yeah. I've just check it out. Turn out it was my fault. I gonna close this issue by now
