### ISSUE TITLE
http/3 support in `NativeAdapter` for cupertino

### ISSUE THREAD

**Issue by Vovcharaa** [cfug/dio#1672]
### Request Statement

As far as I know to enable http/3, I need to set `assumesHTTP3Capable` to  `true` but there is no way of doing this right now. Is it possible to provide this field to client on `NativeAdapter` initialization?

**Comment by AlexV525** [comment]
Which class has `assumesHTTP3Capable` in this case?

**Comment by Vovcharaa** [comment]
@AlexV525  `NSURLRequest` and `NSMutableURLRequest` in cupertino_http library (native_cupertino_bindings.dart file)

**Comment by ueman** [comment]
You can use `CupertinoAdapter` and configure it as needed. `NativeAdapter doesn't support configuration and just delegates to the respective platform adapter

**Comment by Vovcharaa** [comment]
@ueman I dont see any way to provide this property in `CupertinoAdapter` either.

**Comment by ueman** [comment]
Then it's not a problem of this library as this library just wraps https://pub.dev/packages/cupertino_http

If `cupertino_http` does not provide http3 functionality, this library can't add it.
