### ISSUE TITLE
How to send a null value?

### ISSUE THREAD

**Issue by omidraha** [cfug/dio#1681]
I have this map:

```dart
    Map<String, dynamic> apiData = {
      "user":  123,
      "desc": null,
    };
```
And I'd like to send this `null` value as a key in the  `json`  data to the back-end.

But  when I create `formData` from this map  data:

```dart
FormData formData = FormData.fromMap(apiData);
// Also there is an image field
formData.files.add(MapEntry("image", await MultipartFile.fromFile("image.png"));

```
 Its key is deleted from the data, based on this code:

https://github.com/cfug/dio/blob/bb573bc565803f37797b7a21c3f0dedf750d54cc/dio/lib/src/form_data.dart#L51

output:
```dart
print(formData.fields.toString());
[MapEntry(user: 123), ]
```

**Comment by omidraha** [comment]
Did you have a suggestion or solution?

**Comment by patana93** [comment]
WIP: #977
