### ISSUE TITLE
dio 5.0.0 设置BaseOptions  contentType 失效

### ISSUE THREAD

**Issue by jiajialaixi** [cfug/dio#1682]
### Package

dio

### Version

5.0.0

### Steps to Reproduce

1、设置  DIo  baseOptions  contentType=Headers.formUrlEncodedContentType 

2、post的请求不携带 contentType =Headers.formUrlEncodedContentType 

3、请求结果contentType 的值会变成application/json;

### Expected Result

期望设置baseOptions 中的contentType 不在重复设置 

### Actual Result

![image](https://user-images.githubusercontent.com/20548416/220275218-06ce607d-ae86-45b6-ace3-063c9fc30b0a.png)

**Comment by AlexV525** [comment]
The **response** content-type is not equivalent to the **request** content-type.

**Comment by jiajialaixi** [comment]
![image](https://user-images.githubusercontent.com/20548416/220278011-955277f0-6c07-4974-835b-932ea33c61bf.png)
请求的时候并不会携带content-type

**Comment by jiajialaixi** [comment]
![image](https://user-images.githubusercontent.com/20548416/220278399-f645c5a5-a33d-40c0-97a9-e43ccc8e92b8.png)
我在拦截器中添加head会生效

**Comment by AlexV525** [comment]
You have multiple interceptors configured with your instance and the description is different from your original comment. Please consider providing a minimum reproducible example and submit a new issue.
