### ISSUE TITLE
Request headers missing after automatic redirect

### ISSUE THREAD

**Issue by wilinz** [cfug/dio#1693]
### Package

dio

### Version

5.0.1

### Steps to Reproduce

1. request a 302 redirect to the site
2. set request header "user-agent"
3. view log

### Expected Result

The redirection will carry the previous request header

### Actual Result

The redirect does not bring the previous request header

**Comment by wilinz** [comment]
You can only see the redirection information using a packet capture tool. The dio interceptor cannot intercept automatic redirection. Is this a bug?

**Comment by AlexV525** [comment]
Please provide a minimal reproducible example.

**Comment by wilinz** [comment]
Dio().get("http://xxx"); // This a 302 url

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/221346202-42e8654a-ee33-407c-a294-6b367dd6487c.png)

**Comment by wilinz** [comment]
Can you use fiddler to grab packets and have a look
