### ISSUE TITLE
Dio post auto redirection is not available

### ISSUE THREAD

**Issue by wilinz** [cfug/dio#1694]
### Package

dio

### Version

5.0.1

### Steps to Reproduce

```
Dio().post("http://xxx")  //This is a url that returns a 302 code
```

### Expected Result

redirect to new url

### Actual Result

```
Dio Error Status 302 
```

**Comment by AlexV525** [comment]
Please describe what exactly happened with a minimal reproducible code, and we don't handle old issues at this moment.

**Comment by wilinz** [comment]
> Please describe what exactly happened with a minimal reproducible code, and we don't handle old issues at this moment.

ok

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/221346603-8ffd61d0-def4-4772-8a3c-787636b2270a.png)
