### ISSUE TITLE
Can `LogInterceptor.onResponse` use isolate ?

### ISSUE THREAD

**Issue by EArminjon** [cfug/dio#1699]
### Request Statement

On debug mode, Dio use onResponse to print data when flutter receive some network response. When network response are HEAVY and as onResponse print synchronously, app is sometimes stucked or slowed hard.

Is it possible to have a feature like this ?

### Solution Brainstorm

Isolate, compute or async debug print.

On my app I did that : 
```dart
class IsolateLogger {
  void Function(Object object) logPrint = print;

  static void logResponse(Response<dynamic> response) =>
      IsolateLogger()._printResponse(response);

  void _printResponse(Response<dynamic> response) {
    logPrint('*** Response ***');
    _printKV('uri', response.requestOptions.uri);

    _printKV('statusCode', response.statusCode);
    if (response.isRedirect == true) {
      _printKV('redirect', response.realUri);
    }

    logPrint('headers:');
    response.headers.forEach(
      (String key, List<String> v) => _printKV(' $key', v.join('\r\n\t')),
    );

    logPrint('Response Text:');
    _printAll(response.toString());

    logPrint('');
  }

  void _printKV(String key, Object? v) {
    logPrint('$key: $v');
  }

  void _printAll(dynamic msg) {
    msg.toString().split('\n').forEach(logPrint);
  }
}

class CustomInterceptors extends Interceptor {
  @override
  void onResponse(
    Response<dynamic> response,
    ResponseInterceptorHandler handler,
  ) {
    compute(IsolateLogger.logResponse, response);
    return handler.next(response);
  }
}
```

```dart
 final Dio dio = Dio();
 dio.interceptors.add(CustomInterceptors());
```

**Comment by AlexV525** [comment]
We don't print things generally until you explicitly add an interceptor AFAIK. Can you identify which part of the source code is affecting your performance?

**Comment by EArminjon** [comment]
> We don't print things generally until you explicitly add an interceptor AFAIK. Can you identify which part of the source code is affecting your performance?

Performance drop when app receive a big body response when add this interceptor from Dio : LogInterceptor.

**Comment by AlexV525** [comment]
> Performance drop when app receive a big body response when add this interceptor from Dio : LogInterceptor.

This is more accurate. :) Please do the same indication next time.

**Comment by AlexV525** [comment]
As it turns out using the compute didn't gain too much performance improvement as this point. Also we're unlikely to take more care about the debug mode. Closing as won't fix.
