### ISSUE TITLE
Handshake errors aren't propagated to the user

### ISSUE THREAD

**Issue by JAOOOOO** [cfug/dio#1701]
### Package

dio

### Version

5.0.1

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-EG)
    • Flutter version 3.7.5 on channel stable at /Users/jao/fvm/versions/3.7.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jao/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Vivaldi.app/Contents/MacOS/Vivaldi

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 12 (mobile)          • 588BE730-A4EA-48C0-A33A-BF95A5AC52DC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Vivaldi 5.7.2921.60

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Dart Version

2.19.2

### Steps to Reproduce

I'm developing a networking service based on dio, It works well for IOS but Android all requests fail without any clear reason what's happening. 
Those are screenshots from flutter dev tool network stuff
![Screenshot 2023-03-01 at 3 23 01 AM](https://user-images.githubusercontent.com/29809879/222022619-f6928d5f-662f-442c-9fc7-524f8bf30cfa.png)

![Screenshot 2023-03-01 at 3 23 12 AM](https://user-images.githubusercontent.com/29809879/222022643-e6a6cdc1-266f-4bb9-a53a-5f6b13f9072f.png)

my code to initialize dio is as follows:

`    final options = BaseOptions(baseUrl: _baseUrl);

    final dio = Dio(options);
    dio.interceptors.add(_clientIdInterceptor);
    dio.interceptors.add(
      PrettyDioLogger(
        requestHeader: true,
        requestBody: true,
        responseHeader: true,
      ),
    );
    dio.interceptors.addAll(interceptors);
`

and I have the INTERNET permission in my manifest. what can be happening!

### Expected Result

The network calls work, get some response whatever

### Actual Result

![Screenshot 2023-03-01 at 3 23 01 AM](https://user-images.githubusercontent.com/29809879/222023060-bda76055-4cfa-4ee2-aede-8c22e1599b87.png)

Dio throws an unknown error with null message.

**Comment by AlexV525** [comment]
Can you share a reproducible link or example so we can identity the root cause?

**Comment by ueman** [comment]
@JAOOOOO Are there any updates?

**Comment by JAOOOOO** [comment]
Hello, sorry I missed the first reply. 
Yes I've found the problem it changes the issue a bit but still it's an issue. 
I downgraded to version `4.0.6` and applied the same request. and got a handshakre error. turned out that my server was using an expired authority signature. 

The problem is that v `5.0.1` doesn't report that error.

**Comment by AlexV525** [comment]
Using the latest dio produces the same uncaught exception with `HandshakeException` and wrapped `DioError`. 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/15884415/225671920-597a75bc-cfdd-4dbf-9250-097eb51190f9.png">
