### ISSUE TITLE
Dio throws wrong error type

### ISSUE THREAD

**Issue by timnew** [cfug/dio#1703]
### Package

dio

### Version

5.0.1

### Output of `flutter doctor -v`

```shell
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.0.1 22A400 darwin-x64, locale en-AU)
    • Flutter version 3.7.5 on channel stable at /Users/timnew/Workspace/flutter_sdks/production
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/timnew/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 8B1B6C6A-211B-431E-9BD3-7EEBF6D33029 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dart Version

2.19.2

### Steps to Reproduce

1. Calling API, which is expected to return JSON when succeeded
2. API returns 403 due to token issue, which `content-type` as `text/html` instead of `application/json` (Due to WAF or so)
3. Expected to have `DioError[badResponse]` but `got DioError[unknown]`

### Expected Result

Dio throws `DioError[badResponse]`

### Actual Result

Dio throws `DioErro[unkown]`
```
flutter: Error: DioError [unknown]: null
Error: FormatException: Unexpected character (at character 1)
error code: 1020
^
flutter: Stack:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      _decodeJson
#8      SyncTransformer.transformResponse
sync_transformer.dart:123
<asynchronous suspension>
#9      DioMixin._dispatchRequest
dio_mixin.dart:567
<asynchronous suspension>
```

**Comment by timnew** [comment]
The issue is caused because `Dio` trys to parse body as json regardless its `content-type` in response header.

The issue doesn't occur in Dio 4.x, only starts in 5.0

**Comment by timnew** [comment]
Issue caused by https://github.com/cfug/dio/blob/42b7eb838a3e6e73fdb93478b2992e0f36eba39b/dio/lib/src/dio_mixin.dart#L558-L571

Not sure how `receiveDataWhenStatusError` is set to true, even though I'm sure didn't manually doing that.

`forceConvert` enforced the dio override the server content-type when parsing the body, which doesn't make anysense

**Comment by kaankoken** [comment]
I am getting the same error when I assigned `content-type: application/json; charset=utf-8`

**Comment by timnew** [comment]
As I don't need the body for error response, so I'm kind of workaround the issue by manually set `receiveDataWhenStatusError` to `false` in `baseOptions`, which is set to `true` by default.

But I guess this would still be an issue for those who need error response.

**Comment by timnew** [comment]
Not sure what `4.x` behaviour was, but I tried to add an kill switch in options to avoid this `forceConvert` behaviour, which I don't run into error here any more. 
But I run into an assertion error later that dio assert the `response.data` is the type `T`. As if the incoming content-type is `text/html`, so I got `string`, which fails the assertion.
Due to the complexity, I found the easiest solution for this is to set `receiveDataWhenStatusError` to `false`.

**Comment by vohoangtuit** [comment]
set dio options:
dio.options.contentType = Headers.formUrlEncodedContentType;
working for me

**Comment by AlexV525** [comment]
cc @ipcjs. Can you help to identify if this is a regression that has been invented since #1490?

**Comment by AlexV525** [comment]
I haven't added tests yet but would like to know if #1711 solves the issue.

**Comment by ipcjs** [comment]
In version 4.x, `forceConvert` has never worked due to implementation issues.
I fixed it by https://github.com/cfug/dio/pull/1490
