### ISSUE TITLE
Combine Response `Encoder/Decoder` with `Transformer` or improve them to allow asynchronized method 

### ISSUE THREAD

**Issue by huafsud** [cfug/dio#1709]
### Request Statement

因为 这个`dio.options.responseDecoder` 地方处理`response` 的编码的方法 , 有局限性
比如:

这个地方 根据`content-type` 来判断 `UTF-8 `或者`gbk` 都能很好的进行解码 并返回

但是, 
很多接口,网站都没设置`content-type` 的编码,并不清楚返回的内容是什么编码的,  导致,需要手动判断下是否是gbk 或者是其他编码

这时候,就要引用第三方库来判断,  例如 `flutter_charset_detector`

但是第三方库 ` await CharsetDetector.autoDecode(bytes)`  是异步方法, 
这时候, `dio.options.responseDecoder `就指定不上, 很尴尬.

也有其他办法解决,
比如, 获得`response bytes data` 后再传递到` flutter_charset_detector`里面, 再判断编码,再转换处理, 但是这个太麻烦了, 而且破坏了ResponseType 的自动设置,
 
其实,就是要在`responseDecoder `的地方,判断`GBK `编码, 但是判断`GBK`编码要异步 , 然后走不下去了.

大佬们~~~    有更好更优雅的解决办法吗?   求指点指点 
  
The method of handling response encoding in `dio.options.responseDecoder` has limitations. For example, it can decode `UTF-8` or `GBK `based on the `content-type `and return the decoded content. However, many APIs or websites don't specify the encoding in the` content-type `header, making it unclear what encoding the returned content is in. This requires manual detection to determine whether it's `GBK` or some other encoding.

To address this issue, a third-party library such as` flutter_charset_detector` can be used to detect the encoding. However, the asynchronous method await `CharsetDetector.autoDecode(bytes) `creates a challenge in specifying `dio.options.responseDecoder.`

Other solutions are possible, such as obtaining the response bytes data and passing it to `flutter_charset_detector `for encoding detection and conversion, but this approach is cumbersome and can disrupt the automatic setting of the response type.

Ultimately, the challenge is to asynchronously determine the encoding for `GBK` at the `responseDecoder` level, and this creates an impasse.

Do any experts have a better, more elegant solution? Any guidance would be appreciated.

**Comment by AlexV525** [comment]
Use `Transformer` should resolve your request in this case.
cc @ueman How would you evaluate the necessarity to keep the decoder and the transformer together?

**Comment by ueman** [comment]
I don't think we necessarily have to keep them together. I feel like we could make the responseDecoder and requestEncoder support async operations, too, by supporting `FutureOr` as a return type.

Maybe we should also combine the transformer, de/encoder methods of the transformer and the responseDecoder and requestEncoder into one class. They all seem to somehow solve the same or at least similar problems. That's something for the next major version though.

**Comment by ueman** [comment]
I did take a look at this today. Here are my preliminary results:

If we change the signature of `Transformer.transformRequest()` from `Future<String> transformRequest(RequestOptions options);` to `Future<List<int>> transformRequest(RequestOptions options);` we can get rid of the `RequestEncoder` by moving its functionality into the transformer. It's pretty much the same change for the request decoding.

I'll try to play around with it for a bit.
