### ISSUE TITLE
Automatic redirection does not trigger the interceptor, causing the cookieJar interceptor to not work properly

### ISSUE THREAD

**Issue by wilinz** [cfug/dio#1715]
### Package

dio, cookie_manager

### Version

2.1.1

### Steps to Reproduce
```dart

final dio = Dio();
final dir = await getApplicationSupportDirectory();
final cookieJar = PersistCookieJar(storage: FileStorage(join(dir.path, "cookies")));
dio.interceptors.add(CookieManager(cookieJar));
dio.get("http://site1") ; // This is a 302 redirect url. The redirected site2 url will return the set-cookie response header
```

### Expected Result

The cookie will be saved to site2

### Actual Result

The cookie is saved to the original url, ie site1, resulting in no cookie being carried in subsequent requests.
So I checked the source code cookie_mgr.dart, Should response.requestOptions.uri be changed to response.realUri?
```dart
  Future<void> _saveCookies(Response response) async {
    final setCookies = response.headers[HttpHeaders.setCookieHeader];

    if (setCookies != null) {
      final cookies = setCookies
          .map((str) => str.split(_setCookieReg))
          .expand((element) => element);
      await cookieJar.saveFromResponse(
        response.requestOptions.uri, // Should this be changed to response.realUri ?
        cookies.map((str) => Cookie.fromSetCookieValue(str)).toList(),
      );
    }
  }
```

**Comment by wilinz** [comment]
This seems to be caused by the fact that the interceptor cannot intercept the redirection. Is this a BUG?

**Comment by ueman** [comment]
This is not a bug. Redirects don‘t trigger interceptors since redirects are handled by the underlying APIs dio is making use of.

We should document this probably better since I feel like I’ve seen this question popular multiple times.

**Comment by AlexV525** [comment]
The inspector is working as intended, but we need to evaluate if the cookie manager is behaving normally.

**Comment by CaiJingLong** [comment]
> This is not a bug. Redirects don‘t trigger interceptors since redirects are handled by the underlying APIs dio is making use of.
> 
> We should document this probably better since I feel like I’ve seen this question popular multiple times.

So, should `dio` handle redirection instead of handing it to the underlying api?

**Comment by ueman** [comment]
> So, should `dio` handle redirection instead of handing it to the underlying api?

While it seems to be possible, I don't think it should, since that creates a lot of complexity. What we could offer is to allow the user to handle redirects himself.

**Comment by wilinz** [comment]
My temporary solution is
```dart
      dio.setFollowRedirects(false);
      dio.interceptors.add(RedirectInterceptor(dio2));
```
```dart
extension DioExt on Dio {
  Dio setFollowRedirects(bool followRedirects) {
    options.followRedirects = followRedirects;
    if (followRedirects) {
      options.validateStatus =
          (int? status) => status != null && status >= 200 && status < 300;
    } else {
      options.validateStatus =
          (int? status) => status != null && status >= 200 && status < 400;
    }
    return this;
  }
}
```
```dart
class RedirectInterceptor extends Interceptor {
  final Dio dio;

  RedirectInterceptor(this.dio);

  @override
  Future<void> onResponse(
      Response response, ResponseInterceptorHandler handler) async {
    if (_isRedirect(response.statusCode ?? 0)) {
      final location = response.headers.value('location');
      if (location == null) throw Exception("location is null");
      final requestOptions = response.requestOptions;
      final rawUri = requestOptions.uri.toString();

      final redirectResponse = await dio.get(
        parseHttpLocation(rawUri, location),
        options: Options(
          sendTimeout: requestOptions.sendTimeout,
          receiveTimeout: requestOptions.receiveTimeout,
          extra: requestOptions.extra,
          headers: requestOptions.headers,
          responseType: requestOptions.responseType,
          contentType: requestOptions.contentType,
          validateStatus: requestOptions.validateStatus,
          receiveDataWhenStatusError: requestOptions.receiveDataWhenStatusError,
          followRedirects: requestOptions.followRedirects,
          maxRedirects: requestOptions.maxRedirects,
          persistentConnection: requestOptions.persistentConnection,
          requestEncoder: requestOptions.requestEncoder,
          responseDecoder: requestOptions.responseDecoder,
          listFormat: requestOptions.listFormat,
        ),
      );
      return handler.next(redirectResponse);
    }
    return handler.next(response);
  }

  bool _isRedirect(int statusCode) {
    return statusCode == 301 ||
        statusCode == 302 ||
        statusCode == 303 ||
        statusCode == 307 ||
        statusCode == 308;
  }
}
```

**Comment by AlexV525** [comment]
IMO this does not related to the mechanism of interceptors, but related to the mentioned `response.realUri`.

**Comment by CaiJingLong** [comment]
> While it seems to be possible, I don't think it should, since that creates a lot of complexity. What we could offer is to allow the user to handle redirects himself.

But cookieJar should work "out of the box".

**Comment by wilinz** [comment]
I've published a new Dart package to address this issue. You can check out the [dio_redirect_interceptor](https://pub.dev/packages/dio_redirect_interceptor) package, which provides enhanced control over HTTP redirects in Dio, including custom logic for handling redirects.
