### ISSUE TITLE
Curly braces {} turn into %7B and %7D

### ISSUE THREAD

**Issue by HornyPony** [cfug/dio#1742]
### Request Statement

Please help me how I can solve this problem. I have to work with just such a request, I can't ask to change it. Is it possible to avoid changing the url and send it exactly as I write it? I have a request containing '/GetStepResult?runParams={pipelineId:251251', where { before pipelineId changes to %7B when sending, which is why the request works uncorrected

Any workarounds pleeease

Code:
 final response = await _dio.get(
      'http://site/Pipeline/GetStepResult?runParams={PipelineId:..}',
      options: Options(
      headers: {
        "Content-Type": 'application/json',
      },
    ),
);

**Comment by AlexV525** [comment]
@HornyPony Infra and blank issues are only available for moderators. You're apperantly using the wrong issue template.

> Infra 和空白 issue 仅供管理人员使用，请选择其他 issue 模板创建 issue。
