### ISSUE TITLE
"Content-Length" header is not working on put request.

### ISSUE THREAD

**Issue by GustavoHruschka** [cfug/dio#1746]
### Package

dio

### Version

5.0.2

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 22.04.1 LTS 5.19.0-35-generic, locale pt_BR.UTF-8)
    • Flutter version 3.7.7 on channel stable at /home/gustavo/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/gustavo/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio-2021.3.1.17/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### Dart Version

2.19.4

### Steps to Reproduce

1. Get an image file using Flutter's [image picker](https://pub.dev/packages/image_picker) and convert it to file bytes (`UInt8List` type)
2. Try to upload the file via a put request. I'm trying to upload it to an AWS pre-signed url, but I don't think the target of the request should make a difference here. Just to clarify, `params.signedUrl` is the url, of type `String`; and `params.fileBytes` is the file I got on step 1 converted to bytes, of type `UInt8List`. My code is like this:
```
      final Uri uri = Uri.parse(params.signedUrl);
      final Dio dio = Dio();

      FormData formData = FormData.fromMap({
        "file": MultipartFile.fromBytes(params.fileBytes),
      });

      dio.options.headers["Host"] = uri.host;
      dio.options.headers[Headers.contentLengthHeader] =
          formData.length.toString();
      dio.options.headers[Headers.acceptHeader] = "*/*";

      final response = await dio.put(
        uri.toString(),
        data: formData,
        queryParameters: uri.queryParameters,
      );

      inspect(response);
```

### Expected Result

The expected result was a successful request, but I got a network error. I tested a lot of different parameters on [Postman](https://www.postman.com/) discovered that AWS demands the "Content-Length" header to be included.
When analysing the request options from the `inspect(response)` output, I expected to see the header "Content-Length" included on the request, because I explicitly set it on my code:
```
      dio.options.headers[Headers.contentLengthHeader] =
          formData.length.toString();
```

### Actual Result

When analysing the output of the `inspect(response)` line, we can see that the headers do not include "Content-Length":
![image](https://user-images.githubusercontent.com/69220882/225915757-a652bbfd-9bd3-4d10-b478-501f98a18af4.png)
Text of the output: `_headers:
CustomHashMap<String, dynamic> ({accept: */*, content-type: multipart/form-data; boundary=--dio-boundary-2639088881})`

I think this is probably a bug, as I defined the "Content-Length" header explicitly and it was not on my request.

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/226075847-00c62651-af78-4a12-b3f7-8f9dee395421.png)
![image](https://user-images.githubusercontent.com/15884415/226075860-5541386c-6797-45f4-8563-0398ac49ce01.png)
![image](https://user-images.githubusercontent.com/15884415/226075871-aea698ee-8a1f-4593-a056-86c656bf8edd.png)

**Comment by wh120** [comment]
same issue
