### ISSUE TITLE
dio.options.headers with CORS doesn't work with Flutter web

### ISSUE THREAD

**Issue by Shuo-Li** [cfug/dio#1750]
### Package

dio

### Version

5.0.1

### Dart Version

2.19.3

### Steps to Reproduce

Response response =
        await dio.get('localhost:3000/api/dict/$word',
            options: Options(
                headers: {
              // 'Authorization': 'Bearer $accessToken',
              "Access-Control-Allow-Origin": "*",
            }),
            cancelToken: cancelToken);

### Expected Result

After setting Options.headers (any header), the dio.get() request works fine with Android emulator, but doesn't work at all with Flutter Web (Chrome)

### Actual Result

When using with Flutter web and setting any Options.headers, I keep getting DioError[conneciton error]: The XMLHttpRequest onError callback was called ...... My local server doesn't receive the get request from Dio client

However, without setting any Options.headers, dio.get and dio.post work perfectly on both Flutter web and Android emulator.

I tried this on both Windows and MacOS, I got the same results on both operating systems.

![image](https://user-images.githubusercontent.com/6397910/226418864-86cfa6ae-120b-467c-8889-f7da3e555d23.png)

**Comment by AlexV525** [comment]
We have many tests that run both on VM and Chrome. They don't seem to complained before. Please provide a minimal reproducible code.

**Comment by Shuo-Li** [comment]
Thanks for your quick reply! Upon further investigation, I realized this is another Browser Preflight issue.

I knew when making a dio.post() request, Chrome browser would make a preflight request first. What I didn't realize was when adding a header to dio.get(), Chrome would also make a preflight request to ask the server if the server is willing to accept the header.

Of course, if we make a dio.get() request with headers on Android or IOS, there's no preflight request at all so this issue doesn't exist.

I got tripped up on this one. I spent a couple of days working on it and just couldn't figure out why adding a header worked on Android/IOS but not on Flutter web. Now I know why.

The way I solved this was to add the following to the response header on my golang web server:  headers.Add("Access-Control-Allow-Headers", "Content-Type, Authorization, X-MyHeader")     (X-MyHeader is the header I added to dio.get() request). 

I googled "Flutter web Dio preflight (or CORS)" and I saw quite a few people got tripped up by this. Perhaps we should add a small section to the Dio document to talk about "Flutter web Dio Preflight"? If you think it helps to have this section in the document, I can write it up. Let me know...

**Comment by AlexV525** [comment]
Good to know. Any improvements are always welcomed!

**Comment by Shuo-Li** [comment]
I've just added the following section to the dio README.md and merged the pull request with the main branch. If you're ok with what I added, I'll add the same in Chinese to the Chinese version of README.md. 

## Flutter Web

When using Dio with Flutter Web, be aware of Web Browser CORS Pre-flight Requests. You won't encounter this on mobile platforms like Android/IOS. However, Pre-flight requests always happen with Flutter web when one makes a REST Api call such as dio.post() or dio.get() with headers.

The way to handle browser pre-flight requests is to enable CORS on your web server. Most web server frameworks or libraries provide CORS middleware to handle browser pre-flight requests.

**Comment by AlexV525** [comment]
> I've just added the following section to the dio README.md and merged the pull request with the main branch. If you're ok with what I added, I'll add the same in Chinese to the Chinese version of README.md.

Looks good for now, though I suggest the title can be "CORS on Flutter Web".

**Comment by Shuo-Li** [comment]
Good suggestions! I've made the change accordingly.

Here's the pull request on my forked branch of Dio:  https://github.com/Shuo-Li/dio/pull/2

I've been doing software development for many years. However, I hadn't done much Open Source stuff before so I'm kind of a noob as far as github fork, pull request, etc. are concerned

**Comment by AlexV525** [comment]
You'll need to submit the PR again targeting the origin branch. Just try a few times and you'll get the point. :)

**Comment by Shuo-Li** [comment]
Got it. Just submitted the PR to the origin branch
