### ISSUE TITLE
The result that FormData.fromMap builded on 5.0.3 is different from 3.0.6.

### ISSUE THREAD

**Issue by chris-choy** [cfug/dio#1758]
### Package

dio

### Version

5.0.3

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.6 on channel stable at /Users/jiayou/fvm/versions/3.3.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 months ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

There is a different result which from FormData.fromMap() between Dio(5.0.3) and Dio(3.0.9).  The result I expected is "spec[]" : "6", but it was "spec": "6" on 5.0.3.
1. Is there any setting that I can get the the result that the same as in 3.0.9? 
2. I have noticed that ListFormat.multiCompatible example is the result style I want. But I had put it in the options and nothing new happened.
```

### Dart Version

2.18.2

### Steps to Reproduce

```dart
Future<void> main(List<String> arguments) async {

  final data = {
    'key1': 'value1',
    'spec': [6],
  };

  Dio dio = Dio();

  await dio.post<Map<String, dynamic>>(
    'https://postman-echo.com/post',
    data: data,
    options: Options(
      contentType: Headers.formUrlEncodedContentType,
      method: 'post',
    )
  ).then((onValue) {
    print('===<Response>---\n$onValue');
  });
  
}
```
Run and see the result.

### Expected Result

```
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "key1": "value1",
        "spec[]": "6"
    },
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-641d62d2-581890fc6c16023f47191f33",
        "content-length": "24",
        "user-agent": "Dart/2.18 (dart:io)",
        "content-type": "application/x-www-form-urlencoded",
        "accept-encoding": "gzip"
    },
    "json": {
        "key1": "value1",
        "spec[]": "6"
    },
    "url": "https://postman-echo.com/post"
}
```

### Actual Result
```
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "key1": "value1",
        "spec": "6"
    },
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-641d62e6-6d4eb8246a594a63138a64be",
        "content-length": "18",
        "user-agent": "Dart/2.18 (dart:io)",
        "content-type": "application/x-www-form-urlencoded",
        "accept-encoding": "gzip"
    },
    "json": {
        "key1": "value1",
        "spec": "6"
    },
    "url": "https://postman-echo.com/post"
}
```

The  spec key/value should be "spec[]" : "6", not  "spec": "6"

**Comment by AlexV525** [comment]
cc @kuhnroyal

**Comment by chris-choy** [comment]
Hello, I had tried to run this code in the Dio 5.1.0, but the probleme seems to be still exist. 
Are there any wrong steps  in this code that not return the result I expected? 
``` dart
Future<void> main(List<String> arguments) async {

  final data = {
    'key1': 'value1',
    'spec': [6],
  };

  Dio dio = Dio();

  await dio.post<Map<String, dynamic>>(
    'https://postman-echo.com/post',
    data: data,
    options: Options(
      contentType: Headers.formUrlEncodedContentType,
      method: 'post',
      listFormat: ListFormat.multiCompatible
    )
  ).then((onValue) {
    print('===<Response>---\n$onValue');
  });

}
```
The result return is
 
``` json
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "key1": "value1",
        "spec": "6"
    },
    "headers": {
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "host": "postman-echo.com",
        "x-amzn-trace-id": "Root=1-642241ed-7dc3857a112a771f44173ca0",
        "content-length": "18",
        "user-agent": "Dart/2.18 (dart:io)",
        "content-type": "application/x-www-form-urlencoded",
        "accept-encoding": "gzip"
    },
    "json": {
        "key1": "value1",
        "spec": "6"
    },
    "url": "https://postman-echo.com/post"
}
```
I want the correct result about spec is "spec[]": "6", not the "spec": "6".
Can you help me check the code? Thank you very much. @AlexV525 @kuhnroyal

**Comment by AlexV525** [comment]
cc @kuhnroyal

**Comment by kuhnroyal** [comment]
Yea this has nothing to do with the recent changes. This is wrong since 4.0.x

**Comment by kuhnroyal** [comment]
Please test with the linked PR.

**Comment by chris-choy** [comment]
> Please test with the linked PR.

Thanks for your help at first.
But I modified my code in Dio5.1.0 according to your commit changes. Then, run the code below and the result was still not my expect result. Is this data I input not in a right way or something else ? Thanks a lot.

``` dart
Future<void> main(List<String> arguments) async {

  final data = {
    'key1': 'value1',
    'spec': [6],
  };

  Dio dio = Dio();

  await dio.post<Map<String, dynamic>>(
    'https://postman-echo.com/post',
    data: data,
    options: Options(
      contentType: Headers.formUrlEncodedContentType,
      method: 'post',
      listFormat: ListFormat.multiCompatible
    )
  ).then((onValue) {
    print('===<Response>---\n$onValue');
  });

}
```
I really want the result contain "spec[]" : "6" , because my project's Dio is from 3.0.6 to 5.x.x, and the server can't resolve the data from my client-side that the result is "spec":"6".

**Comment by AlexV525** [comment]
> Thanks for your help at first. But I modified my code in Dio5.1.0 according to your commit changes. Then, run the code below and the result was still not my expect result. Is this data I input not in a right way or something else ? Thanks a lot.

Please use the PR's latest commit ref as the dependency rather than copying codes so we can identify the issue better.

**Comment by chris-choy** [comment]
> > Thanks for your help at first. But I modified my code in Dio5.1.0 according to your commit changes. Then, run the code below and the result was still not my expect result. Is this data I input not in a right way or something else ? Thanks a lot.
> 
> Please use the PR's latest commit ref as the dependency rather than copying codes so we can identify the issue better.

Thanks for replying. 
I'm using the PR's lastest commit ref as the dependency now. I tested it again and found the problem is that the listformat setting in Options not came into effect.
### Correct Result
It can bring a correct result if set ``ListFormat.multiCompatible`` in ``FormData``.
```dart
test('InFormData', () async {

    final data = {
      'key1': 'value1',
      'spec': [6],
    };

    final FormData formData = FormData.fromMap(
      data,
      ListFormat.multiCompatible
    );

    await Dio().post<Map<String, dynamic>>(
        'https://postman-echo.com/post',
        data: formData,
        options: Options(
          contentType: Headers.formUrlEncodedContentType,
          method: 'post',
          listFormat: ListFormat.multiCompatible
        )
    ).then((result) {
      print('===<Response>---\n$result');
      expect(result.toString(), contains('spec[]'));
    });

  });
```
### Uncorrect Result
It will bring a uncorrect result if set  ``ListFormat.multiCompatible`` in ``Option``. So I don't think the listview option setting worked.
```dart
test('InOption', () async {

    final data = {
      'key1': 'value1',
      'spec': [6],
    };

    await Dio().post<Map<String, dynamic>>(
      'https://postman-echo.com/post',
      data: data,
      options: Options(
        contentType: Headers.formUrlEncodedContentType,
        method: 'post',
        listFormat: ListFormat.multiCompatible
      )
    ).then((result) {
      print('===<Response>---\n$result');
      expect(result.toString(), contains('spec[]'));
    });

  });
```

**Comment by kuhnroyal** [comment]
Thanks for the reproducible sample. I fixed it and updated the PR. Please test again if that works for you.

**Comment by chris-choy** [comment]
> Thanks for the reproducible sample. I fixed it and updated the PR. Please test again if that works for you.

Thanks a lot . The problem seems to have been solved.

**Comment by kadarpik** [comment]
The problem was even harder, in my case Dio post request always hanged when the form had special symbols needed to be encoded. I got rid of Dio, it was too complicated for my situation and fallback to simple http.  Hanging was really hard to detect, finally did wireshark.

**Comment by AlexV525** [comment]
> The problem was even harder, in my case Dio post request always hanged when the form had special symbols needed to be encoded.

It would be super helpful if you can share simple special symbols with a minimal code example that can reproduce your issue, rather than digging in your production code that might makes investigation harder.
