### ISSUE TITLE
cookie_manager does not save cookies from redirect responses for origin domain in version 2.1.3+

### ISSUE THREAD

**Issue by Vovcharaa** [cfug/dio#1761]
### Package

cookie_manager

### Version

2.1.3

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-UA)
    • Flutter version 3.7.8 on channel stable at /Users/vovcharaa/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (5 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/vovcharaa/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Dart Version

2.19.5

### Steps to Reproduce

After https://github.com/cfug/dio/pull/1734 was merged in version [2.1.3](https://github.com/cfug/dio/releases/tag/cookie_manager_v2.1.3), cookies are not saved in jar for origin domain but only for domain in `location` header. Before that everything was okay and cookies were saved (only) for origin domain.
In my use case, I do not follow redirect but use `location` in other place. But my backend returns `state` cookie and now I just lose it every time because of this change.

My usage example:
1. Make request with `followRedirects: false` to my endpoint that returns redirect to auth server and `Set-Cookie` with state.
2. Catch `location` url and open it in browser for auth.
3. Catch callback with code and get tokens from token endpoint on my backend using dio, but now its not working because `state` cookie is not in request.

Before the change mentioned above, I could do this because cookie was saved for my domain, not the auth server domain. Now its saved for auth server domain but not for my backend domain.

### Expected Result

`Set-Cookie` must not be ignored for origin domain if it is sent in redirect response.

And I also propose to implement compliance for [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) attribute.
If SameSite is set to `Strict`, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#strict) cookies MUST NOT be sent to `location` url.

### Actual Result

Cookies in redirect responses saved only for `location` domain without checking SameSite attribute and never saved for origin domain.

**Comment by AlexV525** [comment]
`SameSite` policy should be solid in https://github.com/flutterchina/cookie_jar/blame/4.0/lib/src/default_cookie_jar.dart#L73 once we upgrade the dependency to 4.0.0.
