### ISSUE TITLE
DioErrorType.unknown getting issue in some device every time 

### ISSUE THREAD

**Issue by ShirishModi8** [cfug/dio#1767]
### Package

dio

### Version

5.0.2

### Dart Version

2.19.4

### Steps to Reproduce

DioErrorType.unknown 

### Expected Result

DioErrorType.unknown

### Actual Result

DioErrorType.unknown

**Comment by ShirishModi8** [comment]
Future<String> getConfigRequested() async {
    try {
      final response = await repoApi.loadGetData(Endpoints.config);
      return json.encode(response.data);
    } on DioError catch (e) {
      final errorMessage = DioExceptions.fromDioError(e).toString();
      throw errorMessage;
    }
  }

some device getting unknow error any solution plz give

**Comment by ShirishModi8** [comment]
@AlexV525 can you give solution?

**Comment by stjfk** [comment]
same here

**Comment by AlexV525** [comment]
The given info is not helpful for investigating the issue, not even have the error itself.

**Comment by AlexV525** [comment]
Closing as above comments are neither following the issue template nor providing necessary info to investigate. Consider attaching more logs with exceptions and a minimal reproducible example.
