### ISSUE TITLE
Multipart -> Error: SocketException: Connection reset by peer (OS Error: Connection reset by peer,

### ISSUE THREAD

**Issue by michaldev** [cfug/dio#1776]
### Package

dio

### Version

5.1.0

### Problem description 

I have problem with sending files by multipart/form-data. I have tested server by "insomnia rest client" and everything is ok, but over flutter-dio not.

**Error on native device:**
Error: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = 192.168.0.89, port = 49776

**Error on web** is something like "XML Layer network problem".

I tested it both on a local server and on a remote server. Every time the same problem occurs. At the same time, Insomnia (rest client) works correctly everywhere and always. The request doesn't even reach the server. What could be the problem? I've tried attaching the files in different configurations. The last one looks like this:

```
  Future<String> addTest({required List<Uint8List> photos}) async {
    _dio.interceptors.add(PrettyDioLogger());
    _dio.interceptors.add(PrettyDioLogger(
        requestHeader: true,
        requestBody: true,
        responseBody: true,
        responseHeader: false,
        error: true,
        compact: true,
        maxWidth: 90));
    final formData = FormData();

    for (var i = 0; i < photos.length; i++) {
      formData.files
          .add(MapEntry('file$i', MultipartFile.fromBytes(photos[i])));
    }

    final req = await _dio.post('/posts',
        data: formData,
        options: Options(headers: {
          'Content-Type': 'multipart/form-data',
        }));
    return req.data["id"];
  }
```

### Expected Result

Receiving by server.

### Actual Result

Thats all logs from only 1 request.

<img width="1090" alt="Zrzut ekranu 2023-03-29 o 23 25 49" src="https://user-images.githubusercontent.com/5132385/228671400-584751dc-d4ed-4b8e-9e91-49f6311b2aa5.png">

**Comment by michaldev** [comment]
Probably problem is in gofiber (golang framework): https://github.com/gofiber/fiber/issues/1940

**Comment by AlexV525** [comment]
Closing as it seems not related to the package.
