### ISSUE TITLE
Bad file descriptor IOS 

### ISSUE THREAD

**Issue by AshotKhachatryan1995** [cfug/dio#1779]
### Package

dio

### Version

5.1.1

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2.1 22D68 darwin-x64, locale en)
    • Flutter version 3.3.10 on channel stable at /Users/admin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • SM A025U (mobile)      • R9PR80L5NML               • android-arm • Android 12 (API 31)
    • Aida’s iPhone (mobile) • 00008110-001E542601BB801E • ios         • iOS 16.3.1 20D67

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Dart Version

2.18.6

### Steps to Reproduce

on IOS.

1. Make post request. 
2. During uploading proccess lock iphone screen
3. After few seconds catch exception

It's working on debug and profile mode, but in release mode not working
Error: SocketException: Bad file descriptor(OS Error: Bad file descriptor, errno=9)

### Expected Result

Need continue uploading proccess

### Actual Result

..

**Comment by AshotKhachatryan1995** [comment]
Which information do you need?

**Comment by AshotKhachatryan1995** [comment]
``` try {
      Response response = await Dio().post(
        url.baseUrl + url.uploadUrl,
        options: Options(
            validateStatus: (_) => true,
            headers: {
              "Content-Type": "multipart/form-data",
              "name": userModel.name,
              "number": userModel.number
            }),
        onSendProgress: (int count, int total) {
          emit(SendInfoDataState(
              sendInfoModel:
                  SendInfoModel(receivedData: count, allData: total)));
        },
        data: FormData.fromMap({
          "files": files,
          "jsonMap": jsonEncode({
            "number": userModel.number,
            "name": userModel.name,
            "filesList": filesList,
          })
        }),
      );

      if (response.statusCode == 200) {
        //...
        return;
      }

      return;
    } catch (e) {
 
      throw Exception(e.toString());
    }

**Comment by knaeckeKami** [comment]
This is likely the same issue as this one in the http package : https://github.com/dart-lang/http/issues/197

**Comment by CaiJingLong** [comment]
> This is likely the same issue as this one in the http package : [dart-lang/http#197](https://github.com/dart-lang/http/issues/197)
[Apple's documentation](https://developer.apple.com/library/archive/technotes/tn2277/NaN#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION14) is mentioned in this issue.
It is stated in this document that if you want to suspend the application and perform network operations in the background, you should configure [Background Execution](https://developer.apple.com/documentation/xcode/configuring-background-execution-modes/) for your iOS app.

**Comment by AshotKhachatryan1995** [comment]
Here is one comment 
```
HttpClient client;
...
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.paused) {
     client.clearConnectionPool();  // Think of a better name.
    }
  }

is it any way to clear connection in Dio?

**Comment by AshotKhachatryan1995** [comment]
> > This is likely the same issue as this one in the http package : [dart-lang/http#197](https://github.com/dart-lang/http/issues/197)
> 
> [Apple's documentation](https://developer.apple.com/library/archive/technotes/tn2277/NaN#//apple_ref/doc/uid/DTS40010841-CH1-SUBSECTION14) is mentioned in [this issue](https://github.com/dart-lang/http/issues/197). It is stated in this document that if you want to suspend the application and perform network operations in the background, you should configure [Background Execution](https://developer.apple.com/documentation/xcode/configuring-background-execution-modes/) for your iOS app.

All configs are done but still I have some issue. I think it's not releated with IOS config

**Comment by ueman** [comment]
Does using https://github.com/cfug/dio/tree/main/plugins/native_dio_adapter solve the issue?

**Comment by knaeckeKami** [comment]
yes.

**Comment by AlexV525** [comment]
This is most likely caused by the Dart VM or by the implementation of `HttpClient`, which is out of the scope of our package currently. Please consider follow up in https://github.com/dart-lang/http/issues/197.
