### ISSUE TITLE
Supporting Brotli

### ISSUE THREAD

**Issue by fzyzcjy** [cfug/dio#1782]
### Request Statement

Hi, thanks for the package! I wonder whether Dio will support Brotli in the future? As we know, Brotli compression often perform better than Gzip, so this can help save a lot of network traffic.

Context: https://github.com/cfug/dio/issues/684

**Comment by AlexV525** [comment]
I've searched for Brotli transformers/adapters in the pub and found this: [dio_brotli_transformer](https://github.com/vycius/dio_brotli_transformer). Is it still valid or only require a few migration steps to make it work again?

**Comment by fzyzcjy** [comment]
Yes I have also seen that. My concern is that, that package depends on https://pub.dev/packages/brotli, which has not had any updates for 2 years and has unhandled possible bugs https://github.com/tiagohm/brotli/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen. Therefore, I am wondering whether CFUG or Dio has the interest to maintain/implement brotli on Dart. Anyway, this is just a small proposal :)

**Comment by ueman** [comment]
The correct approach is to fix those issues on the linked library. I don't think the maintainer team has the capacity to support it.

**Comment by amondnet** [comment]
@fzyzcjy In my experience, most of the time it works fine, but in very rare cases I have encountered the following issues. https://github.com/tiagohm/brotli/issues/3

**Comment by fzyzcjy** [comment]
@amondnet Thank you! So did you solve that or use it in production?

**Comment by AlexV525** [comment]
So in summary we don't want to expand our maintenance area to the Brotli support since the community already has one at this moment. But we are still available to help contact the author to fix issues if necessary. Before that, I would suggest you guys contact the author first and he seems to be active on GitHub recently.
