### ISSUE TITLE
Error: SocketException: Connection refused

### ISSUE THREAD

**Issue by seyhongkin** [cfug/dio#1783]
### Package

dio

### Version

5.1.0

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.7.3, on Microsoft
    Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.7.3 on channel stable at
      C:\src\flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (9 weeks ago),
      2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is
    version 10 or higher)

[√] Android toolchain - develop for Android devices
    (Android SDK version 33.0.1)
    • Android SDK at
      C:\Users\HONG_USER\AppData\Local\Android\sdk     
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android 
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe       

[√] Visual Studio - develop for Windows (Visual Studio 
    Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft      
      Visual Studio\2022\Community
    • Visual Studio Community 2022 version
      17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin can be installed from:
      
      https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart  
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.1)
    • VS Code at
      C:\Users\HONG_USER\AppData\Local\Programs\Microso
      ft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 •   
      android-x64    • Android 13 (API 33) (emulator)  
    • Windows (desktop)            • windows       •   
      windows-x64    • Microsoft Windows [Version      
      10.0.22621.1413]
    • Chrome (web)                 • chrome        •
      web-javascript • Google Chrome 111.0.5563.147    
    • Edge (web)                   • edge          •   
      web-javascript • Microsoft Edge 112.0.1722.39    

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Steps to Reproduce

import 'package:clone_social_media/constant/constant.dart';
import 'package:clone_social_media/data/model/auth/RegisterUserResModel.dart';
import 'package:either_dart/either.dart';
import 'dart:io';
import 'package:dio/dio.dart';

class AuthProvider {
  final dio = Dio();
  //register user
  Future<Either<String, RegisterUserResModel>> registerUser({
    required String name,
    required String email,
    required String password,
    required File image,
  }) async {
    try {
      final formData = FormData.fromMap({
        'name': name,
        'email': email,
        'password': password,
        'image': await MultipartFile.fromFile(image.path),
      });
      final res = await dio.post(
        "$kBaseUrl/user/register",
        data: formData,
        options: Options(
          headers: {'Accept': 'application/json'},
          followRedirects: false,
          validateStatus: (status) {
            return status! < 500;
          },
        ),
      );
      if (res.statusCode == 200) {
        return Right(RegisterUserResModel.fromJson(res.data));
      } else {
        return Left(res.data['message']);
      }
    } catch (e) {
      return Left(e.toString());
    }
  }
}

### Expected Result

{
    "user": {
        "name": "test",
        "email": "test1@gmail.com",
        "updated_at": "2023-04-11T15:13:07.000000Z",
        "created_at": "2023-04-11T15:13:07.000000Z",
        "id": 7
    },
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMGZhZWYxNzNkNmQ1YzI5ZjU4N2VhODk3NjZlZmZjODE5M2E2ZTExOTZkM2JkM2YxNmFhYTE3MDc5YTFhNzExMGQ3ZjBmZmFiYWRhM2UxZWUiLCJpYXQiOjE2ODEyMjU5ODcuNDcwNjUyLCJuYmYiOjE2ODEyMjU5ODcuNDcwNjYyLCJleHAiOjE3MTI4NDgzODcuNDU0NDI5LCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.e19MoQx4PCRcwTKvvCvuVFHRzYvDIXwqbL8OffwZFhWrkBVMlMFubDvPBWU-uO1Nsm5i9bmImyPNMlmWOchfLOpscBy1pcxCE3lZvME0lXPk3nlufQf7nox3br6dkJH2u3EFfxRspyIHn2DcAxiqPca3JDVmDxyZ3B9Nl183WRbo4mLTMl05ehwB1-zvyxuE92JEs-bPxGRCq4tUi8Isw6uDCV4mMIUEsf1K1l-uwldBBn-ae7_qvz1lJwK4eLi1xWFxPLXT2UbOhwUoQV8bQvRCew2KZZ-yNEgBuFOKuRTI8dZxSkX4ZvirlKgep6HvtrkhAufqIqOVzpVgdzKqYmb14NabYG8xGMzwi4t7lMu0SduxBQ-Ap2vCGIP4Urg82zB0LYmbwOG2l3MA-v8o5RrPemG-7fNUnSs7VY1540pzJ-pYO0zn-zeED7APKFYjW3d6g9I611jyNWbEMY-fHwkRCZZOfnwD0U-_beIUzdMe22n9arBXY6jtarJUAO4twNk1B8HXrFu_k-srMvr0N123wiXCANMEVT3eet5lsXRbVjyR9LHrQLzmBI3HwtH87awl9CS1Ghns0Q_N3eLQ99DMkyx7z3zxKFOCO8p4pk2EnYIHV_oKXQBXLhiudeu5qjt7qDJAiXeGRQL9WNoWA9ImkXKW8I6p1eFTcTNaTTA"
}

### Actual Result

I/flutter ( 5208): DioError [unknown]: null
I/flutter ( 5208): Error: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = 127.0.0.1, port = 38560
D/EGL_emulation( 5208): app_time_stats: avg=18.89ms min=5.52ms max=84.73ms count=44

**Comment by AlexV525** [comment]
Make sure you can access 127.0.0.1 from your emulator.
