### ISSUE TITLE
Ignore certificate issues

### ISSUE THREAD

**Issue by Lily1710** [cfug/dio#1785]
### Package

dio

### Version

5.1.1

### Output of `flutter doctor -v`

```shell
flutter doctor -v
```

### Dart Version

3.7.8

### Steps to Reproduce

DIO version 5.1.1, whether certificate verification can be forcibly ignored for HTTPS requests like earlier versions
Low version code:
(_dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (HttpClient client) {
      client.badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
    };
I have also learned about the code for verifying HTTPS certificates in the new version of Dio. The current situation is that we are a multi-party development project and cannot obtain others' HTTPS certificates. Therefore, I would like to ask the above question,
If you cannot use lower version code, what do you need to do to make HTTPS requests without requiring an HTTPS certificate

### Expected Result

true

### Actual Result

false

**Comment by ueman** [comment]
Please take look at the documentation here: https://github.com/cfug/dio/tree/main/dio#https-certificate-verification
