### ISSUE TITLE
get a error : "The method 'fromMap' isn't defined for the type 'FormData'. Try correcting the name to the name of an existing method, or defining a method named 'fromMap'.dartundefined_method"

### ISSUE THREAD

**Issue by boziyoung** [cfug/dio#1788]
### Package

dio

### Version

4.0.6

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.7.11, on macOS 12.3 21E230 darwin-arm64, locale zh-Hans-AL)
    • Flutter version 3.7.11 on channel stable at /Users/boziyoung/Resource/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/boziyoung/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 083D9448-C180-48B1-8926-05711FFEC8C2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

### Steps to Reproduce

i defind a FormData type parmaes , but it raised a error:
code :
`  FormData formData = FormData.fromMap({
                      "original": Se.titleController.value.text,
                      "translation": Se.translationController.value.text,
                      "notes": Se.noteController.value.text
                    });
         `

### Expected Result

formData should be right

### Actual Result

screenshot
![image](https://user-images.githubusercontent.com/50167927/232005085-6e272561-0858-4830-a3fb-4b2ecc520e8b.png)

**Comment by ueman** [comment]
Have you tried updating to the latest DIO version? On the latest DIO version form data has that method.

**Comment by boziyoung** [comment]
> Have you tried updating to the latest DIO version? On the latest DIO version form data has that method.
I'm sure it still raised this error after DIO was updated to the latest version. 
Perhaps I am not describing this problem clearly.
so i'll add more information again;

1. first i do some network encapsulations to dio:

sendApi.dart:
`import 'package:common_utils/common_utils.dart';
import 'package:dio/dio.dart';
// import 'package:flutter/material.dart';
// import 'package:fluttertoast/fluttertoast.dart';

class Request {
  // 配置 Dio 实例
  static final BaseOptions _options = BaseOptions(
    baseUrl: "http://127.0.0.1:8000",
    connectTimeout: const Duration(milliseconds: 5000),
    receiveTimeout: const Duration(milliseconds: 5000),
  );

  // 创建 Dio 实例
  static final Dio _dio = Dio(_options);

  static dynamic _request(String path,
      {String? method, dynamic data, Map<String, dynamic>? headers}) async {
    // restful 请求处理

    //初始化设置 LogUtil
    LogUtil.init(isDebug: true);
    LogUtil.v("发生的data: $data");
    try {
      Response response = await _dio.request(path,
          data: data, options: Options(method: method, headers: headers));
      // 通过对response 的status code 的结果进行判断
      if (response.statusCode == 200 ||
          response.statusCode == 201 ||
          response.statusCode == 204) {
        try {
          LogUtil.v(response.data);
          // print("request: ${response.data.toString()}");
          // 返回response的数据
          return response;
        } catch (e) {
          LogUtil.v(e);
          LogUtil.v("错误data：${response.data}");
          // 解析错误：
          // 新增 toast 提醒报错
          // Fluttertoast.showToast(
          //   msg: "解析错误",
          //   // backgroundColor: style.background,
          //   textColor: Colors.white,
          //   gravity: ToastGravity.TOP,
          //   webPosition: "center",
          // );
        }
      } else {
        if (response.statusCode != null) {
          LogUtil.v(response.statusCode);
          _handleHttpError(response.statusCode);
        }
      }
    } on DioError catch (e) {
      LogUtil.v(_dioError(e), tag: '请求异常');
      // 新增 toast 提醒报错
      // Fluttertoast.showToast(
      //   msg: _dioError(e),
      //   // backgroundColor: style.background,
      //   textColor: Colors.white,
      //   gravity: ToastGravity.TOP,
      //   webPosition: "center",
      // );
    } catch (e) {
      LogUtil.v(e);
// 新增 toast 提醒报错
      // Fluttertoast.showToast(
      //   msg: "未知异常",
      //   // backgroundColor: style.background,
      //   textColor: Colors.white,
      //   gravity: ToastGravity.TOP,
      //   webPosition: "center",
      // );
    }
  }

  // 处理 Dio 异常
  static String _dioError(DioError error) {
    switch (error.type) {
      case DioErrorType.connectionTimeout:
        return "网络连接超时，请检查网络设置";
      case DioErrorType.receiveTimeout:
        return "服务器异常，请稍后重试！";
      case DioErrorType.sendTimeout:
        return "网络连接超时，请检查网络设置";
      case DioErrorType.badResponse:
        return "服务器异常，请稍后重试！";
      case DioErrorType.cancel:
        return "请求已被取消，请重新请求";
      case DioErrorType.unknown:
        return "网络异常，请稍后重试！";
      default:
        return "Dio异常";
    }
  }

  // 处理 Http 错误码
  static void _handleHttpError(int? errorCode) {
    String message;
    switch (errorCode) {
      case 400:
        message = '请求语法错误';
        break;
      case 401:
        message = '未授权，请登录';
        break;
      case 403:
        message = '拒绝访问';
        break;
      case 404:
        message = '请求出错';
        break;
      case 408:
        message = '请求超时';
        break;
      case 500:
        message = '服务器异常';
        break;
      case 501:
        message = '服务未实现';
        break;
      case 502:
        message = '网关错误';
        break;
      case 503:
        message = '服务不可用';
        break;
      case 504:
        message = '网关超时';
        break;
      case 505:
        message = 'HTTP版本不受支持';
        break;
      default:
        message = '请求失败，错误码：$errorCode';
    }
    // 新增 toast 提醒报错
    // Fluttertoast.showToast(
    //   msg: message,
    //   // backgroundColor: style.background,
    //   textColor: Colors.white,
    //   gravity: ToastGravity.TOP,
    //   webPosition: "center",
    // );
  }

  static dynamic get(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "get", headers: headrers);
  }

  static dynamic post(
    String path, {
    String? method,
    dynamic? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "post", data: data, headers: headrers);
  }

  static dynamic delete(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "delete", data: data, headers: headrers);
  }

  static dynamic put(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "put", data: data, headers: headrers);
  }
}
`

2. second ,i do a encapsulation to all "Api" path

apiSum.dart:
`import 'package:english_test/Dio/SendApi.dart';

/**
 * 将所有的 api 接口封装在一起
*/

class Api {
  static getTestQuestion(Map data, dynamic headers) {
    return Request.post("/get_next_cloze", data: data, headrers: headers);
  }

  static getEnglishList() {
    return Request.get("/list");
  }

  static getSingleEnglish(String id) {
    return Request.get("/get_sentences/$id");
  }

  static updateSentence(Map data) {
    return Request.put("/put_sentences", data: data);
  }

  static addSentence(dynamic data) {
    return Request.post('/add_sentences', data: data);
  }
}
`
then, as you can see , i'm going to use "addSentence" function, but when i want to use use "formdata" type, it raised this error

**Comment by boziyoung** [comment]
> Have you tried updating to the latest DIO version? On the latest DIO version form data has that method.
I'm sure it still raised this error after DIO was updated to the latest version. 
Perhaps I am not describing this problem clearly.
so i'll add more information again;

1. first i do some network encapsulations to dio:

sendApi.dart:
`import 'package:common_utils/common_utils.dart';
import 'package:dio/dio.dart';
// import 'package:flutter/material.dart';
// import 'package:fluttertoast/fluttertoast.dart';

class Request {
  // 配置 Dio 实例
  static final BaseOptions _options = BaseOptions(
    baseUrl: "http://127.0.0.1:8000",
    connectTimeout: const Duration(milliseconds: 5000),
    receiveTimeout: const Duration(milliseconds: 5000),
  );

  // 创建 Dio 实例
  static final Dio _dio = Dio(_options);

  static dynamic _request(String path,
      {String? method, dynamic data, Map<String, dynamic>? headers}) async {
    // restful 请求处理

    //初始化设置 LogUtil
    LogUtil.init(isDebug: true);
    LogUtil.v("发生的data: $data");
    try {
      Response response = await _dio.request(path,
          data: data, options: Options(method: method, headers: headers));
      // 通过对response 的status code 的结果进行判断
      if (response.statusCode == 200 ||
          response.statusCode == 201 ||
          response.statusCode == 204) {
        try {
          LogUtil.v(response.data);
          // print("request: ${response.data.toString()}");
          // 返回response的数据
          return response;
        } catch (e) {
          LogUtil.v(e);
          LogUtil.v("错误data：${response.data}");
          // 解析错误：
          // 新增 toast 提醒报错
          // Fluttertoast.showToast(
          //   msg: "解析错误",
          //   // backgroundColor: style.background,
          //   textColor: Colors.white,
          //   gravity: ToastGravity.TOP,
          //   webPosition: "center",
          // );
        }
      } else {
        if (response.statusCode != null) {
          LogUtil.v(response.statusCode);
          _handleHttpError(response.statusCode);
        }
      }
    } on DioError catch (e) {
      LogUtil.v(_dioError(e), tag: '请求异常');
      // 新增 toast 提醒报错
      // Fluttertoast.showToast(
      //   msg: _dioError(e),
      //   // backgroundColor: style.background,
      //   textColor: Colors.white,
      //   gravity: ToastGravity.TOP,
      //   webPosition: "center",
      // );
    } catch (e) {
      LogUtil.v(e);
// 新增 toast 提醒报错
      // Fluttertoast.showToast(
      //   msg: "未知异常",
      //   // backgroundColor: style.background,
      //   textColor: Colors.white,
      //   gravity: ToastGravity.TOP,
      //   webPosition: "center",
      // );
    }
  }

  // 处理 Dio 异常
  static String _dioError(DioError error) {
    switch (error.type) {
      case DioErrorType.connectionTimeout:
        return "网络连接超时，请检查网络设置";
      case DioErrorType.receiveTimeout:
        return "服务器异常，请稍后重试！";
      case DioErrorType.sendTimeout:
        return "网络连接超时，请检查网络设置";
      case DioErrorType.badResponse:
        return "服务器异常，请稍后重试！";
      case DioErrorType.cancel:
        return "请求已被取消，请重新请求";
      case DioErrorType.unknown:
        return "网络异常，请稍后重试！";
      default:
        return "Dio异常";
    }
  }

  // 处理 Http 错误码
  static void _handleHttpError(int? errorCode) {
    String message;
    switch (errorCode) {
      case 400:
        message = '请求语法错误';
        break;
      case 401:
        message = '未授权，请登录';
        break;
      case 403:
        message = '拒绝访问';
        break;
      case 404:
        message = '请求出错';
        break;
      case 408:
        message = '请求超时';
        break;
      case 500:
        message = '服务器异常';
        break;
      case 501:
        message = '服务未实现';
        break;
      case 502:
        message = '网关错误';
        break;
      case 503:
        message = '服务不可用';
        break;
      case 504:
        message = '网关超时';
        break;
      case 505:
        message = 'HTTP版本不受支持';
        break;
      default:
        message = '请求失败，错误码：$errorCode';
    }
    // 新增 toast 提醒报错
    // Fluttertoast.showToast(
    //   msg: message,
    //   // backgroundColor: style.background,
    //   textColor: Colors.white,
    //   gravity: ToastGravity.TOP,
    //   webPosition: "center",
    // );
  }

  static dynamic get(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "get", headers: headrers);
  }

  static dynamic post(
    String path, {
    String? method,
    dynamic? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "post", data: data, headers: headrers);
  }

  static dynamic delete(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "delete", data: data, headers: headrers);
  }

  static dynamic put(
    String path, {
    String? method,
    Map? data,
    Map<String, dynamic>? headrers,
  }) {
    return _request(path, method: "put", data: data, headers: headrers);
  }
}
`

2. second ,i do a encapsulation to all "Api" path

apiSum.dart:
`import 'package:english_test/Dio/SendApi.dart';

/**
 * 将所有的 api 接口封装在一起
*/

class Api {
  static getTestQuestion(Map data, dynamic headers) {
    return Request.post("/get_next_cloze", data: data, headrers: headers);
  }

  static getEnglishList() {
    return Request.get("/list");
  }

  static getSingleEnglish(String id) {
    return Request.get("/get_sentences/$id");
  }

  static updateSentence(Map data) {
    return Request.put("/put_sentences", data: data);
  }

  static addSentence(dynamic data) {
    return Request.post('/add_sentences', data: data);
  }
}
`
then, as you can see , i'm going to use "addSentence" function, but when i want to use use "formdata" type, it raised this error

**Comment by ueman** [comment]
I still don't see why it doesn't work. Maybe you're importing a different class which is also called `FormData`? Have you tried importing dio as a named import?

This is an error woth your code, not woth DIO.

There's also an example for the FormData usage at https://github.com/cfug/dio/blob/main/example/lib/formdata.dart which works.

**Comment by boziyoung** [comment]
> I still don't see why it doesn't work. Maybe you're importing a different class which is also called `FormData`? Have you tried importing dio as a named import?
> 
> This is an error woth your code, not woth DIO.
> 
> There's also an example for the FormData usage at https://github.com/cfug/dio/blob/main/example/lib/formdata.dart which works.

ok, thank you for the example of yor link;
i import "dio" package in the file which raised this error;
i get a new error:
`The name 'FormData' is defined in the libraries 'package:dio/src/form_data.dart (via package:dio/dio.dart)' and 'package:get/get_connect/http/src/multipart/form_data.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.d`

acctording to IDE's advice , i new add a alias
`import 'package:dio/dio.dart' as new_dio_formDaa;

 new_dio_formDaa.FormData formData =
                        new_dio_formDaa.FormData.fromMap({
                      "original": Se.titleController.value.text,
                      "translation": Se.translationController.value.text,
                      "notes": Se.noteController.value.text
                    });
`
so, now code can work normally

Finally, I really appreciate your help
