### ISSUE TITLE
DioError is named incorrectly

### ISSUE THREAD

**Issue by clragon** [cfug/dio#1789]
### Request Statement

This has bothered me since a while. 
By dart convention, `DioError` is named incorrectly, as it is not an `Error`, but an `Exception`.

The distinction is important, as `Exception` is meant to be caught but `Error` is not.
`Error` signals a mistake from the programmer, that is usually not recoverable, 
while `Exception` is simply a failure of an operation, that can be handled by the program.

As per:
https://api.flutter.dev/flutter/dart-core/Error-class.html
https://api.flutter.dev/flutter/dart-core/Exception-class.html

### Solution Brainstorm

I understand that renaming `DioError` to `DioException` would be a very large breaking change.
This change could be introduced gradually by adding a typedef:

```dart
@Deprecated('Use DioException instead')
typedef DioError = DioException;
```

It's also noteworthy that while `DioException` is more correct based on convention, it is a bit longer to write than `DioError`, though this will probably be eliviated by IDE autocompletion.

It would perhaps be useful to provide a codemod for this transition, as there probably will be many projects that use `DioError` in many places.

**Comment by ueman** [comment]
This is something which will be tackled in the major version if at all. 

I agree though, and the naming bothers me, too. But it's a significant breaking change and keeping users code working is more important than changing the name.

**Comment by Catyousha** [comment]
I'm interested in this issue and currently working at it.
I understand the concern as the major changes could possibly breaking existing code. But we can make sure `DioError` still works by pay more attention on backward compatibility testing.

There are three options i can think for the test:
1. Keep `DioError` in every test.
2. Rename every `DioError` in current test into `DioException`, and add a test that groups unit test which depends on `DioError` (keep the name).
3. Rename every `DioError` in current test into `DioException`, and add the unit test below:
```
test('backward compatibility with DioError', () {
    expect(identical(DioError, DioException), isTrue);
    expect(identical(DioErrorType, DioExceptionType), isTrue);
  });
```

What do you think?

**Comment by clragon** [comment]
I say option 3.

I have set up a PR that contains all the renamings for the main package as well as the deprecation notice.
With the deprecation notice we create a grace period for users to replace their `DioError` with `DioException`.
We can then remove `DioError` in the next major version. We might even wait for the major version after the next, since Dio is a very large package.
This way we can assure users are not surprised by this change.

The unit test you mentioned looks good to me, and I think it would work well.

However, I think we should also consider if there is a way to make migration for users easier.
For example, we could write a linter fix that changes `DioError` into `DioException`, that can then be applied with `dart fix`.

**Comment by AlexV525** [comment]
I haven't explorered the `dart fix` config yet but it should work like this: https://github.com/flutter/flutter/tree/master/packages/flutter/lib/fix_data.
