### ISSUE TITLE
Different type casting by platform

### ISSUE THREAD

**Issue by QweKs-dev** [cfug/dio#1790]
### Package

dio

### Version

5.1.1

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19041.388])
    • Flutter version 3.7.8 on channel stable at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (4 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\QweKs\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\STORAGE_X\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\STORAGE_X\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\STORAGE_X\IntelliJ IDEA Community Edition 2022.1.4
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6096

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.149

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

### Dart Version

2.19.5

### Steps to Reproduce

Code example
`
@JsonSerializable()
class Info {
  double? userId;
  double? age;
  String? name;

  Info();

  factory Info.fromJson(Map<String, dynamic> json) => _$InfoFromJson(json);
  Map<String, dynamic> toJson() => _$InfoToJson(this);
}

@JsonSerializable()
class UserInfo {
  User? user;
  List<Info>? info;
  List<double>? userIds;

  UserInfo();

  factory UserInfo .fromJson(Map<String, dynamic> json) => _$UserInfoFromJson(json);
  Map<String, dynamic> toJson() => _$UserInfoToJson(this);
}
`
`
  Future<UserSetting> userSetting(double userId, UserInfo params) async {
    var resIdStr = userId.truncate().toString();
    var rslt = await fetchObj(
        () => _rest.post("/info/users/$resIdStr", params), (json) => UserSetting.fromJson(json));
    return rslt;
  }`

### Expected Result

Processing the same value is the same regardless of platform.

### Actual Result

When I call method `userSetting` on Web I get good response. But on Android I get error, because fields on my beck-end handles int values. Why Web platform is cast differently?

**Comment by AlexV525** [comment]
Generally Web treats `1.0` as `1` unless the environment is using the wasm. Use `num` instead of `int` or `double` for compability.
