### ISSUE TITLE
Dio call api mutiple times 

### ISSUE THREAD

**Issue by venbrinoDev** [cfug/dio#1793]
### Package

dio

### Version

dio: 5.0.3

### Output of `flutter doctor -v`

```shell
Flutter (Channel stable, 3.7.7)
    • Flutter version 3.7.7 on channel stable at /Users/mines/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
```

### Dart Version

2.19.4

### Steps to Reproduce

Add this package 
pretty_dio_logger: ^1.3.1
 dio: ^5.0.3
 
 Instantiate dio and add interceptor(pretty dio logger )

Dio dio = Dio
    ..interceptors.add(PrettyDioLogger());
    
   call any endpoint 
   open your run(terminal) to view mutiples call
   
   dio makes more than 5 calls to api at once 

### Expected Result

Expect a single call

flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝

### Actual Result

mutiple calls

flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: loaded image
flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║ api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: \^[[38;5;12m💡  Locator - >>> This not an auth request<…>
flutter:
flutter: ╔╣ Request ║ GET
flutter: ║  api/v1
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝

**Comment by ueman** [comment]
Hey, can you add a minimal example which reproduces this behavior? I can't reproduce this issue.
