### ISSUE TITLE
Support Cronet Engine

### ISSUE THREAD

**Issue by chientrm** [cfug/dio#1802]
### Request Statement

Implement cronet engine as the default network stacks.

**Comment by AlexV525** [comment]
Your statement seems a little bit different from your title. Can you identify your request more specifically?

**Comment by chientrm** [comment]
> Your statement seems a little bit different from your title. Can you identify your request more specifically?

My bad, I mean to allow using Cronet network stack with `Dio`, not to set it as the default network stack.

**Comment by AlexV525** [comment]
We already have `native_dio_adapter`. Check it out first.
