### ISSUE TITLE
Cannot connect my flutter app to localhost API

### ISSUE THREAD

**Issue by osmartakashi** [cfug/dio#1805]
### Package

dio

### Version

5.1.1

### Output of `flutter doctor -v`

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1555], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include
      these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Dart Version

2.9.16

### Steps to Reproduce

1- Given an backend in .net 7 (API), eg https://localhost:<port>/api/products
2 - An Dio Instance in a flutter app running on android emulator;
3 - A method to connect into this API from the flutter app.

### Expected Result

The result is to establish a connection between my app and the localhost API.

### Actual Result

The actual result is an error from Dio, socket exception or handshake exception.
[api connection problem.pdf](https://github.com/cfug/dio/files/11402815/api.connection.problem.pdf)

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/blob/fcec18303ba9a8c59f5d14aa543d021fde43446e/dio/README.md?plain=1#L750-L753

localhost is the local hostname alias on the host device, not your emulator.
