### ISSUE TITLE
`Response<String>` is treated as string literals rather than JSON literals

### ISSUE THREAD

**Issue by ryuujo1573** [cfug/dio#1806]
### Package

dio

### Version

5.1.1

### Steps to Reproduce

1. POST /foo
2. result
```yml
content-type: application/json
body: "bar" # with quotes
```
3. check `resp.data`
4. get `'"bar"'`

### Expected Result

Step 4 should be parsed into `bar` rather than `"bar"`.
Extra quotes in result of JSON parsing.

### Actual Result

<img width="361" alt="image" src="https://user-images.githubusercontent.com/16525512/236816235-c68a0476-4965-4927-978e-6ab330ccd24f.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/16525512/236816291-38a1fa98-5fdb-4ee2-9ec1-68bbd634fa0b.png">

**Comment by ryuujo1573** [comment]
```json
"bar"
```
This should be a valid json response as specified in header (content-type).

**Comment by AlexV525** [comment]
If the `content-type` is defined as `application/json`-like in your response headers, the data should be parsed to a valid JSON string.

**Comment by ryuujo1573** [comment]
## Cause
When generic type argument is given explicitly (e.g String), the result is not evaluated as JSON literals, and thus the extra padding `"`.


Fixed by leave type argument blank (which is `Response<dynamic>`)

Is this in line with expectation?

**Comment by AlexV525** [comment]
Related to #1751.

**Comment by AlexV525** [comment]
Closing as we think the behavior is as expected and can be solved by a simple workaround.
