### ISSUE TITLE
How handle ssl cert with 5.0.0v

### ISSUE THREAD

**Issue by R0om** [cfug/dio#1808]
### Request Statement

Version
5.1.1

I have tried this code  to make the https(ssl/tls) request but not work
```
(dio.httpClientAdapter as IOHttpClientAdapter).onHttpClientCreate  = (client) {
    client.badCertificateCallback=(X509Certificate cert, String host, int port){
        if(cert.pem==PEM){ // Verify the certificate
            return true;
        }
        return false;
    };
};
```
the problem is 
**The name 'IOHttpClientAdapter' isn't a type, so it can't be used in an 'as' expression.**
 If I try to cast with HttpClientAdapter, the error is :
**The setter 'onHttpClientCreate' isn't defined for the type 'HttpClientAdapter'**

Please help

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/tree/main/dio#httpclientadapter
