### ISSUE TITLE
How to listen for error messages using dio.download()

### ISSUE THREAD

**Issue by giantss** [cfug/dio#1815]
### Package

dio

### Version

4.0.4

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.9 on channel stable at /Users/zhongpeng/file/env/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (6 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

### Dart Version

2.18.5

### Steps to Reproduce

<img width="559" alt="image" src="https://github.com/cfug/dio/assets/13778798/1b67d574-dc4a-4684-8b13-c5a1d5cecb15">

1. Use the above code to download a zip package.
2. The network is interrupted before the download is completed.

### Expected Result

I hope there is a way to catch the network interruption error

### Actual Result

Can't catch any error return.

**Comment by giantss** [comment]
@AlexV525  After I upgraded the version to the latest version v5.2.1+1, the test found that there was no change compared with before. 😔

**Comment by AlexV525** [comment]
Could you provide a minimal example to reproduce the issue? Our tests already contain download tests so issues should be covered.

**Comment by giantss** [comment]
I just created a new example and tested the latest version of `dio` separately. I found that while downloading, the network suddenly disconnected. After a while, reconnecting `try`  `catch` could catch the error, but I don't know why it didn't work in my project. It may be my reason. I will check the problem again. Thank you for solving the problem. I will close the problem first.
