### ISSUE TITLE
POST请求FormData表单提交报错

### ISSUE THREAD

**Issue by hysz-git** [cfug/dio#1819]
### Package

dio

### Version

5.1.1

### Output of `flutter doctor -v`

```shell
请求代码
    var formData = prefix.FormData.fromMap(<String, dynamic>{
      "userIcon": await FileUtils.imageToBase64(avatarImgPath!)
    });
    await DioConfig().dio.post(ApiMe.updateUserInfo,data: formData);

报错内容：
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [unknown]: null
Error: type 'FormData' is not a subtype of type 'Map<String, dynamic>'
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:532:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1660:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:165:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#5      Future._completeError (dart:async/future_impl.dart:575:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
#7      _Completer.completeError (dart:async/future_impl.dart:23:5)
#8      Future.any.onError (dart:async/future.dart:617:45)
#9      _RootZone.runBinary (dart:async/zone.dart:1665:54)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#12     Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#13     Future._completeError (dart:async/future_impl.dart:575:5)
#14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

### Steps to Reproduce

请求代码
    var formData = prefix.FormData.fromMap(<String, dynamic>{
      "userIcon": await FileUtils.imageToBase64(avatarImgPath!)
    });
    await DioConfig().dio.post(ApiMe.updateUserInfo,data: formData);

报错内容：
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioError [unknown]: null
Error: type 'FormData' is not a subtype of type 'Map<String, dynamic>'
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:532:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1660:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:165:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#5      Future._completeError (dart:async/future_impl.dart:575:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
#7      _Completer.completeError (dart:async/future_impl.dart:23:5)
#8      Future.any.onError (dart:async/future.dart:617:45)
#9      _RootZone.runBinary (dart:async/zone.dart:1665:54)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#12     Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#13     Future._completeError (dart:async/future_impl.dart:575:5)
#14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

### Expected Result

Error: type 'FormData' is not a subtype of type 'Map<String, dynamic>'

参数没问题，看不懂这个报错

### Actual Result

请大佬指点

**Comment by AlexV525** [comment]
Please provide the minimal reproducible code without the actual business code. (We don't know what's happened with your `prefix`, `FileUtils`, etc.)

**Comment by hysz-git** [comment]
///通过图片路径将图片转换成Base64字符串
  static Future<String> imageToBase64(String path) async {
    File file = new File(path);
    List<int> imageBytes = await file.readAsBytes();
    return base64Encode(imageBytes);
  }

**Comment by AlexV525** [comment]
Closing as no useful information is provided. Please attach a minimal reproducible example if it still occurred consistently.
