### ISSUE TITLE
Bug: 400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by m4iu3m** [cfug/dio#1829]
### Package

dio

### Version

5.1.2

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19044.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] Network resources
```

### Dart Version

3.0.0

### Steps to Reproduce

dio get to url https://bitel.com.pe/api/Project/MyBitel/Home/SlideShow/select
query Params: {id: Mibitel_BitelPlus, deviceModel: sdk_gphone64_x86_64, osVersion: 12, deviceBrand: google, appVersion: 4.4.15, OS: Android, securityToken: a25f5f759ba8d080801728d5321847f6b272b0544b74c5c8e37c3c6b54cae149}

### Expected Result

```dart
  {
    _id: "62b57d8106691e2bd70ea2f4",
    createdTime: 1656061313,
    lastUpdateTime: 1679642018,
    sortOrder: 1656061313,
    creatorId: 199801,
    site: 2005922,
    type: "Decl.Slideshow",
    slideType: "default",
    title: "Mibitel BitelPlus",
    status: 1,
    appCode: "Mibitel_BitelPlus",
    links: [
      {
        title: "Miplan",
        phone: "",
        link: "page/Home/Product/CustomizePlan/Edit?isPlanChip=1",
        linkGoogle: "",
        linkAppStore: "",
        linkAppGallery: "",
        objectType: "1",
        btnLabel: "",
        subTitle: "",
        detailLayout: "",
        icon: "",
        brief: "",
        image: "upload/2005922/20220816/ARMA-TU-PLAN_cae87.jpg",
        iconImage: "",
        displayImage: "right",
        sortOrder: 2
      },
      {
        title: "1",
        phone: "",
        link: "https://tonos.bitel.com.pe/home",
        linkGoogle: "",
        linkAppStore: "",
        linkAppGallery: "",
        objectType: "1",
        btnLabel: "",
        subTitle: "",
        detailLayout: "",
        icon: "",
        brief: "",
        image: "upload/2005922/20220708/1649094746cr7-1920x919__1__1_a6a1d.png",
        iconImage: "",
        displayImage: "right",
        sortOrder: 3
      }
    ],
    amount: "0",
    suggestTitle: "mibitel bitelplus Mibitel BitelPlus mibitel bitelplus",
    resellerId: 10263,
    isTrial: 0,
    isDisplay: 1,
    log: "editar",
    rewriteURL: "decl/slideshow/mibitel-bitelplus2.html",
    type1: "Decl",
    type2: "Decl.Slideshow",
    lastUpdateUserId: 0,
    id: "62b57d8106691e2bd70ea2f4"
  }
```

### Actual Result

<html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx</center>
</body>
</html>

**Comment by m4iu3m** [comment]
if i go back to version 4.0.6 this problem won't happen. it started with version 5.0.0 and still suffers with latest version 5.1.2

**Comment by kuhnroyal** [comment]
Works as expected.
Please check if you use the cookie plugin and have a large cookie stored in there.

**Comment by m4iu3m** [comment]
> Works as expected. Please check if you use the cookie plugin and have a large cookie stored in there.

yes, i am using dio_cookie_manager and cookie_jar library, but why in dio version 4.0.6 does this issue?

**Comment by kuhnroyal** [comment]
I don't know, probably the `dio_cookie_manager` and `cookie_jar` library are older versions as well and some behaviour has changed there.
If you can provide a reproducible sample where this happens, we might be able to take a look.

**Comment by AlexV525** [comment]
Could you roll all your dependencies (dio, cookie_manager, cookie_jar) to use the latest and verify if the issue still persists?

**Comment by AlexV525** [comment]
Tried with twice requests and the issue is not reproducible.
![image](https://github.com/cfug/dio/assets/15884415/bbaca02f-e76d-4613-8617-c02d41a00a3e)
