### ISSUE TITLE
Dio PUT slow compared to http

### ISSUE THREAD

**Issue by alexcode9** [cfug/dio#1832]
### Package

dio

### Version

5.1.2

### Output of `flutter doctor -v`

```shell
Testing it with pure Dart on Windows
```

### Dart Version

3.0.1

### Steps to Reproduce

```dart
final response = await dio.Dio().put(
      url,
      data: bytes,
      options: dio.Options(
        headers: {'Content-Type': 'application/octet-stream'},
      ),
    );
```

### Expected Result

With http took 0:00:04.612981

```dart
final response = await http.put(
      Uri.parse(url),
      body: bytes,
      headers: {'Content-Type': 'application/octet-stream'},
    );
```

### Actual Result

Unexpected long times making simple PUT requests compared to http standard package. 
For example making this call, where url is an AWS signed URL, took 0:00:21.581325

Am I doing something wrong?

**Comment by kuhnroyal** [comment]
Are you testing on web or io?

**Comment by alexcode9** [comment]
Don't know what you mean by that, sorry... To test it I'm just doing a `dart run main.dart` in windows and I only have that request in main

**Comment by kuhnroyal** [comment]
Yea was asking for the platform you are testing on.

**Comment by alexcode9** [comment]
I also tested it against a simple Postman mock server with same results

**Comment by alexcode9** [comment]
It works great now!

**Comment by kuhnroyal** [comment]
Cool, will see if I can get this into the 5.2 release.
