### ISSUE TITLE
dio put The network is abnormal during file uploading. No error response is received

### ISSUE THREAD

**Issue by wahkim** [cfug/dio#1833]
### Package

dio

### Version

5.1.1

### Dart Version

2.18.6

### Steps to Reproduce

```dart
Dio dio = new Dio();
      (dio.httpClientAdapter as IOHttpClientAdapter).onHttpClientCreate = (client) {
        client.badCertificateCallback = (cert, host, port) {
          return true;
        };
        client.connectionTimeout = Duration(seconds: 5);
      };
      String suffix = filePath.substring(filePath.lastIndexOf("."), filePath.length);
      MediaType mediaType = getMediaType(suffix);
      String contentType = mediaType.mimeType;
      dio.options.contentType = contentType;

      var response = await dio.put(
        url,
        data: Stream.fromIterable(list),
        cancelToken: cancelToken,
        onSendProgress: (count, total) {
          print('onSendProgress count=${count}, total=${total}');
        },
        onReceiveProgress: (count, total) {
          print('onReceiveProgress count=${count}, total=${total}');
        },
        options: Options(headers: {
          Headers.contentLengthHeader: data.length, // content-length
        }),
      );
```

### Expected Result

You should receive a response that the upload failed.

### Actual Result

No response.

**Comment by kuhnroyal** [comment]
If you don't receive a response, then you should get an error, timeout or something.
Nothing is not really possible.

**Comment by wahkim** [comment]
> If you don't receive a response, then you should get an error, timeout or something. Nothing is not really possible.

No error response has been received.

**Comment by wahkim** [comment]
> 
I did a test. When three files were uploaded at the same time, the network was interrupted during the uploading process, but the response time received was different. In particular, the response time received for the third file was 3 minutes slower than that of the first two files. Here's why.

The following is the log.
2023-06-01 15:02:14.033553+0800 Runner[37897:2227357] flutter: upload onSendProgress count=262144, total=349257
2023-06-01 15:02:15.042737+0800 Runner[37897:2227357] flutter: upload onSendProgress count=262144, total=406461
2023-06-01 15:02:15.403959+0800 Runner[37897:2227357] flutter: uploadonSendProgress count=262144, total=580565
2023-06-01 15:03:44.202668+0800 Runner[37897:2227357] flutter: upload error=DioError [unknown]: null
2023-06-01 15:03:56.613046+0800 Runner[37897:2227357] flutter: upload error=DioError [unknown]: null
2023-06-01 15:07:02.368930+0800 Runner[37897:2227357] flutter: upload error=DioError [unknown]: null

**Comment by AlexV525** [comment]
The reported log seems to be incomplete. Please try to provide a reproducible example or a more detailed stack trace for this. Also, we've improved the payload transformation performance recently with #1838, which can be possibly related.
