### ISSUE TITLE
how to hold another api untill where current api getting refresh token 

### ISSUE THREAD

**Issue by Devandhiran637** [cfug/dio#1848]
### Request Statement

In dio Interceptor and the user touch multiple events in a whole app and the api are triggered multiple times and every request call refresh token at the same time and return 400 issue logout to login page

I also tried Future.wait  but it trigerred multiple api are given at same time, it will wait return respone

but here the user touch other event where the current api aldready loading and event call api then two api getting refresh will return issue session expired

So how to hold another api until where current api get refresh token then allow that api get data

`class  Interceptor{
static Dio dio({dynamic data}) {
    final dio = Dio();

dio.interceptors.add(AuthInterceptor(dio: dio));

    return dio;
  }
}`

`class AuthInterceptor extends QueuedInterceptor {
  final Dio? dio;
  BuildContext? context;

  AuthInterceptor({this.dio, this.context});

  @override
  void onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {
    final accessToken = await Mystorage.read('access');
    final refreshToken = await Mystorage.read('refresh');
   
    
    

    if (accessToken == null || refreshToken == null) {
      Nav.navKey.currentState!
          .pushReplacementNamed('/login');
    }
    

    
    bool accessisExpired = JwtDecoder.isExpired(accessToken ?? " ");

    if (accessisExpired ) {
    

      try {
        _refresh = await Api.refresh();
      } on DioError catch (e) {
        if (e.type == DioErrorType.sendTimeout ||
            e.type == DioErrorType.connectionTimeout ||
            e.type == DioErrorType.receiveTimeout) {
          return handler.next(options);
        } else if (e.error is SocketException) {
          print(e);
          print('f net');

          return handler.next(options);
        }
      }
      if (_refresh == true) {
        
        options.headers["Authorization"] =
            "Bearer ${await Mystorage.read("access")}";
       
        options.headers["accept"] = "application/json";
        options.connectTimeout = const Duration(seconds: 120);
        options.receiveTimeout = const Duration(seconds: 90);

        return handler.next(options);
      } else if (_refresh == null) {
       
       Nav.navKey.currentState!
            .pushReplacementNamed('/login');
      } else {
       
        bool anotherchech = JwtDecoder.isExpired(
            await Mystorage.read('access') ?? " ");
        if (anotherchech) {
          
          Nav.navKey.currentState!
              .pushReplacementNamed('/loginpage');
          
        } else {
          print('f 6');
          options.headers["Authorization"] =
              "Bearer ${await Mystorage.read("access")}";
          options.headers["x-api-key"] = Url.clientId;
          options.headers["accept"] = "application/json";

          options.connectTimeout = const Duration(seconds: 120);
          options.receiveTimeout = const Duration(seconds: 90);

          return handler.next(options);
        }
      }
    } else {
      print('4');
      options.headers["Authorization"] =
          "Bearer ${await Mystorage.read("access")}";
      options.headers["x-api-key"] = Url.clientId;
      options.headers["accept"] = "application/json";

      options.connectTimeout = const Duration(seconds: 120);
      options.receiveTimeout = const Duration(seconds: 90);

      return handler.next(options);
    }
  }

 

  @override
  void onError(DioError err, ErrorInterceptorHandler handler) async {
    }
}
`
`class Repo{
Future callapi(){
var response = await Interceptor.dio(data: typeId).post(
      "${Api.url}/xxxxxx",
      data: l,
    );
   

    return response;
}
}`

**Comment by stngcoding** [comment]
did you find any solutions, can you share it here ?

**Comment by Devandhiran637** [comment]
I'm not sure, try adding queue package
`@override
  void onRequest(
      RequestOptions options, RequestInterceptorHandler handler) async {
    final accessToken = await Secure.read('accesstoken');
    final refreshToken = await Secure.read('refreshtoken');
   
    var _refreshed = false;
   
    bool accesscheck = JwtDecoder.isExpired(accessToken ?? " ");

   

    if (accessTokenHasExpired) {
  
      final queue = Queue();
      await queue.add(() async {
        try {
          _refreshed = await Authenticateapi.refreshtoken();
        } on DioError catch (e) {
          if (e.type == DioErrorType.sendTimeout ||
              e.type == DioErrorType.connectionTimeout ||
              e.type == DioErrorType.receiveTimeout) {
       
            _refreshed = true;
            return handler.next(options);
          } else if (e.error is SocketException ||
              e.type == DioErrorType.unknown) {
          
            _refreshed = true;
            return handler.next(options);
          } else {
            _refreshed = true;
            return handler.next(options);
          }
        }
      });`

**Comment by duytq94** [comment]
You can refer to this article
https://medium.com/@duytq94/flutter-refesh-token-with-multiple-requests-4d851c8fe788

**Comment by SelvaKumar-Ajay** [comment]
I use a boolean value to identify refresh call is in process or not, like below ,

  // this static bool value is used to identidy does any on going refresh call happened
  static bool isRefreshing = false;
  static List<Function> pendingRequests = []; // To store pending requests

in my call refresh token function at top i place this code which will hold the upcoming requests if one in ongoing

 if (isRefreshing) {
      // Queue the requests until the refresh token is obtained
      pendingRequests.add(() => _retryRequest(method, e, handler));
      debugPrint(
          "Request queued, pendingRequests count: ${pendingRequests.length}");
      return;
    }

    isRefreshing = true; // Mark refresh in progress
    debugPrint("Refresh token call initiated");

Then in completion of call refresh token,

      // Once refresh is complete, retry the pending requests
      isRefreshing = false;
      _retryPendingRequests(); // Ensure retry happens after refresh


  // Retry all pending requests after refresh token is obtained
  _retryPendingRequests() {
    debugPrint(
        "Retrying all pending requests, count: ${pendingRequests.length}");
    for (var request in pendingRequests) {
      try {
        request(); // Call each pending request
      } catch (e) {
        debugPrint("Error retrying request: $e");
      }
    }
    pendingRequests.clear();
  }

  // Retry the specific API request
  _retryRequest(String method, DioError e, handler) async {
    RequestOptions options = e.response!.requestOptions;
    options.headers.clear();
    options.headers = {
      "Authorization":
          "Bearer ${LocalStorage.getString(AppStrings.accessToken)}",
      AppStrings.contentType: AppStrings.contentTypeValue
    };

    try {
      Response<dynamic> response;
      if (method == 'GET') {
        response = await dio!
            .request(options.path, options: Options(headers: options.headers));
      } else {
        response = await dio!.request(options.path,
            options: Options(headers: options.headers, method: options.method),
            data: options.data);
      }
      handler.resolve(response);
    } catch (e) {
      handler.reject(e);
    }
  }


its worked for me...
