### ISSUE TITLE
Dio Web Proxy Rules

### ISSUE THREAD

**Issue by huafsud** [cfug/dio#1857]
### Request Statement

随着Flutter Web的普及，它在Web开发中的应用也越来越广泛。然而，由于浏览器的跨域限制，Flutter Web的跨域请求变得非常困难，特别是对于那些位于不同域名下、格式不规范的数据接口（如html、json、jsonp等）更是如此。

需求：

我们是否能够提供一个通用的BrowserHttpClientAdapter proxy接口，以便在Flutter Web应用中通过代理服务器访问目标服务器？类似于IOHttpClientAdapter的Proxy属性，可以使用proxyUrl、port和header等字段来传递代理服务器的信息，并返回任何网站的数据给Flutter Web。

dio web proxy ---> self proxy service(maybe java ,go ,node) --->  return any website data to dio web, 

example(maybe like this or other rules)
dio.BrowserHttpClientAdapter.proxy(proxyUrl:'xxxx.com/proxy', port: 443);

dio.get("https://abc.com/")
// then dio internal code will send real request 
dio.get('xxxx.com/proxy',header:{"realUrl":"https://abc.com",requestType:"GET",...headers})

好处：
通过这种方式，我们可以在初始化Dio对象时，根据不同的环境自适应代理规则，而不需要对业务代码进行修改。这样就能够更方便地在Flutter Web应用中实现跨域请求。

--------------------------------- 
With the popularity of Flutter Web, its application in web development is becoming more and more widespread. However, due to the cross-domain restrictions of browsers, cross-domain requests in Flutter Web have become very difficult, especially for those data interfaces that are located in different domains and have non-standard formats (such as html, json, jsonp, etc.).
Requirement:

Can we provide a universal BrowserHttpClientAdapter proxy interface so that we can access target servers through a proxy server in Flutter Web applications? Similar to the Proxy property of IOHttpClientAdapter, we can use fields such as proxyUrl, port, and header to pass the information of the proxy server and return data of any website to Flutter Web.
dio web proxy ---> self proxy service(maybe java, go, node) ---> return any website data to dio web

Example (maybe like this or other rules):

dio.BrowserHttpClientAdapter.proxy(proxyUrl: 'example.com/proxy', port: 443);

dio.get("https://abc.com/")
// Then, the internal code of dio will send the real request:
dio.get('example.com/proxy', header: {"realUrl": "https://abc.com", "requestType": "GET", ...headers});

Benefits:
By doing so, we can adapt to the proxy rules according to different environments when initializing the Dio object, without modifying the business code. This makes it more convenient to implement cross-domain requests in Flutter Web applications.

**Comment by huafsud** [comment]
maybe this feature seems small or unimportant,
 but dio has is a solution like this, 
 many mobile or desktop apps can run on the web without worrying about cross-domain issues.
so it will be easy to run apps on the web.

**Comment by AlexV525** [comment]
当涉及到自定义的 header 的时候，处理起来就绝对不会是一个通用方案。

你已经提到可以自定义 `BrowserHttpClientAdapter`，请直接在自定义的类中进行重定向即可。

如果你已经实现了自己的方案，欢迎以 package 的形式发布在 pub，让更多人可以使用。我认为此时的 dio 不适合内置这样的功能。
