### ISSUE TITLE
Regression in Dio 5.2.0 when encoding json arrays of int values

### ISSUE THREAD

**Issue by ekuleshov** [cfug/dio#1858]
### Package

dio

### Version

5.2.0

### Output of `flutter doctor -v`

```shell
% flutter doctor -v
[✓] Flutter (Channel stable, 3.10.4, on macOS 12.6.1 21G217 darwin-arm64, locale en-CA)
    • Flutter version 3.10.4 on channel stable at /Users/../flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (4 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6.1 21G217 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.
```

### Dart Version

3.0.3

### Steps to Reproduce

The following change in Dio 5.2.0 broke transformation of JSON payloads (e.g. for POST requests) containing array of int values like `[10, 20, 30]` (i.e. `List<int>` on the Dart side, for example a list of some ids).

* Improve performance when sending binary data (List<int>/Uint8List): https://github.com/cfug/dio/commit/193f783e4ded86997b81e54814aba5a2e78584ed#diff-0c6ad18173da236b264dd249ca7086db6b1e1b4b51cdfe40077268e3407c45caR643-R645

As a result with Dio 5.2.0 the `retrofit` Rest client using Dio backend now sends an array of bytes instead of json-array if ints.

This is a bad regression and the only workaround is to change all `retrofit` APIs to not use `List<int>` as a payload and have to wrap it in some envelope.

### Expected Result

The Dio should not be breaking a previously existing behaviour when encoding request payloads and json arrays should not be sent as binary data.

### Actual Result

A byte array or binary payload is being sent instead of json-array of ints.

**Comment by AlexV525** [comment]
cc @kuhnroyal

**Comment by kuhnroyal** [comment]
Yea, that is pretty bad...
I reverted that part of the change and added a test to ensure this doesn't happen again.
I guess handling `Uint8List` directly as binary is enough for now.
