### ISSUE TITLE
DioError [DioErrorType.other]: HttpException: Connection reset by peer

### ISSUE THREAD

**Issue by lala-naibova** [cfug/dio#1864]
### Package

dio

### Version

4.0.6

### Steps to Reproduce

Hi, I don't know in what occasions this happens. But I found it from log file. My app crashes at the result of this error

### Expected Result

App should work without crashing

### Actual Result

My app crashes without any cause and this error appears on my log file

**Comment by sgsm74** [comment]
Please provide some code

**Comment by AlexV525** [comment]
We cannot do further actions but close the issue because no helpful information is provided.
