### ISSUE TITLE
Adapt classes with isolates

### ISSUE THREAD

**Issue by AlexV525** [cfug/dio#1867]
### Request Statement

https://github.com/flutter/flutter/issues/126520#issuecomment-1544422281

> Recent versions of the Dart SDK have tightened the rules for which objects can be sent across isolates (see https://api.dart.dev/stable/3.0.0/dart-isolate/SendPort/send.html and [dart-lang/sdk@67683c39](https://github.com/dart-lang/sdk/commit/67683c39))

Classes might cause unsendable issues when passing through isolates. Someone reported that `MultipartFile` is not sendable which fails the runtime.

![image](https://github.com/cfug/dio/assets/15884415/d2523197-e066-4a69-b3ce-d9fa20606b3c)

### Solution Brainstorm

Make those classes sendable, or figure out ways to handle them in isolates.

**Comment by AlexV525** [comment]
cc @kuhnroyal I saw a related request in https://github.com/OpenAPITools/openapi-generator/pull/15516, could you check if we're capable to adapt similar changes as well?

**Comment by kuhnroyal** [comment]
The PR you linked involves types sent to an isolate due to generator code during encoding/decoding.
Here I don't believe this is something that dio is doing. The easy answer is, don't try to send complex types through a `SendPort`.

**Comment by AlexV525** [comment]
Great, thanks for the feedback!
