### ISSUE TITLE
Method download cause memory leaking

### ISSUE THREAD

**Issue by TacticalTwerking** [cfug/dio#1881]
### Package

dio

### Version

^4.0.0

### Dart Version

Dart 2.19.6 • DevTools 2.20.1

### Steps to Reproduce

1. define a dio instance as a static variable at the top of the class
static var dio = Dio();

2. use the code below to download the file 
static void downloadWithDio(String url) async {
    dio.download(url, getSavePath(url),
      onReceiveProgress: (int count, int total) {
        print('$url -=> $count / $total');
      },
      options: Options(responseType: ResponseType.stream),
    );
  }

### Expected Result

after each file is downloaded, memory drops down to normal

### Actual Result

open DevTools for observation and repeat step 2 several times, you will see the memory gain quickly and will not drop down after the download has been done as ideally

*From the 'Dart VM Observatory' table, I got some massive(100MB) '_HttpProfileData' objects retained by GC root

**Comment by kuhnroyal** [comment]
The `_HttpProfileData` is actually from the Dart profiler. Might be a problem there.

**Comment by AlexV525** [comment]
- `^4.0.0` is an outdated major version of Dio.
- `2.19.6` also results an older stable version of Dart/Flutter.
- You might need to run the profiler under the profile mode (if it's not)

Could you resolve the above outdated version before we go deeper into this?

**Comment by AlexV525** [comment]
See https://github.com/flutter/devtools/issues/4353. Closing as it's a DevTool issue. Please let us know if it's unrelated and provide detailed steps or a minimal reproducible example.
