### ISSUE TITLE
CookieJar does not work in Flutter-web.  What is the point?

### ISSUE THREAD

**Issue by WorikQCI** [cfug/dio#1892]
### Package

cookie_manager

### Version

3.1.0

### Output of `flutter doctor -v`

```shell
In `cookie_jar.dart` there is the code:


const _kIsWeb = bool.hasEnvironment('dart.library.js_util')
    ? bool.fromEnvironment('dart.library.js_util')
    : identical(0, 0.0);
:
:
  factory CookieJar({bool ignoreExpires = false}) {
    if (_kIsWeb) {
      throw UnimplementedError();
    }

```

So this is never going to work in Flutter Web?
```


### Dart Version

_No response_

### Steps to Reproduce

```

    final cookieJar = CookieJar();

```

### Expected Result

`cookieJar` initialised

### Actual Result

Exception

**Comment by AlexV525** [comment]
The `cookie_manager` can work with Flutter Web if you enabled `BrowserHttpClientAdapter.withCredentials`. The `cookie_jar` doesn't support Flutter Web though.

**Comment by WorikQCI** [comment]
> The `cookie_manager` can work with Flutter Web if you enabled `BrowserHttpClientAdapter.withCredentials`. The `cookie_jar` doesn't support Flutter Web though.

Awesome.  But how can I use `cookie_manager` with out `CookieJar`?

The [example](https://pub.dev/packages/dio_cookie_manager/example) is:

```
  final dio = Dio();
  final cookieJar = CookieJar();
  dio.interceptors.add(CookieManager(cookieJar));
```

**Comment by AlexV525** [comment]
That typically means you'll need the `cookie_manager` only when the environment is Flutter Web.

**Comment by WorikQCI** [comment]
> That typically means you'll need the `cookie_manager` only when the environment is Flutter Web.

I am not quite sure I understand.

The problem is that `CookieManager`  cannot be used in Flutter Web

I need access to the "set-cookie" header in the response, but it is filtered out (the server is sending it, I can see it in Chromeium. developer tools).

The request is an XML HttpRequest made after the app is initialised.  

I got round the CORS issue with `launch.json` (I am using VSCode):

```
            "args": [
                "-d",
                "chrome",
                "--web-browser-flag",
                "--disable-web-security"
            ]
```

I am getting a lot of headers back, just not the one I need.

**Comment by AlexV525** [comment]
Try to enable the `BrowserHttpClientAdapter.withCredentials` and you won't need to use packages on Flutter Web.

**Comment by WorikQCI** [comment]
> Try to enable the `BrowserHttpClientAdapter.withCredentials` and you won't need to use packages on Flutter Web.

Thank you for your attention.  I am feeling my way through flutter web, porting a desktop flutter programme.  I need this so I can develop, test, and debug this software on my computer, without having to do that on the hosting server.

However using the `BrowserHttpAdapter` has not helped.

This is what I have:


```
    final dio = Dio();
    dio.httpClientAdapter = BrowserHttpClientAdapter(withCredentials: true);
    dio.options
      ..connectTimeout = const Duration(seconds: 50)
      ..receiveTimeout = const Duration(seconds: 50)
      ..validateStatus = (int? status) {
        return status != null && status > 0;
      }
      ..headers = {
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "Accept": "application/json, text/javascript, */*; q=0.01",
      };
    // dio.httpClientAdapter = Http2Adapter(ConnectionManager());
    Response response = await dio.post(url.toString(), data: bodyData);
```

And these are the headers:

```
request.responseHeaders: cache-control: no-store
cache-control:  no-cache
cache-control:  must-revalidate
content-length: 142
content-type: application/json; charset=UTF-8
date: Wed
date:  12 Jul 2023 20:45:42 GMT
expires: Thu
expires:  19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: Microsoft-IIS/10.0
x-powered-by: PHP/7.4.15
```

**Comment by WorikQCI** [comment]
Looking deeper it appears that chrome is filtering out the `set-cookie` header.

I can see it in the network tab of chrome, but I cannot see it in flutter.

This is not the fault of Cookie Jar, even though Cookie Jar does not work (yet) for Flutter Web.
