### ISSUE TITLE
Files cannot be deleted if network exceptions are thrown

### ISSUE THREAD

**Issue by feimenggo** [cfug/dio#1920]
### Package

dio

### Version

5.3.0

### Dart Version

3.10.6

### Steps to Reproduce

1.在Windows平台，使用dio上传文件
dio.requestUri(uri, data: file.openRead())

2.当遇到网络错误导致上传失败
Bad state: DioException [unknown]: null
Error: SocketException: Write failed (OS Error: 你的主机中的软件中止了一个已建立的连接。
, errno = 10053), address = private-xxx.cos.ap-guangzhou.myqcloud.com, port = 51980

3.此时想要删除该文件会提示以下错误
PathAccessException: Cannot delete file, path = 'C:\Users\6\AppData\Roaming\xxx\xxx.jpg' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)

4.由于file.openRead() 创建的stream没有done或被cancel，仍然占用着该文件，因此无法删除文件

### Expected Result

当遇到网络错误导致上传失败后，需要调用StreamSubscription的cancel方法，关闭流。

### Actual Result

由于file.openRead() 创建的stream没有done或被cancel，仍然占用着该文件，因此无法删除文件

**Comment by AlexV525** [comment]
与 dio 貌似没有任何关系，需要你自己维护 stream 的处理？

**Comment by AlexV525** [comment]
![image](https://github.com/cfug/dio/assets/15884415/d2184381-fdc4-4cbc-bc01-73d444b52652)

> dio会调用listen()来读数据

我们的代码中没有任何地方使用了 `.listen()`，该行为应当由 `HttpRequest` 自动进行处理。

**Comment by AlexV525** [comment]
> dio会调用listen()来读数据

我们的代码中没有任何地方对入参 Stream 进行订阅，传入的 Stream 均由 HttpRequest 进行处理。

**Comment by AlexV525** [comment]
> 是不是应该在这里遇到错误的时候，调用 request.close(); 或 request.abort(); 方法呢？

可以先行确认是否有改善

**Comment by AlexV525** [comment]
不需要通过操作物理设备模拟，理论上只需要延迟调用 throw 即可。

**Comment by AlexV525** [comment]
request 开始之后，delay 一个 throw。

**Comment by AlexV525** [comment]
尝试把 io_adapter.dart#L154 改成如图后再试
![image](https://github.com/cfug/dio/assets/15884415/91349105-4ea4-47fb-be10-a90cf7b70b05)

**Comment by AlexV525** [comment]
拉主分支的代码调试呀…

**Comment by AlexV525** [comment]
问题是否依旧存在？如存在是否可以提供可以直接复现的最小demo？

**Comment by AlexV525** [comment]
```yaml
depedencies:
  dio:
    git:
      url: https://github.com/cfug/dio
      path: dio
```

**Comment by AlexV525** [comment]
提供可以直接复现的最小demo，此处不再做无关回复。

**Comment by AlexV525** [comment]
与 dio 无关，等待上游修复。

**Comment by zpp0196** [comment]
试试 [Stream.asBroadcastStream()](https://api.flutter.dev/flutter/dart-async/Stream/asBroadcastStream.html)

参考：https://github.com/localsend/localsend/pull/1228

**Comment by NightFeather0615** [comment]
> 试试 [Stream.asBroadcastStream()](https://api.flutter.dev/flutter/dart-async/Stream/asBroadcastStream.html)
> 
> 参考：[localsend/localsend#1228](https://github.com/localsend/localsend/pull/1228)

目前看來這應該是最簡潔的解法，缺點就是要等 StreamSubscription 自己取消

這裡有另一種可以馬上釋放 file handle 的解法，更可控但複雜度高不少，其實就是把 `.asBroadcastStream()` 搬過來用😂

```dart
var fileName = "some/file/path";

final file = File(fileName);
final fileStream = file.openRead();
StreamController<List<int>> fileReadController = StreamController();
final fileReadSubscription = fileStream.listen(
  fileReadController.add,
  onError: fileReadController.addError,
  onDone: () => fileReadController.close()
);

final dio = Dio();

try {
  await dio.post(
    "https://httpbun.com/post",
    data: fileReadController.stream
  );
} catch (_) {
  await fileReadSubscription.cancel();
  await file.delete();
}
```
