### ISSUE TITLE
cannot change default content-type when uploading video to S3 bucket using dio FormData and Multipart

### ISSUE THREAD

**Issue by ilyosbekkk** [cfug/dio#1927]
### Package

dio

### Version

5.0.3

### Output of `flutter doctor -v`

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.79.0)
[✓] Connected device (3 available)
[✓] Network resources
```

### Dart Version

3.0.6

### Steps to Reproduce

1.
```
    final formData = FormData.fromMap({
      'file': await MultipartFile.fromFile(
        file.path,
        filename: fileName,
        contentType: MediaType.parse('video/mp4'),
      ),
    });

```
2.
```
  final response = await dio.put<dynamic>(endpoint,
          data: formData, options: Options(contentType: 'video/mp4'));

      return response.data;
```
above I changed the content type to 'video/mp4' (I tried both ways separately) but I am still getting  `multipart/form-data; boundary=--dio-boundary-3846454268`

### Expected Result

after changing content type is should also change to `video/mp4 ` in S3 bucket console, it didn't change and because of that I am getting corrupted file in S3 bucket although I successfully uploaded a video.

### Actual Result

Currently it shows `multipart/form-data; boundary=--dio-boundary-3846454268` in S3 bucket console.

**Comment by kuhnroyal** [comment]
I assume you are putting form-data to the direct file upload endpoint. That will not work.
Maybe reading https://github.com/aws/aws-sdk-js/issues/558 will help.

**Comment by ilyosbekkk** [comment]
> I assume you are putting form-data to the direct file upload endpoint. That will not work. Maybe reading [aws/aws-sdk-js#558](https://github.com/aws/aws-sdk-js/issues/558) will help.

**Comment by ilyosbekkk** [comment]
> I assume you are putting form-data to the direct file upload endpoint. That will not work. Maybe reading [aws/aws-sdk-js#558](https://github.com/aws/aws-sdk-js/issues/558) will help.

Is there any other way to upload file to S3 with presigned url?

**Comment by kuhnroyal** [comment]
You can upload like this:

```dart
      final f = File('test/video.mp4');
      final r = await dio.put(
        '/put',
        data: f.openRead(),
        options: Options(
          contentType: 'video/mp4',
        ),
      );
```

**Comment by ilyosbekkk** [comment]
it worked, thanks
