### ISSUE TITLE
dio.get() passes a non-String data parameter, it will time out

### ISSUE THREAD

**Issue by lyf571321556** [cfug/dio#1937]
### Package

dio

### Version

5.3.2

### Dart Version

2.17.5

### Steps to Reproduce

```dart
try {
 final dio = Dio(); 
dio.options 
..baseUrl = 'https://ones-liuyanfeng.myones.net/api/project/' 
..connectTimeout = const Duration(seconds: 15) 
..receiveTimeout = const Duration(seconds: 30); 
final result = await dio.get("auth/login_support", data: {}, options: Options( method: 'GET', )); 
print(result.toString());
 } catch (e) {
 print(e); 
}
```

### Expected Result

success get data.

### Actual Result

DioException [receive timeout]: The request took longer than 0:00:10.000000 to receive data. It was aborted.

**Comment by AlexV525** [comment]
The connection has been established, it looks like your server didn't respond to your requests.

**Comment by lyf571321556** [comment]
curl https://ones-liuyanfeng.myones.net/api/project/auth/login_support
{"is_unique_org":true,"org_uuid":"TDSh469b","org_type":0,"corp_id":"","agent_id":0,"logo":"","favicon":"","page_title":"default","encryption":null}

**Comment by lyf571321556** [comment]
> The connection has been established, it looks like your server didn't respond to your requests.
->>> curl https://ones-liuyanfeng.myones.net/api/project/auth/login_support
{"is_unique_org":true,"org_uuid":"TDSh469b","org_type":0,"corp_id":"","agent_id":0,"logo":"","favicon":"","page_title":"default","encryption":null}

**Comment by lyf571321556** [comment]
Send a request directly in the browser is also successful
<img width="681" alt="截屏2023-08-15 22 53 23" src="https://github.com/cfug/dio/assets/2295872/3f795d70-8880-43af-a00c-efb36e5e3df1">

**Comment by AlexV525** [comment]
Your Dart code is not equal to your browser request.
![image](https://github.com/cfug/dio/assets/15884415/17e7b626-9e64-4987-9dcb-675c1d26d092)

**Comment by lyf571321556** [comment]
> Your Dart code is not equal to your browser request.
> ![image](https://user-images.githubusercontent.com/15884415/260750824-17e7b626-9e64-4987-9dcb-675c1d26d092.png)

It seemed that  dio.get() can't set 'data' parameter.
