### ISSUE TITLE
Bad state: The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.

### ISSUE THREAD

**Issue by MuhammedRefaat** [cfug/dio#1944]
### Package

dio

### Version

5.3.2

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4.1 22F770820d darwin-x64, locale en-AE)
    • Flutter version 3.10.4 on channel stable at /Users/muhammedrefaat/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (3 months ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Network resources
    • All expected network resources are available.
```

### Dart Version

3.0.3

### Steps to Reproduce

1. User taps a button that triggers background process (isolate):
```
  Future<bool> buttonPressed(String content, String userToken) async {
    bool result = await compute(_runIsolate,
        {'content': content, 'baseUrl': _getBaseUrl(), 'userToken': userToken});
    if (result) {
      await displayNotifications();
    }
    return Future.value(true);
  }
```
2. Inside the isolate, I need to make a server POST request to get some output data.
3. Hence, I'm creating a new DIO() instance with QueuedInterceptor:
```
Dio _getDioInstance(BaseUrl baseUrl, String userToken) {
  final dio = Dio();
  dio.interceptors.add(CustomQueuedInterceptor(
    Dio(),
    EventBus(),
    DeviceInfo(),
    baseUrl,
    userToken: userToken,
  ));
  return dio;
}
```
4. And calling it inside the isolate as the following:
```
Future<bool> _runIsolate(Map<String, dynamic> args) async {
  // get arguments
  .
  .
  Dio dio = _getDioInstance(baseUrl, userToken);
  // Post request
  final response = await dio.post(url, data: {"data": content}); // Here is the issue
  return Future.value(response.statusCode == 200);
}
```

### Expected Result

To get the request executed successfully.

### Actual Result

I'm getting that error:
`Bad state: The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.`
and the request is not executed.

**Comment by AlexV525** [comment]
Please provide a valid feedback by upgrading your Dio version to ^5.0.0 and write a minimal example to reproduce instead,

**Comment by MuhammedRefaat** [comment]
Actually when creating an example I found the error is coming from QueuedInterceptor inherited class, and it's related to other library from that performs some actions onRequest, so nothing to do with dio
