### ISSUE TITLE
[Feature Request] MockWebServer

### ISSUE THREAD

**Issue by Shader-Killer** [cfug/dio#1945]
### Request Statement

Currently If we want to test dio, we must custom HttpClientAdapter, what I want is something like [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver),It lets us specify which responses to return and then verify that requests were made as expected.

### Solution Brainstorm

Unfortunately, Dart [mock-web-server](https://github.com/trevorwang/mock-web-server) seems like not updated since 2018. So I guess if dio maintainer will support?

**Comment by AlexV525** [comment]
[`shelf`](https://pub.dev/packages/shelf)?

**Comment by Shader-Killer** [comment]
No, Shelf's goal is **web server middleware for dart**., but the responsibility of the mock web server is to mock  data and verify whether the returned result is correct result。[flutter_mock_web_server](https://github.com/jandrop/flutter_mock_web_server) is what I‘m looking for. I'm going to close issue.

**Comment by Shader-Killer** [comment]
[flutter_mock_web_server](https://github.com/jandrop/flutter_mock_web_server) is what I‘m looking for. I'm going to close issue.

**Comment by kuhnroyal** [comment]
You might also want to take a look at https://pub.dev/packages/http_mock_adapter
