### ISSUE TITLE
Dio causing breaking build issues since flutter upgrade to 3.13.x

### ISSUE THREAD

**Issue by Harry-SMKD** [cfug/dio#1968]
### Package

dio

### Version

5.0.2

### Operating-System

Linux

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.13.4, on Ubuntu 22.04.3 LTS 5.19.0-50-generic,
    locale en_GB.UTF-8)
    • Flutter version 3.13.4 on channel stable at
      /home/harry/src/mobile-dev/flutter/flutter_linux_3.10.2-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (2 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/harry/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at:
      /home/harry/src/mobile-dev/android-studio/android-studio-2022.2.1.20-linux
      /android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at
      /home/harry/src/mobile-dev/android-studio/android-studio-2022.2.1.20-linux
      /android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Ubuntu
      22.04.3 LTS 5.19.0-50-generic
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Dart Version

3.1.2

### Steps to Reproduce

- Was previously on flutter 3.10.6 without any issue, using the Dio all ok.
- After upgrading to 3.13.x I now get a Dio as an unregistered type issue when running flutter pub run build_runner build.
```
[SEVERE] injectable_generator:injectable_builder on lib/infrastructure/core/injectable_modules.dart:

InvalidType is not a class element

[ConnectivityCubit] depends on unregistered type [Dio] from package:dio/dio.dart

Did you forget to annotate the above class(s) or their implementation with @injectable? 
or add the right environment keys?
```
This is how im setting up the Dio in a injectable_modules:
```
  @LazySingleton(env: [Environment.dev])
  Dio devDioClient() => Dio(
        BaseOptions(
          baseUrl: devHost,
          receiveTimeout: defaultReceiveTimeout,
          connectTimeout: defaultConnectTimeout,
          followRedirects: false,
          validateStatus: (status) => status != null && status < 500,
        ),
      )..interceptors.add(CookieManager(CookieJar()));
```
- The connectivity cubit very simply just takes in the Dio as so:
```
part 'connectivity_state.dart';
part 'connectivity_cubit.freezed.dart';

@injectable
class ConnectivityCubit extends Cubit<ConnectivityState> {
  final Dio _client;
  final ILogger _logger;
  late final StreamSubscription<ConnectivityResult> subscription;

  ConnectivityCubit(this._client, this._logger) : super(const ConnectivityState()) {
```

### Expected Result

- As previous I should be able to use the build_runner build command without being blocked by the Dio error.

### Actual Result

flutter pub run build_runner build --delete-conflicting-outputs
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 165ms
[INFO] Precompiling build script... completed, took 3.0s
[INFO] Building new asset graph completed, took 801ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 3ms
[SEVERE] injectable_generator:injectable_builder on lib/infrastructure/core/injectable_modules.dart:

InvalidType is not a class element
[WARNING] injectable_generator:injectable_config_builder on lib/injection.dart:
Missing dependencies in claude_mobile/injection.dart

[AuthService] depends on unregistered type [Dio] from package:dio/dio.dart
[SelfAssesmentRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[DashboardRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[OrgAutoCompleteService] depends on unregistered type [Dio] from package:dio/dio.dart
[NewsRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[CareerPlanRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[FeedbackService] depends on unregistered type [Dio] from package:dio/dio.dart
[LibraryBookmarkRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[OrganisationRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[MentorService] depends on unregistered type [Dio] from package:dio/dio.dart
[UserRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[MarketDataRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[LocalStorage] depends on unregistered type [SharedPreferences] from package:shared_preferences/shared_preferences.dart
[CmsInsertRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[PeopleRepository] depends on unregistered type [Dio] from package:dio/dio.dart
[EdAppService] depends on unregistered type [Dio] from package:dio/dio.dart
[UserDefinedScreenRemoteDataSource] depends on unregistered type [Dio] from package:dio/dio.dart
[ConnectivityCubit] depends on unregistered type [Dio] from package:dio/dio.dart

Did you forget to annotate the above class(s) or their implementation with @injectable? 
or add the right environment keys?
------------------------------------------------------------------------ 

[INFO] Running build completed, took 13.7s
[INFO] Caching finalized dependency graph completed, took 73ms
[SEVERE] Failed after 13.8s

**Comment by mozochek** [comment]
bruh💀

**Comment by AlexV525** [comment]
We haven't been involved in related artifacts so far. If you can provide a more detailed and minimal reproducible example, we might be able to take a further look.

**Comment by we-prajapati-c001** [comment]
LogInterceptor makes the console lose connection with iOS devices.

can you check by commenting on LogInterceptor? Building from Xcode directly will work fine
