### ISSUE TITLE
onError Interceptors没有拦截到连接错误或者连接超时异常

### ISSUE THREAD

**Issue by langhaoabcd** [cfug/dio#1972]
### Package

dio

### Version

5.3.2

### Operating-System

Windows

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.22621.2283], locale zh-CN)
    • Flutter version 3.10.6 on channel stable at D:\soft\flutter_windows_3.3.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

### Dart Version

3.0.6 (stable)

### Steps to Reproduce

![image](https://github.com/cfug/dio/assets/39892654/166f798e-db1b-4e88-930a-d291e696dfe4)
网络连接错误，或者超时异常没法进入到拦截器，只能用catch捕获？

### Expected Result

网络连接错误或超时2...

### Actual Result

网络连接错误或超时1
![image](https://github.com/cfug/dio/assets/39892654/4111b348-e493-4fe7-9764-e7f954931152)

**Comment by AlexV525** [comment]
Add the interceptor before making requests.
