### ISSUE TITLE
E/flutter (18085): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [bad response]: The request returned an invalid status code of 401. final dio=Dio();

### ISSUE THREAD

**Issue by Mahmoud-Mokh55** [cfug/dio#1984]
### Package

dio

### Version

5.3.3

### Operating-System

Linux

### Steps to Reproduce

what is the problem

### Expected Result

The request returned an invalid status code of 401

### Actual Result

E/flutter (18085): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [bad response]: The request returned an invalid status code of 401.

**Comment by kuhnroyal** [comment]
Do you have an actual question with this? Because right now you just have a standard status code response.

**Comment by Mahmoud-Mokh55** [comment]
> Do you have an actual question with this? Because right now you just have a standard status code response.

I run my code and this error DioException and don't know what is this or how handel it

**Comment by kuhnroyal** [comment]
You received a 401 response from the server which usually means that your request was not authorized.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

**Comment by BLUECALF** [comment]
> > Do you have an actual question with this? Because right now you just have a standard status code response.
> 
> I run my code and this error DioException and don't know what is this or how handel it

HI did you solve this

**Comment by BLUECALF** [comment]
The issue is yes i have handled 401 but maybe the refresh token failed and  the `handler.next(err);` fails to do its work.

other code here..
`class AuthErrorInterceptor extends Interceptor with CredentialsRepo, RefreshToken {
  final Dio dio;
  AuthErrorInterceptor(this.dio);

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) async {
    if (err.response?.statusCode == 401) {
      if (!err.requestOptions.extra.containsKey("numOfTries") || err.requestOptions.extra["numOfTries"] < 2) {
        String? newAccessToken = await refreshToken(userAccessToken != null ? TokenType.user : TokenType.client);
        if (newAccessToken != null) {
          err.requestOptions.headers['Authorization'] = 'Bearer newAccessToken';
          err.requestOptions.extra["numOfTries"] = err.requestOptions.extra.containsKey("numOfTries") ? err.requestOptions.extra["numOfTries"] + 1 : 1;
          print("value in num of tries is ${err.requestOptions.extra["numOfTries"]}");
          return handler.resolve(await dio.fetch(err.requestOptions));
        }
      }
      else
        return handler.next(err);
    }
    return handler.next(err);
  }
}`
