### ISSUE TITLE
DioException.connectionError  - app non-responsive

### ISSUE THREAD

**Issue by cloudbreakstudios** [cfug/dio#1989]
### Package

dio

### Version

5.3.3

### Operating-System

Android

### Output of `flutter doctor -v`

```shell
PS C:\Users\Rob\Desktop\CBS\git\InitSys\responder\initsys-responder> flutter doctor -v
[√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.19045.3448], locale en-GB)
    • Flutter version 3.13.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (3 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Rob\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\Rob\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (4 available)
    • Pixel 4 (mobile)  • 99211FFAZ009P3 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.19045.3448]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 117.0.5938.132
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Dart Version

3.1.2

### Steps to Reproduce

Using Pixel 4 (same seen in emulators) 

Disconnect all data/wifi etc and try to make a request to force a timeout

**client.dart**
```dart
Dio client() {
  const String _baseUrl = '<<my private URL>>';

  Dio dio = new Dio(BaseOptions(
    baseUrl: _baseUrl,
    connectTimeout: Duration(seconds: 5),
    receiveTimeout: Duration(seconds: 3)
  ));

  dio.interceptors.add(InterceptorsWrapper(
    onRequest: (options, handler) {
    debugPrint('Dio onRequest: ${options.method} ${options.path}');
    debugPrint('Dio onRequest Data: ${options.data}');
    return handler.next(options); //continue
  }, onResponse: (response, handler) {
    log('Dio onResponse: ${response.data}');
    return handler.next(response); // continue
  }, onError: (DioException e, handler) {
    //debugPrint('Dio onError Request: ${e.request}');
    debugPrint('Dio onError Message: ${e.message}');
    debugPrint('Dio onError Response: ${e..response}');
    return handler.next(e); //continue
  }));

  return dio;
}
```

**service.dart**
```dart
Future<Response?> fetchEvent({required String alertId}) async {
    debugPrint('fetchEvent()');

    _sessionId = null; //clean out session id

    try {
      Response response = await getAlert(client(), alertId);
      if (response.statusCode == 200) {
        eventData = Event.fromJson(response.data);
        log('fetchEvent() - eventData: $eventData');
        if (eventData != null) {
          _sessionId = eventData!.session;
        }
        return response;
      }
      return response;
    } on DioException catch (e) {
      if (e.type == DioExceptionType.connectionTimeout) {
        return null;
      }

      debugPrint('fetchEvent() -${e.response}');
      return e.response;
    } catch (_) {
      debugPrint('fetchEvent() - error');
      return null;
    }
  } //fetchEvent
```

Then requesting data with..

```dart
return await context.read<MyService>().fetchEvent(alertId: _alertId);
```

### Expected Result

Dio error with a timeout

### Actual Result

io_adapter.dart

`Future<ResponseBody>` _fetch() throws

`throw DioException.connectionError(`

The app locks up and currently unable to handle this gracefully!

**Comment by AlexV525** [comment]
Please provide a minimal example that we can run instantly and make further investigations.

**Comment by cloudbreakstudios** [comment]
@AlexV525 I'm no longer able to reproduce this issue.  I created an example and the issue was not seen. I then switched back to my prod app and again was unable to replicate the issue anymore.  I shall keep an eye out on it, but will close this issue for now.

**Comment by game-birer** [comment]
I also encountered this problem. The code is as follows. A similar error occurred. xxx.xxx.xxx.xxx was replaced by me. The API was verified by postman test and it was OK.


final Dio _dio = Dio();
  String _result = "";
  bool _isLoading = false;

  void _setupDio() {
    _dio.options = BaseOptions(
      baseUrl: "https://xxx.xxx.xxx.xxx",
      connectTimeout: const Duration(seconds: 5),
      receiveTimeout: const Duration(seconds: 3),
      headers: {
        'Content-Type': 'application/json; charset=UTF-8',
        'Accept': 'application/json',
      },
    );

    // _dio.options.withCredentials = true; // 需要时启用
    // _dio.options.

    // 添加拦截器
    _dio.interceptors.add(InterceptorsWrapper(
      onRequest: (options, handler) {
        print('👉 请求发起: ${options.uri}');
        print('├─ Headers: ${options.headers}');
        print('└─ Data: ${options.data}');
        return handler.next(options);
      },
      onResponse: (response, handler) {
        print('✅ 响应接收: ${response.statusCode}');
        print('├─ Headers: ${response.headers}');
        print('└─ Data: ${response.data}');
        return handler.next(response);
      },
      onError: (DioException e, handler) {

        _printDetailedError(e);

        String errorDetails = "";

        // 详细错误类型判断
        if (e.type == DioExceptionType.unknown) {
          if (e.error is SocketException) {
            errorDetails = "网络连接失败，请检查网络设置";
          } else if (e.error is HandshakeException) {
            errorDetails = "SSL证书验证失败";
          } else {
            errorDetails = "未知错误: ${e.error}";
          }
        }

        // 显示错误信息
        showDialog(
          context: context,
          builder: (ctx) => AlertDialog(
            title: const Text("错误"),
            content: Text("$errorDetails\n错误码: ${e.response?.statusCode}"),
          ),
        );

        print('❌ 请求错误: ${e.type}');
        print('├─ Message: ${e.message}');
        if (e.response != null) {
          print('├─ Status: ${e.response?.statusCode}');
          print('└─ Response: ${e.response?.data}');
        }
        return handler.next(e);
      },
    ));
  }

  // 登录
  Future<void> _sendLoginRequest() async {
    if (_isLoading) return;

    setState(() {
      _isLoading = true;
      _result = '';
    });

    try {
      // 构造符合服务端要求的JSON结构
      final Map<String, dynamic> requestBody = {
        "userName": _userName,
        "password": _password,
        "authCode": _authCode,
        "deviceInfo": { // 附加参数
          "platform": "Android",
          "version": "10",
          "uuid": "设备唯一标识"
        }
      };

      final response = await _dio.post(
        '/app/appLogin', // 接口路径
        data: requestBody, // Dio会自动转换为JSON
        options: Options(
          headers: {
            'X-Client-Type': 'flutter_app', // 自定义头部
          },
        ),
      );

      // 处理成功响应
      if (response.statusCode == 200) {
        final responseData = response.data;
        setState(() {
          _result = '登录成功!\n'
              '用户ID: ${responseData['userId']}\n'
              'Token: ${responseData['token']}';
        });
      }
    } on DioException catch (e) {
      // 错误处理
      String errorMessage = '登录失败: ';
      if (e.response != null) {
        errorMessage += _parseServerError(e.response!.data);
      } else {
        errorMessage += _getNetworkError(e);
      }
      setState(() => _result = errorMessage);
    } finally {
      setState(() => _isLoading = false);
    }
  }

  String _parseServerError(dynamic errorData) {
    // 根据服务端错误结构解析
    return errorData?['message'] ?? '未知服务器错误';
  }

  void _printDetailedError(DioException e) {
    print('''
      ‼️ 完整错误堆栈：
      错误类型: ${e.type}
      错误信息: ${e.message}
      请求地址: ${e.requestOptions.uri}
      请求方法: ${e.requestOptions.method}
      请求头: ${e.requestOptions.headers}
      请求体: ${e.requestOptions.data}
      响应状态: ${e.response?.statusCode}
      响应头: ${e.response?.headers}
      响应体: ${e.response?.data}
      底层错误: ${e.error}
      堆栈跟踪: ${e.stackTrace}
        ''');
  }

  String _getNetworkError(DioException e) {
    switch (e.type) {
      case DioExceptionType.connectionTimeout:
        return '连接超时';
      case DioExceptionType.receiveTimeout:
        return '响应超时';
      case DioExceptionType.sendTimeout:
        return '发送超时';
      case DioExceptionType.badCertificate:
        return '证书验证失败';
      case DioExceptionType.badResponse:
        return '服务器异常响应';
      case DioExceptionType.cancel:
        return '请求取消';
      case DioExceptionType.connectionError:
        return '网络连接失败';
      default:
        return '未知网络错误';
    }
  }


error info:

  👉 请求发起: https://xxx.xxx.xxx.xxx/app/appLogin
├─ Headers: {Content-Type: application/json; charset=UTF-8, Accept: application/json, X-Client-Type: flutter_app}
└─ Data: {userName: 3000_1000001, password: 332211, authCode: YjAZ, deviceInfo: {platform: Android, version: 10, uuid: 设备唯一标识}}
      ‼️ 完整错误堆栈：
      错误类型: DioExceptionType.connectionError
      错误信息: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.
      请求地址: https://xxx.xxx.xxx.xxx/app/appLogin
      请求方法: POST
      请求头: {Content-Type: application/json; charset=UTF-8, Accept: application/json, X-Client-Type: flutter_app}
      请求体: {userName: 3000_1000001, password: 332211, authCode: YjAZ, deviceInfo: {platform: Android, version: 10, uuid: 设备唯一标识}}
      响应状态: null
      响应头: null
      响应体: null
      底层错误: null
