### ISSUE TITLE
Does not work on Windows Server 2016.

### ISSUE THREAD

**Issue by DmitryNX** [cfug/dio#1992]
### Package

dio

### Version

5.3.0

### Operating-System

Windows

### Output of `flutter doctor -v`

Everything is ok.

### Dart Version

3.0.2

### Steps to Reproduce

Run the App with a simple code like this:
```
import 'package:dio/dio.dart';

final dio = Dio();

void getHttp() async {
  final response = await dio.get('http://localhost:51111/hello');
  print(response);
}
```
In my case, I tried to connect to localhost via http protocol.
On the another PC (Windows 7 and 10) it works properly.

### Expected Result

Getting data before showing the app.

### Actual Result

The App has started but not shown. In a task manager You can see the app`s background process which uses more resources of CPU than usual.

**Comment by AlexV525** [comment]
It's more sounds like a configuration problem. There are nothing configured for the Windows platform in our package.

**Comment by AlexV525** [comment]
Similar issues: https://github.com/docker/for-win/issues/2150

Closing as we cannot provide further actions.
