### ISSUE TITLE
DioException [bad response]: The request returned an invalid status code of 500.

### ISSUE THREAD

**Issue by jamalalloh** [cfug/dio#1993]
### Package

dio

### Version

5.3.3

### Operating-System

Android

### Output of `flutter doctor -v`

[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.2 on channel stable at C:\Users\jamal\Downloads\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (7 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\jamal\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.83.0)
    • VS Code at C:\Users\jamal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 117.0.5938.149
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.60

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

### Dart Version

3.0.1

### Steps to Reproduce

Future<dynamic> bookAppointment(
      String date, String day, String time, int doctor, String token) async {
    try {
      var response = await Dio().post('http://10.0.2.2:8000/api/appointment',
          data: {
            'date': date,
            'day': day,
            'time': time,
            'doctor_id': doctor,
          },
          options: Options(headers: {'Authorization': 'Bearer $token'}));
      if (response.statusCode == 200 && response.data != 'data') {
        return response.statusCode;
      }
    } catch (error) {
      return (error);
    }
  }

### Expected Result

I/flutter ( 5871): DioException [bad response]: The request returned an invalid status code of 500.

### Actual Result

![dioexception](https://github.com/cfug/dio/assets/95585900/579cb2c3-a259-458a-9293-f6042a8ee7ec)

**Comment by ueman** [comment]
A 500 status code indicates a backend failure, not an issue with the dio library.
