### ISSUE TITLE
 The request headers key changes to lowercase

### ISSUE THREAD

**Issue by hnsycsxhzcsh** [cfug/dio#2002]
### Request Statement

When I made a network request, Authorization was added to the network request headers, but the result was changed to lowercase.
example：
var dio = Dio(); Options options = Options(headers: {"Authorization": "Basic xxx"}); Response response = await dio.get(“xxx” options: options, );

![276073621-af600c08-56c8-47ab-9610-e58857286808](https://github.com/cfug/dio/assets/22562281/0c4814b4-d4bf-4267-89cf-7aa9a2e49fae)

**Comment by ueman** [comment]
HTTP headers are defined as being case insensitive, which means `Authorization` and `authorization` are identical.

What exactly, is your problem @hnsycsxhzcsh ?

**Comment by hnsycsxhzcsh** [comment]
The way I write it is：

dio.options.headers["Authorization"] =  "Basic <token&gt;";



But the reality is：





I want the argument in the request header to be Authorization instead of authorization. What should I do?



陈少华
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cfug/dio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月21日(星期六) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfug/dio]  The request headers key changes to lowercase (Issue #2002)





 
HTTP headers are defined as being case insensitive, which means Authorization and authorization are identical.
 
What exactly, is your problem @hnsycsxhzcsh ?

**Comment by hnsycsxhzcsh** [comment]
The way I write it is：

dio.options.headers["Authorization"] =  "Basic <token&gt;";



But the reality is：





I want the argument in the request header to be&nbsp;Authorization instead of authorization. What should I do?



陈少华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfug/dio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月21日(星期六) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfug/dio]  The request headers key changes to lowercase (Issue #2002)





 
HTTP headers are defined as being case insensitive, which means Authorization and authorization are identical.
 
What exactly, is your problem @hnsycsxhzcsh ?

**Comment by ueman** [comment]
I understand that, but why does it need to start with an upper case A?

**Comment by hnsycsxhzcsh** [comment]
The server interface is not compatible with lowercase, the server cannot change, the client needs to pass uppercase


陈少华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfug/dio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cfug/dio]  The request headers key changes to lowercase (Issue #2002)





 
I understand that, but why does it need to start with an upper case A?

**Comment by AlexV525** [comment]
I've tried to solve this multiple times and ended up with a complicated but different solution every time. I'll try again to see if I can make any difference this time.

P.S. We've been involved with customized headers and headers from the io package, which causes a significant amount of transformation code has be written during the implementation.
