### ISSUE TITLE
support forcing transport type

### ISSUE THREAD

**Issue by arlakay** [cfug/dio#2004]
### Request Statement

in native android we can forcing http connection over cellular data / wifi using okhttp3
this example snippet code
`.addTransportType(NetworkCapabilities.TRANSPORT_CELLULAR)`

my question, is it dio have configuration to force connection over cellular/wifi?

```[tasklist]
### Tasks
```

**Comment by kuhnroyal** [comment]
You can do that with the https://pub.dev/packages/native_dio_adapter for iOS but I am not sure about the Android side which uses https://pub.dev/packages/cronet_http

**Comment by ueman** [comment]
As said in the comment above, dio itself can't and won't support this usecase. It is possible with the native adapter, or you can manually check what connection is currently active and make requests accordingly.

**Comment by arlakay** [comment]
Hi @kuhnroyal , thanks for your information.
do you have example/reference for native dio adapter for ios, that forces cellular data?

I can't find any configuration that supports my issue above.
cronet_http doesn't have configuration-related force cellular data with cronet engine.
I don't think, native dio adapter also has this configuration for forcing cellular data.

At this time, I think the only solution on native side, using platform-specific channel

here is my reference on Android developer web.
https://developer.android.com/reference/android/net/NetworkRequest.Builder

**Comment by kuhnroyal** [comment]
Yea, you can actually only disallow cellular access with `cupertino_http` but you can not force it, my bad.
