### ISSUE TITLE
[Documentation] Replace HttpAdapter names on README

### ISSUE THREAD

**Issue by deandreamatias-worldline** [cfug/dio#2012]
### Request Statement

1. The class `BrowserClientAdapter ` do not exist on `package:dio/browser.dart` but on README HttpClientAdapter section, show `BrowserClientAdapter ` like example.
2. The class `IOClientAdapter` do not exist on `package:dio/io.dart` but on README HttpClientAdapter section, show `IOClientAdapter` like example.

### Solution Brainstorm

Replace `IOClientAdapter` to `IOHttpClientAdapter` on both README
Replace `BrowserClientAdapter ` to `BrowserHttpClientAdapter ` on both README

**Comment by someshwar16** [comment]
Hi, I can do this work can I be assigned to this issue?

**Comment by ueman** [comment]
@someshwar16 feel free to work on this. There's no need to be assigned. Thank you!
