### ISSUE TITLE
The request finished correctly , but Exception in the interceptor stop the app 

### ISSUE THREAD

**Issue by MayaBloodsAI** [cfug/dio#2017]
### Package

dio

### Version

5.3.3

### Operating-System

Web

### Output of `flutter doctor -v`

```shell
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3570], locale en-IL)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.83.1)
[√] Connected device (3 available)
[√] Network resources
```

### Dart Version

3.1.0

### Steps to Reproduce

I  run post or get request (happened in both):
`
 Dio dio = Dio(
    BaseOptions(baseUrl: URLController.endpoint),
  );

Response response = await dio.get(path);
`

I can print the data everything work 100%...

But.. the application stop with Exception no error message present.. I just can see this line in the interseptor.dart file:

![image](https://github.com/cfug/dio/assets/98014743/bbd95d29-508c-4cb2-aa0c-b858fe3fb947)

### Expected Result

App continue normally

### Actual Result

I get Exception with out any explanation even thought the request finished and the request.data is as expected

**Comment by kuhnroyal** [comment]
This may be related to https://github.com/cfug/dio/issues/1953. Cam you try running without debugger or in release mode?
