### ISSUE TITLE
Download  receiveTimeout 

### ISSUE THREAD

**Issue by QixianWu** [cfug/dio#2022]
### Package

dio

### Version

5.3.3

### Operating-System

Android

### Output of `flutter doctor -v`

```shell
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (4 available)
```

### Steps to Reproduce

In previous versions, it was only necessary to set the receiveTimeout of the Download Options to 0 to download without timeout. Now, after changing to the Duration type, the time cannot be unlimited

```dart
Future downloadFile(urlPath, savePath,
      {CancelToken? cancelToken, ProgressCallback? onReceiveProgress}) async {
    Response? response;
    response = await dio.download(urlPath, savePath,
        cancelToken: cancelToken,
        options: Options(receiveTimeout: Duration(seconds: 0)),
        onReceiveProgress: onReceiveProgress ??
            (int count, int total) {
              logI("$count $total");
            });
    return response;
  }
```

### Expected Result

download success

### Actual Result

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [receive timeout]: The request took longer than 0:00:00.000000 to receive data. It was aborted.

**Comment by kuhnroyal** [comment]
You should be able to set it to `null` now.

**Comment by QixianWu** [comment]
> 您现在应该可以将其设置`null`。

I have tried to set it to 'null', but it defaults to using the 'receiveTimeout' of the option for the single instance 'dio', so my current method can only set it to a relatively large time

**Comment by kuhnroyal** [comment]
Oh, right so you can not override it in the `Options` passed to a single request if you have a different duration set it in the `BaseOptions`?
You should be able to set it to `null` on the `BaseOptions`?

Do I understand this correctly?

**Comment by QixianWu** [comment]
> Oh, right so you can not override it in the `Options` passed to a single request if you have a different duration set it in the `BaseOptions`? You should be able to set it to `null` on the `BaseOptions`?
> 
> Do I understand this correctly?

Yes, Unless a new `Dio` is instantiated. For me, the entire app uses the same single instance `Dio`, and the `receiveTimeout` set by the Base Options is 15 seconds.

**Comment by AlexV525** [comment]
So the most straight-forward solution would be to ignore zero duration? @ueman

**Comment by kuhnroyal** [comment]
Yea I agree
