### ISSUE TITLE
XMLHttpRequest error in flutter web

### ISSUE THREAD

**Issue by Shahriyar13** [cfug/dio#2026]
### Package

dio

### Version

5.3.3

### Operating-System

Web

### Output of `flutter doctor -v`

```shell
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2428], locale en-US)
    • Flutter version 3.13.6 on channel stable at C:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\SDK\Android
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.106
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

### Dart Version

3.1.3

### Steps to Reproduce

It's works on iOS, macOS, Windows and Android successfully

Send a Post request from Web (Chrome)
![Screenshot 2023-11-07 134816](https://github.com/cfug/dio/assets/33436153/7c551ede-d5f9-447b-a7bb-06076b785540)
Header:
{Content-Type: application/json, Accept: */*, Access-Control-Allow-Origin: *, Access-Control-Allow-Credentials: true, Access-Control-Allow-Headers: Origin, Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, locale, Cookie, X-CSRF-TOKEN, Accept
, X-XSRF-TOKEN, Access-Control-Allow-Origin, Access-Control-Allow-Methods: GET, POST, OPTIONS, DELETE, PUT}

### Expected Result

Call API

### Actual Result

DioExceptionType.connectionError
The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer.
![Screenshot 2023-11-07 135040](https://github.com/cfug/dio/assets/33436153/15f000af-75ec-423a-a257-20bb49d07430)

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/tree/main/dio#cross-origin-resource-sharing-on-web-cors

**Comment by Shahriyar13** [comment]
I read documents and I applied everything in both server-side and flutter dio headers, but it's not fixed

**Comment by AlexV525** [comment]
We can help investigate the issue if there is a minimal reproducible example that we can run. Before that, there was nothing we could do with the given info.
