### ISSUE TITLE
Track request duration

### ISSUE THREAD

**Issue by simplenotezy** [cfug/dio#2027]
### Request Statement

I'd like a way to track request durations. Initially I thought I could simply create an interceptor that would keep track of each request and then using `StopWatch`. However, it's been proven to log much longer duration than ngrok is reporting.

This is the code that reports invalid request duration (e.g. code reports 600ms, but ngrok reports 53ms).

```dart
import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';

String generateMd5(String input) {
  return md5.convert(utf8.encode(input)).toString();
}

class RequestTimeInterceptor extends Interceptor with Loggable {
  String get debugLogContext => 'SlowRequests';

  Map<String, Stopwatch> _requests = {};

  _isGraphqlRequest(RequestOptions options) {
    return options.path.contains('graphql');
  }

  _getRequestId(RequestOptions options) {
    if (_isGraphqlRequest(options)) {
      final encoded = _getRequestName(options) + options.data['variables']?.toString();
      final id = generateMd5(encoded);

      return id;
    }

    return generateMd5(options.path + options.data.toString());
  }

  _getRequestName(RequestOptions options) {
    if (_isGraphqlRequest(options)) {
      return options.data['operationName'] ?? 'Unknown GraphQL request';
    }

    return options.path;
  }

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    _requests[_getRequestId(options)] = Stopwatch()..start();
    return super.onRequest(options, handler);
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    _requestStopped(response.requestOptions);

    return super.onResponse(response, handler);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    _requestStopped(err.requestOptions);

    return super.onError(err, handler);
  }

  /// Called when a request is stopped (either by error or success)
  _requestStopped(RequestOptions options) {
    final stopWatch = _requests[_getRequestId(options)];

    stopWatch?.stop();

    recordLog('Request to ${_getRequestName(options)} took ${stopWatch?.elapsedMilliseconds} ms');

    _requests.remove(_getRequestId(options));
  }
}

```

**Comment by simplenotezy** [comment]
I should note that we are using the http2 adapter by the way

**Comment by AlexV525** [comment]
As far as I know, ngrok is a backend service, correct? What makes you think that clients request duration should equal to server's?

**Comment by kuhnroyal** [comment]
You can look at how Sentry traces the time here: https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/breadcrumb_client_adapter.dart

**Comment by simplenotezy** [comment]
> As far as I know, ngrok is a backend service, correct? What makes you think that clients request duration should equal to server's?

They report the response time it takes from sending the request to receiving the answer. Same as I would expect this interceptor to do. I also tried verifying by proxying through Charles; same incorrect results for some reason. And it's not just a few ms. It's a request taking 100ms is sometimes tracked as 600ms with stopwatch; so I am simply trying to understand what layers might be in between the interceptors and what can be done to get more accurate reports

**Comment by simplenotezy** [comment]
> You can look at how Sentry traces the time here: https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/breadcrumb_client_adapter.dart

Nice! Will check it out

**Comment by simplenotezy** [comment]
> so I am simply trying to understand what layers might be in between the interceptors and what can be done to get more accurate reports

Seems like this answers my question: https://github.com/getsentry/sentry-dart/blob/main/dio/lib/src/breadcrumb_client_adapter.dart#L12

**Comment by AlexV525** [comment]
@kuhnroyal Did we match the circumstance to close the issue? Could we implement a duration interceptor or a general adapter on our own?

**Comment by kuhnroyal** [comment]
I don't know, we could add the timing to the `LogInterceptor`. Other than that, I see no point.
