### ISSUE TITLE
DELETE requests doesn't work on Android with native_dio_adapter

### ISSUE THREAD

**Issue by OperKH** [cfug/dio#2035]
### Package

native_dio_adapter

### Version

1.1.0

### Operating-System

Android

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.16.0, on Fedora Linux 39 (KDE Plasma) 6.3.13-200.fc38.x86_64, locale en_GB.UTF-8)
    • Flutter version 3.16.0 on channel stable at /mnt/P/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (6 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/oper/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at:
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Android Studio (version unknown)
    • Android Studio at /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir = /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.76.0

[✓] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Dart Version

3.2.0

### Steps to Reproduce

Create dio client with `NativeAdapter`
```dart
final Dio dioClient = Dio();
dioClient.httpClientAdapter = NativeAdapter();
```

Make a delete request to your http server
```dart
dioClient.delete('url');
```

Check logs on your http server

### Expected Result

Server must receive `DELETE` request

### Actual Result

Server receive `GET` request

**Comment by OperKH** [comment]
`DELETE` request works with `dio_http2_adapter` or without `httpClientAdapter`

**Comment by kuhnroyal** [comment]
I somehow doubt that but in any case, there is nothing that we do on the dio side in that regard. 
Probably ask here: https://pub.dev/packages/cronet_http with a reproducible sample.

**Comment by AlexV525** [comment]
This is because the `CronetClient` didn't set the request method when making requests. After `builder.setHttpMethod(request.method.toJString())` was called, the `DELETE` requests were sent successfully.

There is nothing related to Dio tho. Please submit issues with the `cronet_http` package.

**Comment by kuhnroyal** [comment]
https://pub.dev/packages/cronet_http had a new release 0.4.2 which fixes the HTTP methods. @AlexV525 Do we want to bump this in dio?

**Comment by AlexV525** [comment]
> https://pub.dev/packages/cronet_http had a new release 0.4.2 which fixes the HTTP methods. @AlexV525 Do we want to bump this in dio?

I just checked that we have `^0.4.0` so `flutter pub upgrade` would be enough for users.
