### ISSUE TITLE
[native_dio_adapter] Support cronet_http_embedded

### ISSUE THREAD

**Issue by vanyasem** [cfug/dio#2042]
### Request Statement

`cronet_http` depends on Google Play Services

There is a separate package called [cronet_http_embedded](https://pub.dev/packages/cronet_http_embedded) which has no such dependency, but is bigger in size

### Solution Brainstorm

I'd like to propose creating a separate package `native_dio_adapter_embedded` that would depend on `cronet_http_embedded` instead of `cronet_http`. We have to support devices that do not have Google Play Services installed.

**Comment by AlexV525** [comment]
Although I wrote the tool to create the `cronet_http_embedded` package, I don't think we have a proper way to handle this until Dart team can make its publishing automatic, which can at least avoid the version difference between them.

**Comment by AlexV525** [comment]
ref: https://github.com/dart-lang/http/issues/1047#issuecomment-1825765612

**Comment by vanyasem** [comment]
@AlexV525 thank you for your valuable input! I guess it makes sense to postpone my suggestion until the publishing is made automatic

**Comment by ueman** [comment]
Cronet embedded is now integrated in the cronet lib. I'm closing this since there's no longer any action needed for this library.
