### ISSUE TITLE
Access response data type <T> in Interceptor.

### ISSUE THREAD

**Issue by huynhmytuandev** [cfug/dio#2061]
### Request Statement

I'm using dio with auto-generated client code retrofit. For some case api response 204 status code. I have to handle and transform the response to 200 with empty data type of <T> interceptor before return it. 

### Solution Brainstorm

Could you please provide somethings like: 
```dart
class OkHttpInterceptor<T> implements Interceptor<T> {
  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    return handler.next(err);
  }

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    return handler.next(options);
  }

  @override
  void onResponse(Response<T> response, ResponseInterceptorHandler handler) {
    final dataType = response.typeOf();

    if ([204, 205].contains(response.statusCode)) {
      response.statusCode = 200;
      switch (dataType) {
        case String:
          response.data = '';
          break;
        case List:
          response.data = [];
          break;
        case Map:
          response.data = {};
          break;
        default:
          response.data = null;
          break;
      }
      return handler.next(response);
    }

    return handler.next(response);
  }
}

```

**Comment by AlexV525** [comment]
The `T` here does not seen to have any meaning for me. I'm not familar with how `retrofit` handles responses too. For regular dio requests, consider adding the `T` into the extra field and obtain it in the interceptor. You may also try to provide a minimal use case so we take have a better understanding about your demand.

**Comment by AlexV525** [comment]
Simply fallback to an empty list after `_result.data?` should handle this.

**Comment by huynhmytuandev** [comment]
Yes, I already done with it, just want to request this feature for another use case need to access  response type of `T` in interceptor.
