### ISSUE TITLE
Dio on Windows : Invalid media type: expected no more input.

### ISSUE THREAD

**Issue by LastMaggot** [cfug/dio#2063]
## Environment Information

| Library/Tool      | Version                  |
| ------------------ | ------------------------ |
| Dio                | 5.4.0                    |
| Flutter            | 3.13.9 • channel stable  |
| Dart               | 3.1.5                    |
| Operating System   | Windows 11               |
| Development Tool   | Android Studio           |

## Error Message
![ErrorMessage](https://github.com/cfug/dio/assets/122156291/3a1039a2-dd62-4968-9e1e-595fee8b161e)
![StackTrace](https://github.com/cfug/dio/assets/122156291/cf1fa7fa-13e0-49d8-867e-3bf81bd9be86)

## MyCode
![image](https://github.com/cfug/dio/assets/122156291/08276c6a-0c9e-415c-a9e9-f13a92f1fed2)

I try following settings with ChatGPT's help. But it still doesn't work.  
![image](https://github.com/cfug/dio/assets/122156291/7aad6502-dae4-45c6-9114-d74702fefd47)

I test the same code on Edge, it works successfully.

```[tasklist]
### Tasks
```

**Comment by LastMaggot** [comment]
I also used a Interceptor to test it.
onRequest is executed successfully.
![image](https://github.com/cfug/dio/assets/122156291/582cfcac-b2b9-4bfe-bd6b-730da318e807)
![image](https://github.com/cfug/dio/assets/122156291/16996b75-a84b-4bd8-9923-9a1bb4ca0e8d)
Thanks for any help given.

**Comment by AlexV525** [comment]
So it looks like your response contains a malformed content-type. Could you verify that?

**Comment by LastMaggot** [comment]
@AlexV525 Thank you for your advice; it helped me resolve the issue. I'm truly grateful for your assistance!
