### ISSUE TITLE
[Web] ERROR_TYPE: DioExceptionType.connectionError

### ISSUE THREAD

**Issue by LambGe** [cfug/dio#2074]
### Package

dio

### Version

5.4.0

### Operating-System

Web

### Dart Version

3.2.2

### Steps to Reproduce

A GET request.

### Expected Result

Request normal.

### Actual Result

- ERROR_TYPE: DioExceptionType.connectionError
 ERROR_MSG: The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.

Btw，requests work properly on iOS and Android platforms.

**Comment by AlexV525** [comment]
Please provide a minimal reproducible example.

**Comment by LambGe** [comment]
- URL: https://demo.fortex.com/BOAPI/v1/2FA/Enable2FA
│ 💡 - METHOD: GET
│ 💡 - HEADER:
│ 💡 {
│ 💡   "os" : "web 1.0",
│ 💡   "ver" : "1.2.75",
│ 💡   "app_sys" : "1"
│ 💡 }

**Comment by LambGe** [comment]
![d63878733ee22f9ff5bd184c97999e35](https://github.com/cfug/dio/assets/119394755/39c7dc22-2c07-4392-8d89-5a6510d2b04a)
This is also normal in Postman.

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/tree/main/dio#cross-origin-resource-sharing-on-web-cors
