### ISSUE TITLE
Flutter web deployment

### ISSUE THREAD

**Issue by longfit** [cfug/dio#2075]
### Package

dio

### Version

5.3.3

### Operating-System

Web

### Output of `flutter doctor -v`

```shell
lutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu 23.10 6.5.0-14-generic, locale en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/ykwings/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/ykwings/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/ykwings/android-sdk
    • Java binary at: /home/ykwings/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/ykwings/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-14-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.
```

### Dart Version

3.2.3

### Steps to Reproduce

my flutter web app work properly at flutter chrome with "disable-web-security"
I deploy to nginx only shown login page
,press button no repsone
chrome development tools shown error , 

Exception while loading service worker: Error: Service Worker API unavailable.
The current context is NOT secure.
Read more: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:130:11)
    at FlutterLoader.loadEntrypoint (flutter.js:360:33)
    at VM50:4:23
(anonymous) @ flutter.js:362
login:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
login:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

![Screenshot from 2023-12-22 11-59-38](https://github.com/cfug/dio/assets/4157794/ee086cc1-bbe0-4483-b81f-a5c05ae71c2e)

### Expected Result

get nodejs  api server json data
e.g longfit.f3322.org:8100/api/user/login

### Actual Result

press login press no response

**Comment by AlexV525** [comment]
Please provide a minimal reproducible example.
