### ISSUE TITLE
Response Header is missing except content-length & content-type

### ISSUE THREAD

**Issue by rnp0728** [cfug/dio#2105]
### Package

dio

### Version

5.4.0

### Operating-System

Linux

### Output of `flutter doctor -v`

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.8, on Pop!_OS 22.04 LTS
    6.6.6-76060606-generic, locale en_US.UTF-8)
    • Flutter version 3.16.8 on channel stable at
      /home/rnp/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (7 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/rnp/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.21+9-post-Ubuntu-0ubuntu122.04)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.85.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS
      6.6.6-76060606-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.224

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Dart Version

3.2.5

### Steps to Reproduce

Try sending Cookie's from backend, then the headers are missing
![image](https://github.com/cfug/dio/assets/98372124/d4d0bc88-91b5-4710-82ca-1fb46b824e82)

### Expected Result

I should get the set-cookie data from dio response headers.
![image](https://github.com/cfug/dio/assets/98372124/e976da27-b559-444d-9bdc-abac34d1a4d0)

### Actual Result

![image](https://github.com/cfug/dio/assets/98372124/9663dc32-efeb-4d1e-b116-ffe2909afe17)

// Response Header in Web
![image](https://github.com/cfug/dio/assets/98372124/2a0b32b3-555f-479b-923b-a756e383757e)

**Comment by rnp0728** [comment]
This is a web based project so, ignore the android studio / toolchain related errors,

**Comment by AlexV525** [comment]
On the Web, cookies are implicitly handled by the browser. All you need to do is to enable `BrowserHttpClientAdapter.withCredentials`.

**Comment by rnp0728** [comment]
DioError ║ DioExceptionType.connectionError
 The connection errored: The XMLHttpRequest onError callback was called. This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.
 
 New error comes up due to this code
```
 _dio.httpClientAdapter = BrowserHttpClientAdapter(withCredentials: true);
```

**Comment by AlexV525** [comment]
As the error stated:

> This typically indicates an error on the network layer. This indicates an error which most likely cannot be solved by the library.

Closing as the issue becomes unactionable.

**Comment by rnp0728** [comment]
@AlexV525 I am sending a api request to the baceknd of the server and in the response i am getting 10 response header which also includes a cookie, but currently i am able to fetch only 2 of them (...mention the header names). ....add the server.js file in refrence.

**Comment by Team4pInfinite** [comment]
i am facing to the same error. I have checked in browser with 10 response header but in dio debug only log 2 property content-type, content-length

**Comment by nohli** [comment]
@rnp0728 in our case [this](https://github.com/dart-lang/http/issues/726#issuecomment-1433169316) was the fix.
