### ISSUE TITLE
Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by AlexV525** [cfug/dio#2115]
### Package

dio

### Version

5.4.1

### Operating-System

Android

### Steps to Reproduce

1. Set the `receiveTimeout` as 1 second when the request should take 2.
2. Cancel the request before the 1 second.

### Expected Result

No exceptions.

### Actual Result

```console
The following message was thrown:
Bad state: Cannot add event after closing

When the exception was thrown, this was the stack: 
#1      handleResponseStream.watchReceiveTimeout.<anonymous closure> (package:dio/src/response/response_stream_handler.dart:48:20)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 4 frames from class _Timer, dart:async, and dart:async-patch)
```

**Comment by Reprevise** [comment]
Can this be released in a new version of Dio?

**Comment by AlexV525** [comment]
> Can this be released in a new version of Dio?

Every unreleased change would be released in the next version, generally speaking.
