### ISSUE TITLE
Add a response time to the response result

### ISSUE THREAD

**Issue by laterdayi** [cfug/dio#2129]
### Request Statement

Add a response time to the response result
There is no interface response time in status code

**Comment by laterdayi** [comment]
The response time of each interface needs to be obtained from the interceptor
@AlexV525

**Comment by laterdayi** [comment]
Whether a response time can be returned in response

**Comment by AlexV525** [comment]
You can write interceptors to implement response time calculation. This is not the main scope of the library and can be easily implemented. See also: #2027.
