### ISSUE TITLE
Support flutter web for native_dio_adapter

### ISSUE THREAD

**Issue by ABausG** [cfug/dio#2133]
### Request Statement

Right now Flutter Web Projects fail to build as there are import chains pointing towards dart:ffi

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code -2:
           ../../../../.pub-cache/hosted/pub.dev/cupertino_http-1.3.0/lib/src/cupertino_api.dart:30:8:
           Error: Dart library 'dart:ffi' is not available on this platform.
           import 'dart:ffi';
                  ^
           Info: The unavailable library 'dart:ffi' is imported through these packages:
           
               main.dart => package:my_app_packages => package:native_dio_adapter => package:cronet_http => package:jni => dart:ffi

```

**Comment by AlexV525** [comment]
Please submit related issues to the https://github.com/dart-lang/http repo.

**Comment by ABausG** [comment]
@AlexV525 This is not about the dart-lang/http client though but about `native_dio_adapter`

We recently added `native_dio_adapter` to improve the http adapter on ios builds. Unfortunately that now breaks our web builds due to the error that I added to the description.

I think it would be awesome if this plugin could be used when also using Flutter web. So adding it to this section:

https://github.com/cfug/dio/blob/b7d7f348970745051bb0dfc98e0953fa5274ba28/plugins/native_dio_adapter/pubspec.yaml#L33-L38

As well as making sure that a working http client is being used on flutter web.

As a first step it would be great to just get compiling working so lines where `NativeAdapter()` is created could be checked with `!kIsWeb`

**Comment by kuhnroyal** [comment]
The native adapter does not support web, you can use the default `BrowserHttpClientAdapter` on web.
You can easily switch the implementation of the adapter yourself depending on the platform.

**Comment by ABausG** [comment]
Yes but the issue comes up at compile time

**Comment by kuhnroyal** [comment]
You can use a conditional import in the same way `dio` does it be default, you only have to change the adapters. See the imports here https://github.com/cfug/dio/blob/main/dio/lib/src/adapter.dart#L10 and the `createAdapter()` function.

**Comment by ABausG** [comment]
I'll check again tomorrow as I also think that @nottmey has been trying to find a solution for this problem.

Right now the problem showed up when running `flutter build web` and point to an issue within pub getting the dependencies so even before it would be solvable with a conditional import.
I'll also see if I can get an example going where this is can be easily reproduced!
