### ISSUE TITLE
DioException HttpException: Connection closed before response was received

### ISSUE THREAD

**Issue by LambGe** [cfug/dio#2135]
### Package

dio

### Version

5.4.1

### Operating-System

Android, iOS

### Dart Version

3.3.0

### Steps to Reproduce

Future.wait([
      _getUserInfo(),
      _getCurrentServerInfo()
    ])

### Expected Result

Both requests can succeed

### Actual Result

One interface is successful, and the other one reports an error.

**Comment by AlexV525** [comment]
This typically means the connection is not stable and ends by the underlying platform. There is nothing related to the Dio itself.
