### ISSUE TITLE
302没有带上cookie

### ISSUE THREAD

**Issue by yanweimin7** [cfug/dio#2180]
### Package

dio

### Version

5.2.1+1

### Operating-System

Android

### Adapter

Default Dio

### Output of `flutter doctor -v`

```shell
[✓] Flutter (Channel stable, 3.10.6, on macOS 14.4 23E214 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (version 2023.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.88.0)
```

### Dart Version

3.0.6

### Steps to Reproduce

1. 调用一个get请求，比如url https://www.xxx.com/a/b ,  该url要带上cookie才能返回正确内容，否则会返回302， 
2. 当第一次调用时 ，由于没有带上cookie，因此header里面会返回set cookie,  如
```
Set-Cookie:
EO-Bot-Session=leoiD3kj4ttGbnfyzIHIgzCpD0SEOWCOLah7puYe9OfU7TF07893ChR-P2geuwAs; max-age=7800; Domain=.xxx.com; path=/; HttpOnly

Set-Cookie:
EO-Bot-SessionId=17523055444970748937; max-age=7800; Domain=.xxx.com; path=/; HttpOnly
Set-Cookie:
EO-Bot-Token=; max-age=3900; Domain=.xxx.com; path=/;
```
且Location依然是/a/b

2 . 此时dio默认会重定向重新请求  https://www.xxx.com/a/b, 但没有带上上次返回的cookie，导致一直302。

### Expected Result

期望遇到302重定向前，从上次response取出cookie，作为下一次的request header

### Actual Result

302没有带上上次response的cookie

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/blob/777b29df01f39242ed81585bd90d9f3024f9932e/plugins/cookie_manager/test/cookies_test.dart#L91

这里的单测没有出问题，请利用 httpbun.com 提供最小复现 demo。
