### ISSUE TITLE
Improve Exception Detailing for Dio Package

### ISSUE THREAD

**Issue by Ultranmus** [cfug/dio#2188]
### Package

dio

### Version

5.4.1

### Operating-System

Android

### Adapter

Default Dio

### Output of `flutter doctor -v`

```shell
Flutter (Channel stable, 3.19.3, on Microsoft Windows [Version 10.0.22631.3447], locale en-IN)
    • Flutter version 3.19.3 on channel stable at C:\Users\User\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (6 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34114.132
    • Windows 10 SDK version 10.0.19041.0
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[!] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 123.0.6312.122
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 123.0.2420.97

[√] Network resources
    • All expected network resources are available.
```

### Dart Version

3.3.1

### Steps to Reproduce

Call youtube data api to fetch youtube videos from a particular channel
```
import 'package:dio/dio.dart';

String? pageToken = "CAUQAA";

void fetchYouTubeVideos() async {
  String apiUrl = "https://youtube.googleapis.com/youtube/v3/search";
  String apiKey = "[YOUR_API_KEY]";
  String channelId = "demo_channel";
  int maxResults = 10;

  try {
    Map<String, dynamic> queryParameters = {
      "key": apiKey,
      "channelId": channelId,
      "maxResults": maxResults,
    };

    if (pageToken != null) {
      queryParameters["pageToken"] = pageToken;
    }

    Response response = await Dio().get(
      apiUrl,
      queryParameters: queryParameters,
      options: Options(
        headers: {
          "Accept": "application/json",
        },
      ),
    );

    // Handle response
    print(response.data);
  } catch (error) {
    print("Error: $error");
  }
}
```

### Expected Result

When quota for youtube data api exceed it give this type of response when using http

"{error: {code: 403, message: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>., errors: [{message: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>., domain: youtube.quota, reason: quotaExceeded}]}}"

So i expected similar kind of error from Dio

### Actual Result

The exception thrown by Dio did not provide sufficient information to diagnose the problem. Instead, it simply stated:

"This exception was thrown because the response has a status code of 403 and RequestOptions.validateStatus was configured to throw for this status code. The status code of 403 has the following meaning: 'Client error - the request contains bad syntax or cannot be fulfilled'. Read more about status codes at [MDN Status Codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code."

This error message lacks the context needed to understand the root cause of the issue. Therefore, I suggest enhancing the Dio package to provide more explanatory error messages in cases like this.

**Comment by kuhnroyal** [comment]
The http library is just outputting the plain body as string.
You can access this via `error.response?.data.toString()` for any `DioException`.
Adding this to the exception message by default may be problematic since the body content might be way too large or contain PII.
