### ISSUE TITLE
Cookie manager path match error

### ISSUE THREAD

**Issue by wilinz** [cfug/dio#2195]
### Package

cookie_manager

### Version

latest

### Operating-System

Android, iOS, Web, MacOS, Linux, Windows

### Adapter

Default Dio

### Steps to Reproduce

The version of the cookie manager that relies on cookiejar needs to be upgraded to fix the cookie path matching bug. For details, see [https://github.com/flutterchina/cookie_jar/commit/78c2246b18d6c05b1fbd743e8515af404ffca146](https://github.com/flutterchina/cookie_jar/commit/78c2246b18d6c05b1fbd743e8515af404ffca146)

Please update the cookiejar dependency to the latest version to solve the problem

Unit Test:

```dart
import 'package:flutter_test/flutter_test.dart';

bool _isPathMatch(String urlPath, String cookiePath) {
  final urlPathLowerCase = urlPath.toLowerCase();
  final cookiePathLowerCase = cookiePath.toLowerCase();
  if ('/' == cookiePath || urlPathLowerCase == cookiePathLowerCase) {
    return true;
  }
  if (urlPathLowerCase.startsWith(cookiePathLowerCase)) {
    final temp = urlPathLowerCase.substring(cookiePathLowerCase.length);
    return temp.startsWith('/');
  }
  return false;
}

main() {
  test('test cookie path match', () {
    final result = _isPathMatch("/student/sso/login", "/student/");
    expect(result, true);
  });
}

```

### Expected Result

true

### Actual Result

false

**Comment by AlexV525** [comment]
https://github.com/cfug/dio/pull/2196#issuecomment-2067983568
