### ISSUE TITLE
Update for wasm

### ISSUE THREAD

**Issue by sgehrman** [cfug/dio#2213]
### Package

dio

### Version

1.2.3

### Operating-System

Linux

### Adapter

Default Dio

### Output of `flutter doctor -v`

```shell
duh
```

### Dart Version

2.2.1

### Steps to Reproduce

doesn't compile with wasm

### Expected Result

fix the dart:html problem

### Actual Result

doesn't compile

**Comment by AlexV525** [comment]
Please do not spam the thread with incorrect information. Thanks.
