### ISSUE TITLE
Remove the message 'The request was manually cancelled by the user.'  for canceltoken.cancel()

### ISSUE THREAD

**Issue by someshswami9** [cfug/dio#2217]
### Request Statement

Dio can show the message which is sent by user or if don't then don't show the message as that is not acceptable . as random message is visible on users screen. 

### Solution Brainstorm

Just remove the hardcoded message from Dio

factory DioException.requestCancelled({
    required RequestOptions requestOptions,
    required Object? reason,
    StackTrace? stackTrace,
  }) =>
      DioException(
        type: DioExceptionType.cancel,
        message: 'The request was manually cancelled by the user.',
        requestOptions: requestOptions,
        response: null,
        error: reason,
        stackTrace: stackTrace,
      );

**Comment by AlexV525** [comment]
We don't show the message to the screen. As a good practice, showing raw exceptions on screen could be a bad solution.
