### ISSUE TITLE
Issue with API call when android device is connected via wifi.

### ISSUE THREAD

**Issue by TechnologyGardening** [cfug/dio#2235]
### Request Statement

Is there anyway or method in dio using which dio can forward request via wifi. because dio is working fine with mobile data, but unable to connect via wifi.

### Solution Brainstorm

is there any way to check for internet connection and dio can be configured to use available connection.

**Comment by kuhnroyal** [comment]
Dio by default uses the HttpClient from the Dart SDK.
Wifi just works. If it does not, then you have some other problem.
Nothing dio can do here.

You can try to use the [native_dio_adapter](https://pub.dev/packages/native_dio_adapter) and see if that changes anything.
