### ISSUE TITLE
Header is out of order

### ISSUE THREAD

**Issue by vimaxwell** [cfug/dio#2253]
### Package

dio

### Version

5.4.3

### Operating-System

Android

### Adapter

Default Dio

### Steps to Reproduce
I want to follow my backend rule of api header order. But I can't do that in dio
```
var headers = {
  'a':'a',
  'b':'b',
  'c':'c',
  'd':'d'
};

var dio = Dio();
var response = await dio.request(
  'https://example.com/api',
  options: Options(
    method: 'GET',
    headers: headers,
  ),
);
```
### Expected Result

The server receives header in order as a,b,c,d

### Actual Result

the header is out of order in the server as c,a,b,d

**Comment by AlexV525** [comment]
We don't manipulate headers in any of our flows. Please check if there is an interceptor that touches your headers or provides a minimal reproducible example.

**Comment by AlexV525** [comment]
> I debug the code and found the lib using `http` package and that package can't keep header order @AlexV525

This is the HTTP implementation inside `dart:io`, not the `package:http`.

> I guess because it uses HashMap instead of LinkedHashMap https://github.com/dart-lang/sdk/blob/51ecf21356df5043f42270915aa22b76857941cd/sdk/lib/_http/http_headers.dart#L29

Cool. I guess you need a request to the Dart SDK then. Closing.
