### ISSUE TITLE
为什么dio的fromMap会将MultipartFile自动放入files字段中

### ISSUE THREAD

**Issue by tangdi0802** [cfug/dio#2261]
### Request Statement

在文件上传中，使用final formData = FormData.fromMap({
      'file': MultipartFile.fromBytes(file.bytes!),
    });
   进行单文件上传，会将file自动塞入files字段中。导致后端无法解析到file字段。
   能否添加一个标志，表示是否自动将file转化为files
这是dio FormData中的代码
if (fromMap != null) {
      // Use [encodeMap] to recursively add fields and files.
      // TODO(Alex): Write a proper/elegant implementation.
      encodeMap(
        fromMap,
        (key, value) {
          if (value is MultipartFile) {
            files.add(MapEntry(key, value));
          } else {
            fields.add(MapEntry(key, value?.toString() ?? ''));
          }
          return null;
        },
        listFormat: listFormat,
        encode: false,
      );
    }

**Comment by AlexV525** [comment]
Please submit issues using the correct issue template.
