### ISSUE TITLE
Dio 5.5 broke compilation for WASM

### ISSUE THREAD

**Issue by vaind** [cfug/dio#2266]
### Package

dio

### Version

5.5.0

### Operating-System

Web

### Adapter

Default Dio

### Output of `flutter doctor -v`

```shell
Flutter 3.22.2
```

### Steps to Reproduce

1. `flutter create dio_web`
2. `cd dio_web`
4. `flutter pub add dio:5.4.3+1`
5. Add some `dio` code to `lib/main.dart`, e.g. 
  ```dart
void main() async {
    final dio = Dio();
    final response = await dio.get('https://dart.dev');
    runApp(const MyApp());
}
```
6. `flutter build web --wasm` succeeds now
7. `flutter pub add dio:5.5.0`
8. `flutter build web --wasm` fails now

### Expected Result

Minor version bumps don't break existing users.

### Actual Result

Latest release broke users who already use wasm (or test against it, e.g. getsentry/sentry-dart)

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.


../../../.pub-cache/hosted/pub.dev/dio_web_adapter-1.0.1/lib/src/html/adapter.dart:5:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html';
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    main.dart => package:dio_web => package:dio => package:dio_web_adapter => dart:html
...
```

**Comment by kuhnroyal** [comment]
@vaind Can you please try to run against https://github.com/kuhnroyal/dio/tree/fix/wasm-compile

**Comment by kuhnroyal** [comment]
While your tests previously compiled for some reason, the dio package does not yet support WASM. So I don't fully grasp how the tests were successful.

**Comment by kuhnroyal** [comment]
The test seem to run now.
@AlexV525 We can probably publish this as `+1` and should be fine?

**Comment by vaind** [comment]
it worked just fine with WASM (verified in an actual web app locally). I assume it depends on what code ends up being tree-shaken or not.

**Comment by kuhnroyal** [comment]
Interesting, I have not looked very much into WASM yet.
Since we only have 2 default adapters and the `dart:html` based adapter is not working for WASM, that would mean that the `io` based adapter was compiled to WASM 🤔

**Comment by AlexV525** [comment]
@vaind Hopefully you'll get all passed tests after upgrading dio to v5.5.0+1.
