### ISSUE TITLE
`no address assoiated with hostname` error in release build apk

### ISSUE THREAD

**Issue by toknT** [cfug/dio#2288]
### Package

dio

### Version

5.3.3

### Operating-System

Android

### Adapter

Default Dio

### Steps to Reproduce

```ts
 Response response = await dio.post(
          url,
          data: {},
        );
```

### Expected Result

exec reques without error.

### Actual Result

`no address assoiated with hostname` error in release build apk, but success in debug build apk

**Comment by AlexV525** [comment]
Did you add the INTERNET permission to your release manifest?

**Comment by toknT** [comment]
add the INTERNET permission to manifest 😂
