### ISSUE TITLE
error: SocketException: Failed host lookup: 'xxx.com' (OS Error: nodename nor servname provided, or not known, errno = 7)

### ISSUE THREAD

**Issue by gitwangyang** [cfug/dio#2290]
### Package

dio

### Version

5.7.0

### Operating-System

Android, iOS

### Adapter

Default Dio

### Dart Version

3.5.0

### Steps to Reproduce

import 'package:dio/dio.dart';
 
void main() async {
  Dio dio = Dio();
 
  // 创建多个请求的Future列表
  List<Future<Response>> futures = [];
 
  // 添加请求到futures列表
  for (int i = 0; i < 10; i++) {
    futures.add(dio.get('https://api.example.com/data$i'));
  }
 
  // 使用Future.wait并发执行所有请求
  try {
    List<Response> responses = await Future.wait(futures);
    // 处理所有响应
    for (Response response in responses) {
      print(response.data);
    }
  } catch (e) {
    print(e);
  }
}

### Expected Result

no erro 

### Actual Result

SocketException: Failed host lookup: 'xxx.com' (OS Error: nodename nor servname provided, or not known, errno = 7)

**Comment by AlexV525** [comment]
与库无关，检查网络权限及网络状况。
