### ISSUE TITLE
Documentation: Transformer example link broken

### ISSUE THREAD

**Issue by eggzotic** [cfug/dio#2298]
### Package

dio

### Version

5.7.0

### Operating-System

Web

### Adapter

Default Dio

### Steps to Reproduce

Documentation at https://pub.dev/packages/dio#transformer refers to broken link https://github.com/cfug/dio/blob/main/example/lib/transformer.dart which should now be https://github.com/cfug/dio/blob/main/example_dart/lib/transformer.dart, I believe.

### Expected Result

https://github.com/cfug/dio/blob/main/example_dart/lib/transformer.dart (works)

### Actual Result

https://github.com/cfug/dio/blob/main/example/lib/transformer.dart (broken)

**Comment by AlexV525** [comment]
@eggzotic Would you like to submit a quick fix for it?
