### ISSUE TITLE
Build to web app get "Bad state: Future already completed" error when setup connectTimeout

### ISSUE THREAD

**Issue by cnsheggcn** [cfug/dio#2301]
### Package

dio

### Version

4.0.6

### Operating-System

Web

### Adapter

Default Dio

### Dart Version

3.3.3

### Steps to Reproduce

1.  d = Dio(
      BaseOptions(
        baseUrl: serviceBaseUrl,
        connectTimeout: kIsWeb ? 15000 : 3000,
        receiveTimeout: 15000,
      ),
    );

2. Response res = await BaseService.dio.get(
        "/api/xxxxx",
        queryParameters: {},
        options:  Options(headers: {"token": token}),
      );

3. flutter build web --dart2js-optimization O1

4. Error info in browser console:
     Bad state: Future already completed at Object.wrapException (main.dart.js:11200:43) at _AsyncCompleter.completeError$2 (main.dart.js:112665:17) at BrowserHttpClientAdapter_fetch_closure1.call$1 (main.dart.js:133593:25) at _RootZone.runUnary$2$2 (main.dart.js:114946:18) at _Future__propagateToListeners_handleValueCallback.call$0 (main.dart.js:113078:51) at Object._Future__propagateToListeners (main.dart.js:14540:93) at _Future._complete$1 (main.dart.js:112902:11) at Future_Future$delayed_closure.call$0 (main.dart.js:112512:22) at _TimerImpl_internalCallback.call$0 (main.dart.js:111914:21)
6.  Reason : The  haveSent var is not set to true correct when request has sent in  browser_adapter.dart ,it should be set to true after lines of :
 
xhr.onLoad.first.then((_) {

xhr.onProgress.listen((event) {

 xhr.onError.first.then((_) {

### Expected Result

no error when request sent success.

### Actual Result

Got "Bad state: Future already completed" error.

**Comment by AlexV525** [comment]
The issue has already been fixed in v5.
