### ISSUE TITLE
Random `SocketException`s: Connection refused / Failed host lookup

### ISSUE THREAD

**Issue by mingjunsiek** [cfug/dio#2304]
### Package

dio

### Version

5.7.0

### Operating-System

Android, iOS

### Adapter

Default Dio

### Dart Version

3.5.3

### Steps to Reproduce

This issue has been happening since we've updated to Flutter 3.24.0. We've received numerous reports from our users that the app is throwing errors when fetching from the backend. 

In our app, we rely on 2 Dio clients which calls 2 different base urls, v1 and v2.
From the error logs shown from the users, calls made to v1 is working well but calls made to v2 always throws either:

- DioException [connection error]: The connection errored: Failed host lookup: '[x.x.x](http://x.x.x)' This indicates an error which most likely cannot be solved by the library. Error: SocketException: Failed host lookup: '[x.x.x](http://x.x.x/)' (OS Error: nodename nor servname provided, or not known, errno = 8)
- [Dio - ErrorResponse]: DioException [connection error]: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library. Error: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = [x-x.x.x](http://x-x.x.x/), port = 38772

What I can confirm is that there is indeed internet connection established since concurrently, calls made to v1 was successful but for some reason, calls made to v2 fails. So this has nothing to do with network permissions and network status. Something in the library is somehow not allowing access to our v2 api even though access to v1 is fine.

### Expected Result

Should not throw socket exception when making the call to v2

### Actual Result

- DioException [connection error]: The connection errored: Failed host lookup: '[x.x.x](http://x.x.x/)' This indicates an error which most likely cannot be solved by the library. Error: SocketException: Failed host lookup: '[x.x.x](http://x.x.x/)' (OS Error: nodename nor servname provided, or not known, errno = 8)
- [Dio - ErrorResponse]: DioException [connection error]: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library. Error: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = [x-x.x.x](http://x-x.x.x/), port = 38772

**Comment by AlexV525** [comment]
Is this also happening with other implementations? Such as dart:io HttpClient and http Request

**Comment by mingjunsiek** [comment]
Can't really tell unless we swap out our implementation to http...

**Comment by AlexV525** [comment]
There should be nothing related to Dio AFAICT.

**Comment by AlexV525** [comment]
> I can confirm this issue happening in release. Usually starts after device goes to sleep.

@ziarehmank Can you provide a reproducible example and an use case?

**Comment by AlexV525** [comment]
> Usually starts after device goes to sleep.

*Failed to lookup host* and *Connection refused* should be nothing related to the library itself. However, swapping a new adapter might be helpful in this case.

**Comment by kuhnroyal** [comment]
I have noticed this as well but have not found the time to reproduce.

**Comment by AlexV525** [comment]
The only thing I can tell is I got tons of these in our Crashlytics too, but those issues occurred even when using only `HttpClient`. I've looked at the implementation of the client, it seems we barely have ways to check if a client is closed.

**Comment by ziarehmank** [comment]
I am using custom http client. Will this effect the library?. 
Also we confirm that this issue start happening after app wakes from sleep.

```
dio.httpClientAdapter = IOHttpClientAdapter(
    createHttpClient: () {
      final client = HttpClient();
      client.badCertificateCallback =
          (X509Certificate cert, String host, int port) {
        return //hosts;
      };
      return client;
    },
  );
```

**Comment by AlexV525** [comment]
All libraries that based on HttpClient should meet the same issue, which includes package:http.

**Comment by ziarehmank** [comment]
@AlexV525 you are right, still happening with http.

**Comment by AlexV525** [comment]
Closing based on the above threads.

**Comment by narendra-vaniya** [comment]
@mingjunsiek Have you discovered any resolution for this problem?

**Comment by kuhnroyal** [comment]
Try to use the native dapter.
