### ISSUE TITLE
Typing for extra

### ISSUE THREAD

**Issue by moshe5745** [cfug/dio#2315]
### Request Statement

Right now there is no typing for extras that could be passed to the request.
For instance, we want to pass some extra data to the interceptor.

**Comment by AlexV525** [comment]
What does typing help here? You can always safely cast fields by using `is`.

**Comment by moshe5745** [comment]
Guess you're right. This feature is not needed. After I understood the power of `is`

**Comment by AlexV525** [comment]
Also pattern matching is great when destructing extras. See https://dart.dev/language/patterns#validating-incoming-json.

**Comment by moshe5745** [comment]
> Also pattern matching is great when destructing extras. See https://dart.dev/language/patterns#validating-incoming-json.

Cant pattern match with class on the map object. Too bad...

**Comment by moshe5745** [comment]
> Also pattern matching is great when destructing extras. See https://dart.dev/language/patterns#validating-incoming-json.

If I have a class like:
```dart
class RequestMetadata {
  final int code;

  RequestMetadata({required this.code});
}
```
I can pattern match it on interceptor only with this
```dart
  var code = switch (options.extra) { {"code": int code} => code, _ => "" };
```
Not a perfect situation.
