### ISSUE TITLE
Return a different Error Code when JSON object could not be composed

### ISSUE THREAD

**Issue by liquidiert** [cfug/dio#2322]
### Request Statement

When Dio fails to compose a JSON object (say the toJson function of the object in question is faulty) it returns an error 500 leading to believe the server couldn't handle the request. Without the log interceptor this can be very confusing.

### Solution Brainstorm

Use a different error code to indicate to the developer that the client is the problem:
- maybe 451 (Unavailable for legal Reasons) because it would be funny
- and more serious 499 (client closed request)

**Comment by AlexV525** [comment]
We don't manipulate responses. Please provide a minimal reproducible example and submit the issue using the correct issue template (BUG report).
