### ISSUE TITLE
Is it a problem that the Dio library cannot be viewed using the Networks view in Flutter's devtools to view the requests made by Dio?

### ISSUE THREAD

**Issue by xhc-code** [cfug/dio#2326]
### Package

dio

### Version

dio: ^5.4.3+1

### Operating-System

Android

### Adapter

Default Dio

### Output of `flutter doctor -v`

```shell
• Flutter version 3.24.3 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Platform android-35, build-tools 35.0.0
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[✓] Network resources
    • All expected network resources are available.
```

### Dart Version

3.5.3

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/c352b707-2cff-4bc9-b838-2f9a3cc3a19a)
![image](https://github.com/user-attachments/assets/816b6e55-a4b4-48a9-b2e5-f2a85ef92c7c)

The HTTP interface requests sent cannot be displayed and are all displayed as sockets.

### Expected Result

Actual display of the request address and parameter information of the interface

### Actual Result

Cannot display the true information of the request sent.

---
In the issue of devtool, many people have also encountered such problems, and the final conclusion is that Dio may not have used the basic request library provided by Flutter, which resulted in devtool being unable to capture requests sent through Dio.
https://github.com/flutter/devtools/issues/8518

**Comment by AlexV525** [comment]
Are you using `native_dio_adapter`?

**Comment by xhc-code** [comment]
> Are you using `native_dio_adapter`?

yes，The httpClientAdapter parameter is not configured。

**Comment by AlexV525** [comment]
Could you write a minimal reproducible example?

**Comment by xhc-code** [comment]
好的。

**Comment by xhc-code** [comment]
https://github.com/xhc-code/my_flutter_network_problem.git
![image](https://github.com/user-attachments/assets/31af0a07-c2cb-4858-bf36-bfa8bcc98971)

The code here includes both HTTP and sockets when using Dio to request linked data. Moreover, the number of socket and get requests is not equal.

**Comment by AlexV525** [comment]
As far as I know, there is no guarantee of the equality of HTTP requests and socket connections.

Your example shows HTTP requests in the DevTools, meaning the inspection works out of the box. Closing as not related and please check if your adapter has been changed during the runtime.
