### ISSUE TITLE
Request to Add Concurrency Limit Feature to Dio

### ISSUE THREAD

**Issue by TheWalkingDead1024** [cfug/dio#2332]
### Request Statement

Hi Dio Team,

I'd like to request a feature that allows setting a limit on the number of concurrent HTTP requests in Dio. This would be useful for managing server load and complying with API rate limits.

Proposed Solution: Implement a configurable setting in the Dio package to control the number of simultaneous requests that can be made, possibly through a queue mechanism that holds excess requests until previous ones have completed.

Rationale: This feature would help prevent overloading servers and improve app performance by avoiding hitting rate limits set by external APIs.

Looking forward to your thoughts on this.

Best regards,

**Comment by AlexV525** [comment]
You can implementing this by a counter lock (or a mutex) + the interceptor. Every request requires a lock and each lock will be released when the request is done or error.
