### ISSUE TITLE
FormData problem with Cyrillic characters

### ISSUE THREAD

**Issue by konstantin-doncov** [cfug/dio#695]
When I send `FormData` which has `String` with Latin characters, I get this:

```
----dio-boundary-0956346409
content-disposition: form-data; name="MyRequest"

{"someInt":5,"someBool":true,"someString":"English text"}
----dio-boundary-0956346409--
```

And this is ok, I think.
But when I send `FormData` with Cyrillic(Russian) characters, I get this:
```
----dio-boundary-2698561535
content-disposition: form-data; name="MyRequest"
content-type: text/plain; charset=utf-8
content-transfer-encoding: binary

{"someInt":5,"someBool":true,"someString":"Русский текст"}
----dio-boundary-2698561535--
```

So, I get extra `content-type` and `content-transfer-encoding` fields.
I also have the same issue if my `FormData` has only a `String`. 
I think this is the wrong behavior because:
- `FormData` has a `content-type: text/plain` even if it contains not only `String`
- `FormData` has a different behavior for Latin and Cyrillic alphabets.

Is it a bug? And how can I get rid of a `content-type` and `content-transfer-encoding` fields?

**Comment by don-prog** [comment]
Guys, I still have this issue. Can anyone help me with this?

**Comment by 1232209** [comment]
same here,did you solved?

**Comment by Darnelo-Inc** [comment]
i have the same problem...

**Comment by Arteandr** [comment]
HELP!

**Comment by Arteandr** [comment]
> same here,did you solved?

did you solve it

**Comment by AlexV525** [comment]
Please file new issues with a minimal reproducible example if anyone still sees the issue.
